(function (root) {
  'use strict';
  const E = typeof module !== 'undefined' && module.exports ? require('./evidence.js') : root.MietteEvidence;
  const annotations = {};
  const foods = [];
  function detail(profile, why, step, options = {}) {
    const p = E.profiles[profile];
    if (!p) throw new Error('Profil alimentaire inconnu : ' + profile);
    const refs = [...new Set([...(options.sources || []), ...p.sources])];
    return {
      status: p.status, reason: why, preparation: [step, ...p.steps].filter(Boolean), sources: refs,
      evidence: { profile, why, sources: refs, basis: options.basis || 'family', note: options.note || '' },
      ...(options.family ? { family: options.family } : {})
    };
  }
  const original = (id, profile, why, step, options) => { annotations[id] = detail(profile, why, step, options); };
  const named = { basis: 'specific' };

  original('avocado', 'produce', 'La chair de l’avocat peut se manger crue. Le point sensible est la peau : le couteau peut transférer ce qui se trouve à sa surface vers la chair au moment de l’ouverture.', 'Laver l’avocat entier avant de le couper ; préparer le guacamole avec des ustensiles propres.');
  original('salmon', 'fish', 'Le saumon frais bien cuit fait partie des poissons à privilégier pour varier les espèces, notamment les poissons gras. La fiche ne couvre pas le saumon fumé ni le gravlax.', 'Cuire le pavé jusqu’au centre ; vérifier la partie la plus épaisse.', named);
  original('mozzarella', 'dairy', 'Une mozzarella au lait pasteurisé est différente d’un fromage affiné à croûte fleurie. Elle peut se manger froide si la pasteurisation, la date et le maintien au froid sont vérifiés.', 'Pour une salade tomate-mozzarella, vérifier aussi le lavage des tomates.', named);
  original('eggs', 'eggs', 'L’œuf n’est pas exclu pendant la grossesse : c’est la présence de blanc ou de jaune encore cru qui motive la précaution contre Salmonella. Œufs à la coque, mollets et au plat au jaune coulant ne répondent pas au repère français.', 'Pour un œuf dur, vérifier que le jaune est pris jusqu’au centre.', named);
  original('strawberries', 'produce', 'Les fraises se mangent sans épluchage et peuvent porter des traces de terre. Le lavage est donc la condition pratique avant de les manger crues, y compris lorsqu’elles viennent du jardin.', 'Rincer soigneusement les fraises à l’eau potable avant de les équeuter.');
  original('brie', 'softCheese', 'Brie et camembert sont des fromages à pâte molle et croûte fleurie explicitement écartés froids par les recommandations françaises. La mention « lait pasteurisé » ne lève pas cette précaution contre Listeria.', 'Dans une recette, le fromage doit être entièrement chauffé, pas seulement coulant en surface.', named);
  original('broccoli', 'cookedProduce', 'Le brocoli peut faire partie des repas. Ses petites fleurettes demandent un nettoyage attentif ; une cuisson vapeur complète permet ensuite de le servir sans garniture crue mal lavée.', 'Séparer les fleurettes pour les laver, puis cuire selon la texture souhaitée.');
  original('yogurt', 'dairy', 'Le yaourt nature fabriqué avec du lait pasteurisé fait partie des laitages possibles. La fermentation seule ne remplace pas la vérification du lait utilisé et de la conservation.', 'Choisir un pot intact, respecter la date limite et le délai après ouverture.', named);
  original('apple', 'produce', 'Une pomme peut être consommée avec sa peau si elle est bien lavée. L’épluchage ne remplace pas le lavage préalable, car les mains et le couteau touchent ensuite la chair.', 'Rincer et frotter la pomme sous l’eau potable avant de la croquer ou de l’éplucher.');
  original('banana', 'produce', 'La peau protège la chair de la banane, mais les mains qui l’épluchent peuvent ensuite toucher la partie mangée. Le repère relève de l’hygiène des fruits, pas d’une interdiction de la banane.', 'Laver la peau et les mains avant de peler ; écarter les parties altérées.');
  original('tomato', 'produce', 'Tomates et tomates cerises peuvent se manger crues lorsque leur lavage est maîtrisé. Le fromage ou la charcuterie ajoutés dans la salade se vérifient séparément.', 'Rincer toutes les faces de la tomate et retirer les parties abîmées.');
  original('spinach', 'cookedProduce', 'Les feuilles d’épinards peuvent retenir de la terre dans leurs replis. Elles ont leur place parmi les légumes ; les folates alimentaires ne remplacent pas une supplémentation prescrite.', 'Séparer et laver les feuilles avant de les cuire.', { sources: ['nutrition'] });
  original('carrot', 'produce', 'La carotte pousse dans le sol : retirer la terre est la première précaution. Une carotte lavée puis épluchée peut se manger râpée si le matériel de préparation est propre.', 'Laver avant d’éplucher et râper au moment de la préparation.');
  original('zucchini', 'cookedProduce', 'La courgette n’est pas un aliment à exclure pendant la grossesse. Dans une poêlée ou un velouté, l’enjeu est de laver le légume puis de conserver correctement le plat.', 'Laver la peau avant de couper en rondelles ou en dés.');
  original('lettuce', 'produce', 'Les feuilles de salade peuvent retenir de la terre et des microbes. Une salade servie crue ne bénéficie pas d’une cuisson : il faut donc pouvoir faire confiance à son lavage et à sa conservation.', 'Séparer les feuilles, éliminer la terre et rincer soigneusement ; suivre aussi les instructions des sachets.', { sources: ['ameli'] });
  original('raspberry', 'produce', 'Les framboises sont fragiles et ne s’épluchent pas. Elles se consomment crues après un rinçage soigneux ; une barquette prête à manger ne dispense pas de lire les instructions.', 'Rincer doucement sans écraser et retirer les fruits altérés.');
  original('melon', 'produce', 'Le melon est un cas où laver la peau est utile même si on ne la mange pas : la lame traverse cette surface avant d’atteindre la chair. Le melon découpé doit ensuite rester au froid.', 'Laver et frotter l’écorce avant découpe, puis réfrigérer les morceaux non consommés.', { basis: 'specific', sources: ['produce'] });
  original('potato', 'potato', 'La pomme de terre bien cuite est un féculent possible. Le choix d’un tubercule sain compte aussi : les zones vertes ou très germées signalent une autre précaution, liée aux glycoalcaloïdes.', 'Préférer vapeur, purée ou four à partir de pommes de terre saines.', named);
  original('mushroom', 'cookedProduce', 'Cette fiche concerne des champignons de culture identifiés, comme le champignon de Paris. Elle ne permet pas de juger une cueillette sauvage : la cuisson ne garantit pas l’absence de toxines d’un champignon mal identifié.', 'Nettoyer les champignons de culture et les cuire ; ne pas appliquer cette fiche à une espèce sauvage inconnue.');
  original('sprouts', 'sprouts', 'Alfalfa, luzerne et autres graines germées crues constituent une exception parmi les végétaux : les bactéries peuvent se multiplier pendant la germination, y compris à l’intérieur de la graine.', 'Dans un bowl, remplacer la garniture de pousses crues par un légume lavé et cuit.', named);
  original('milk', 'dairy', 'Le lait pasteurisé ou UHT a subi un traitement thermique. Il peut être bu sans nouvelle cuisson si ses conditions de conservation sont respectées ; après ouverture, même le lait UHT doit être conservé selon l’étiquette.', 'Suivre la température et la durée après ouverture indiquées sur la brique.', named);
  original('raw-milk', 'rawMilk', 'Le lait cru à boire est explicitement déconseillé pendant la grossesse. Une provenance locale ou un achat directement à la ferme ne remplace pas la pasteurisation.', 'Utiliser une version pasteurisée ou UHT pour les boissons et les préparations.', named);
  original('comte', 'hardCheese', 'Comté et emmental appartiennent aux pâtes pressées cuites admises par les recommandations françaises, même pour un comté au lait cru. Cette exception tient au procédé du fromage, pas au seul mot « lait cru ».', 'Acheter un morceau, retirer sa croûte et le râper soi-même si besoin.', named);
  original('parmesan', 'hardCheese', 'Le parmesan en morceau figure parmi les fromages possibles. Il faut distinguer ce morceau dont on retire la croûte d’un fromage déjà râpé et conservé en sachet.', 'Râper juste avant de servir avec une râpe propre.', named);
  original('feta', 'dairy', 'La feta au lait pasteurisé est un fromage possible selon le NHS. Le sel de la saumure ne permet pas à lui seul de conclure à la sécurité d’une feta au lait cru ou mal conservée.', 'Vérifier le lait utilisé et conserver dans les conditions prévues par le fabricant.', named);
  original('ricotta', 'dairy', 'La ricotta pasteurisée peut être utilisée froide ou dans une recette cuite. Sa texture fraîche ne pose pas la même question que la croûte d’un fromage affiné, mais son maintien au froid reste nécessaire.', 'Contrôler le traitement du lait ou du lactosérum et la date après ouverture.', named);
  original('goat', 'softCheese', 'Ce repère concerne le chèvre affiné à croûte fleurie, par exemple certaines bûches. Il ne s’étend pas automatiquement à tout fromage de chèvre : un chèvre frais pasteurisé sans cette croûte se juge différemment.', 'Choisir du chèvre frais pasteurisé ou une préparation entièrement cuite.', named);
  original('roquefort', 'softCheese', 'Roquefort et fromages bleus à pâte molle sont écartés consommés froids en raison de Listeria. Leur affinage et leur humidité comptent ; enlever une croûte ne suffit pas à rendre la pâte compatible froide.', 'Une sauce au bleu doit être entièrement chauffée ; sinon choisir un autre fromage.', named);
  original('reblochon', 'softCheese', 'Reblochon et morbier sont des pâtes pressées non cuites à affinage court, explicitement citées par Santé publique France. Leur aspect plus ferme ne leur donne pas le même repère que le comté.', 'Pour une tartiflette, vérifier que le centre du plat est fumant et entièrement chauffé.', named);
  original('cream', 'dairy', 'Une crème pasteurisée ou UHT peut être utilisée pendant la grossesse. « Crème fraîche » décrit un produit, mais ne dispense pas de vérifier le traitement, notamment pour une crème fermière.', 'Choisir la mention pasteurisée ou UHT et utiliser un ustensile propre pour prélever.', named);
  original('chicken', 'poultry', 'Le poulet bien cuit reste une source de protéines possible. La précaution concerne surtout les bactéries de la volaille crue et la cuisson de la partie la plus épaisse, même si la peau est déjà dorée.', 'Pour un poulet entier, contrôler plusieurs parties épaisses sans toucher l’os.', named);
  original('turkey', 'poultry', 'Une escalope ou un rôti de dinde doit être cuit intégralement, comme le poulet. Un rôti épais peut rester insuffisamment cuit au centre alors que ses bords paraissent prêts.', 'Vérifier 74 °C à cœur, y compris pour une farce contenant de la volaille.');
  original('beef', 'meat', 'Un steak de bœuf saignant laisse de la viande insuffisamment cuite au centre. Pendant la grossesse, la prévention de la toxoplasmose justifie de demander une cuisson complète, même pour une viande de bonne qualité.', 'Au restaurant, demander une cuisson bien cuite et vérifier avant de manger.', named);
  original('ground-beef', 'groundMeat', 'Le steak haché nécessite une cuisson dans toute son épaisseur car le hachage peut disperser la contamination. Un burger avec un centre rosé ou cru ne répond pas à cette précaution.', 'Pour du bœuf haché, viser au moins 71 °C au centre avec un thermomètre.');
  original('pork', 'meat', 'Une côte ou un rôti de porc peut être consommé entièrement cuit. Le repère de cette viande fraîche ne s’applique pas au jambon cru ou au saucisson, dont la fabrication ne comporte pas cette cuisson.', 'Cuire les morceaux jusqu’au centre et éviter le contact du plat cuit avec le jus cru.');
  original('tartare', 'rawMeat', 'Tartare et carpaccio de viande sont servis sans cuisson. Leur préparation au dernier moment, le citron ou la congélation ne permettent pas d’écarter tous les risques infectieux.', 'Remplacer par un steak bien cuit ; vérifier aussi l’œuf cru parfois ajouté au tartare.', named);
  original('salami', 'rawMeat', 'Saucisson et jambon cru sont salés ou séchés, mais pas cuits comme une viande fraîche. Les recommandations françaises les écartent consommés tels quels, même si l’emballage est récent.', 'Choisir une autre garniture cuite à cœur ; ne pas se fier au seul affinage.', named);
  original('ham', 'deli', 'Le jambon blanc est déjà cuit à la fabrication mais peut être contaminé ensuite. Santé publique France recommande pendant la grossesse de l’éviter froid et propose de le recuire, par exemple dans un gratin.', 'Mettre le jambon dans le plat avant cuisson, pas en garniture froide au moment de servir.', named);
  original('pate', 'deli', 'Pâtés et rillettes réfrigérés sont prêts à manger et peuvent permettre la multiplication de Listeria. Cette fiche vise le rayon frais ; un produit stérilisé en conserve fermée n’a pas le même traitement, et une recette au foie a une précaution supplémentaire.', 'Vérifier la forme du produit ; préférer une autre tartinade préparée et conservée correctement.', named);
  original('cod', 'fish', 'Le cabillaud fait partie des espèces proposées pour varier les poissons pendant la grossesse. Il reste à cuire complètement : son classement favorable face au mercure ne supprime pas les précautions du poisson cru.', 'Cuire le filet jusqu’au centre, selon son épaisseur.', named);
  original('trout', 'fish', 'La truite fraîche bien cuite est une espèce proposée pour varier les poissons. La truite fumée prête à manger est une autre préparation, avec une précaution contre Listeria.', 'Choisir de la truite fraîche à cuire plutôt que des tranches fumées.', named);
  original('sardines', 'fish', 'La sardine fait partie des poissons gras conseillés dans la variété des repas. Fraîche, elle doit être bien cuite ; une sardine marinée crue n’est pas équivalente.', 'Cuire les sardines fraîches entièrement ; vérifier la conservation après achat.', named);
  original('smoked-salmon', 'rawFish', 'Le saumon fumé est un aliment réfrigéré souvent mangé sans nouvelle cuisson. C’est notamment le risque de Listeria qui motive l’évitement, même lorsque le poisson a été congelé auparavant.', 'Pour des pâtes au saumon, préférer du saumon frais entièrement cuit.', named);
  original('sushi', 'rawFish', 'Un sushi au poisson cru combine une absence de cuisson du poisson et plusieurs manipulations avant consommation. Le poisson congelé contre les parasites ne garantit pas l’absence de Listeria.', 'Choisir une version avec poisson bien cuit ou légumes bien lavés et vérifier le maintien au froid du riz.', named);
  original('shrimp', 'shellfish', 'Les crevettes achetées crues pour être cuites peuvent être au menu après cuisson complète. Les crevettes déjà cuites et décortiquées vendues au frais sont explicitement distinguées dans les recommandations françaises.', 'Cuire entièrement les crevettes crues puis les décortiquer avec des mains propres.', named);
  original('mussels', 'shellfish', 'Les moules peuvent être cuisinées si leur provenance est contrôlée et leur cuisson complète. Le vin blanc d’une recette marinière ajoute un problème distinct : la cuisson ne garantit pas que tout son alcool ait disparu.', 'Préparer les moules avec de l’eau ou du bouillon plutôt que du vin.', { sources: ['spf'] });
  original('oysters', 'rawShellfish', 'Une huître crue est un coquillage consommé sans étape qui détruirait les microbes. Sa fraîcheur, le citron et l’immunité à la toxoplasmose ne lèvent pas la recommandation d’éviter les coquillages crus.', 'Choisir une préparation entièrement cuite, et non un simple gratinage de surface.', named);
  original('tuna', 'mercury', 'Le thon est un poisson prédateur que les recommandations françaises demandent de limiter, y compris en conserve. La stérilisation de la boîte traite les microbes mais ne retire pas le méthylmercure.', 'Alterner une consommation de thon avec d’autres espèces plutôt que multiplier les boîtes dans la semaine.', named);
  original('seabass', 'mercury', 'Bar et dorade figurent dans la liste française des poissons prédateurs sauvages à limiter. L’espèce et la provenance importent ; si elles ne sont pas connues, la fiche retient ce repère prudent.', 'Demander l’espèce et la provenance au vendeur, puis varier avec des espèces conseillées.', named);
  original('swordfish', 'highMercury', 'Espadon et requin sont explicitement déconseillés pendant la grossesse à cause du mercure. Le mot « saumonette » peut désigner un petit requin et ne doit pas être confondu avec le saumon.', 'Vérifier l’espèce et choisir un autre poisson.', named);
  original('lentils', 'grains', 'Les lentilles permettent de varier les protéines végétales et les féculents. Le repère vise les graines bien cuites ; des lentilles germées crues relèvent de la précaution sur les graines germées.', 'Cuire les lentilles sèches selon le paquet, ou utiliser une conserve prête à consommer.');
  original('chickpeas', 'grains', 'Les pois chiches cuits ou en conserve peuvent servir dans un plat ou un houmous. Le mixage ne prolonge pas la conservation : un houmous maison reste une préparation à garder rapidement au froid.', 'Utiliser des pois chiches déjà cuits, une conserve intacte et du matériel propre.');
  original('quinoa', 'grains', 'Le quinoa se prépare comme un féculent et peut varier les accompagnements. Il n’exige pas d’exclusion particulière dans les recommandations générales ; la cuisson et la conservation de la salade comptent.', 'Rincer puis cuire selon le paquet ; refroidir rapidement si vous préparez une salade.');
  original('rice', 'rice', 'Le riz bien préparé peut être mangé pendant la grossesse. Sa particularité est la conservation après cuisson : laisser une casserole longtemps tiède peut permettre la multiplication de Bacillus cereus.', 'Préparer seulement la quantité nécessaire ou répartir immédiatement les restes en petits contenants.', named);
  original('pasta', 'grains', 'Des pâtes entièrement cuites, même fabriquées avec des œufs, ne sont pas une préparation à l’œuf cru. La sauce peut en revanche changer le repère : carbonara à l’œuf encore liquide, alcool ou fromage à risque.', 'Cuire les pâtes selon le paquet et choisir une sauce dont tous les ingrédients sont adaptés.');
  original('bread', 'grains', 'Un pain complet a déjà été cuit : il peut être mangé tel quel et n’a pas besoin d’être recuit pour la grossesse. La précaution sur la farine crue concerne la pâte avant cuisson.', 'Conserver le pain au sec selon son conditionnement ; vérifier séparément la garniture du sandwich.');
  original('oats', 'grains', 'Les flocons d’avoine peuvent varier les petits-déjeuners. Leur préparation dépend du produit : suivre l’emballage, notamment si les flocons demandent une cuisson, et vérifier le lait utilisé.', 'Pour un porridge, cuire avec de l’eau ou du lait pasteurisé ou UHT.');
  original('almonds', 'nuts', 'Amandes et noix ne sont pas à supprimer par principe pendant la grossesse. La principale exception propre à la personne est une allergie ; une version nature permet de limiter les ajouts de sel ou de sucre.', 'Choisir des fruits à coque sains et bien conservés.', named);
  original('chocolate', 'sweet', 'Le chocolat est classé à limiter pour sa place parmi les produits sucrés ou gras, et parce que le cacao apporte de la caféine. Un chocolat fourré à la liqueur demande en plus d’éviter l’alcool.', 'Compter la caféine avec celle des boissons.', { sources: ['efsa', 'caffeineAmounts'], note: 'Ordres de grandeur EFSA : 50 g de chocolat noir apportent environ 20 mg de caféine, contre environ 5 mg pour 50 g de chocolat au lait. Ces valeurs varient selon le produit ; total retenu : 200 mg/jour au maximum.' });
  original('mousse', 'rawEggs', 'La mousse et le tiramisu maison sont concernés lorsqu’ils contiennent des œufs crus. Le tiramisu peut aussi ajouter du café et de l’alcool ; changer seulement le fromage ne résout pas ces points.', 'Choisir une version sans œuf cru ni alcool et compter le café éventuel.', named);
  original('mayonnaise', 'rawEggs', 'La mayonnaise maison traditionnelle contient un jaune cru. Le citron, la moutarde et le réfrigérateur ne remplacent pas une pasteurisation ou une cuisson contre Salmonella.', 'Choisir une préparation dont le traitement est confirmé et respecter le délai après ouverture.', named);
  original('tofu', 'soy', 'Tofu et tempeh sont des aliments à base de soja. La cuisson ou la fermentation ne permettent pas de conclure qu’ils ne contiennent plus d’isoflavones : le guide applique la précaution française.', 'Pour un curry ou un bowl, remplacer par des pois chiches ou des lentilles.', named);
  original('water', 'water', 'L’eau potable, plate ou gazeuse, est la boisson à privilégier. Le gaz n’ajoute ni alcool ni caféine ; pour une eau aromatisée, vérifier les ingrédients ajoutés.', 'Boire régulièrement dans un verre ou une gourde propre.', named);
  original('coffee', 'caffeine', 'Le café n’est pas systématiquement interdit : c’est l’exposition totale à la caféine qui se limite. Une grande tasse filtre peut apporter plus de caféine qu’un petit espresso malgré un goût moins intense.', 'Vérifier le volume et le nombre de cafés, puis ajouter le thé, le cola et le chocolat de la journée.', { ...named, note: 'Exemples indicatifs EFSA : un café filtre de 200 ml ≈ 90 mg ; un espresso de 60 ml ≈ 80 mg. Le repère choisi est 200 mg/jour toutes sources confondues, même si certaines autres autorités utilisent un repère différent.' });
  original('tea', 'caffeine', 'La théine est la même molécule que la caféine. Thé noir, thé vert et matcha participent donc au total quotidien ; la dose de feuilles ou de poudre et l’infusion modifient la teneur.', 'Ne pas convertir le repère en un nombre fixe de bols de matcha.', { ...named, note: 'L’EFSA donne environ 50 mg pour 220 ml de thé noir, à titre indicatif. Le matcha n’a pas une teneur universelle par tasse. Additionner toutes les sources pour rester au maximum à 200 mg/jour.' });
  original('cola', 'caffeine', 'Un cola peut apporter de la caféine même lorsqu’il est sans sucre. À l’inverse, « sans caféine » ne signifie pas nécessairement « sans sucre » : les deux informations se lisent séparément.', 'Lire la composition et privilégier l’eau au quotidien.', { ...named, note: 'Ordre de grandeur EFSA : environ 40 mg de caféine pour 355 ml de cola. Vérifier la marque et le volume ; ce chiffre ne s’applique pas à toutes les recettes.' });
  original('energy-drink', 'energy', 'Les boissons énergisantes sont explicitement déconseillées par l’Assurance Maladie pendant la grossesse. Une petite canette peut déjà contribuer fortement au total de caféine, et la version sans sucre reste concernée.', 'Remplacer par de l’eau plutôt que par une autre boisson stimulante.', named);
  original('wine', 'alcohol', 'Vin, bière et spiritueux contiennent le même agent en cause : l’éthanol. Il n’existe pas de type d’alcool préférable pendant la grossesse ni de trimestre où la recommandation zéro alcool serait levée.', 'Pour un repas festif, choisir une boisson dont l’absence d’alcool est confirmée.', named);
  original('soy-drink', 'soy', 'La boisson au soja est concernée par la précaution française sur les isoflavones. L’enrichissement en calcium ou la mention bio ne modifie pas ce point ; cela ne la rend pas non plus équivalente à toutes les autres boissons végétales.', 'Pour une substitution régulière des laitages, faire vérifier l’équilibre nutritionnel du choix retenu.', named);
  original('herbal-tea', 'herbs', 'Il n’est pas possible de donner le même feu vert à toutes les tisanes : une menthe en feuilles, un mélange contenant de la réglisse et un extrait concentré n’ont pas le même profil.', 'Vérifier le nom de chaque plante et les quantités ; une mention « naturel » ne suffit pas.');

  function add(category, art, family, profile, rows) {
    for (const [id, name, why, step, aliases = '', options = {}] of rows) {
      foods.push({ id, name, category, art, family, group: profile, summary: step || E.profiles[profile].title, aliases, origin: 'guide', ...detail(profile, why, step, { family, ...options }) });
    }
  }

  add('produce', 'apple', 'fruit', 'produce', [
    ['pineapple', 'Ananas', 'La chair d’ananas peut se manger crue après une préparation propre. Cette fiche applique les recommandations générales sur les fruits : elles ne prévoient pas d’exclusion de l’ananas consommé comme aliment.', 'Laver l’écorce avant découpe, puis retirer la peau avec un couteau propre.', 'anans pineapple'],
    ['pear', 'Poire', 'La poire se consomme avec ou sans peau. Dans les deux cas, un lavage avant découpe évite de transporter la contamination de surface vers la chair.', 'Laver avant de croquer, d’éplucher ou de pocher.', 'poires'],
    ['peach', 'Pêche', 'La pêche peut se manger fraîche. Sa peau duveteuse demande un rinçage soigneux ; l’éplucher reste un choix de préparation après lavage.', 'Rincer toutes les faces et retirer les parties abîmées.', 'pêches peche'],
    ['nectarine', 'Nectarine', 'La nectarine est souvent mangée avec sa peau lisse : le lavage du fruit entier est donc la condition principale avant consommation crue.', 'Laver avant de couper autour du noyau.', 'nectarines brugnon brugnons'],
    ['apricot', 'Abricot', 'L’abricot frais peut varier les fruits des repas. Le repère concerne sa chair lavée, avec le noyau retiré, et non des extraits ou compléments.', 'Rincer avant de dénoyauter.', 'abricots'],
    ['plum', 'Prune', 'La prune se mange généralement avec sa peau. Un lavage reste nécessaire même pour des fruits cueillis chez soi.', 'Laver puis retirer le noyau.', 'prunes quetsche reine claude mirabelle'],
    ['cherry', 'Cerise', 'Les cerises fraîches ne demandent pas d’éviction particulière au titre des recommandations générales sur les fruits ; elles se lavent avant d’être mangées.', 'Rincer les cerises avant de retirer les queues et les noyaux.', 'cerises'],
    ['grape', 'Raisin', 'Les grains de raisin sont mangés avec leur peau et parfois servis directement en grappe. Il faut les rincer soigneusement plutôt que compter sur l’aspect propre de la grappe.', 'Rincer les grains sur toutes les faces et retirer ceux qui sont altérés.', 'raisins'],
    ['kiwi', 'Kiwi', 'Le kiwi épluché reste un fruit possible. Le couteau et les doigts touchent d’abord sa peau : un lavage avant ouverture est utile.', 'Laver avant de couper ou de peler.', 'kiwis'],
    ['orange', 'Orange', 'L’orange peut être consommée en quartiers après lavage de la peau et épluchage. Une orange entière et un jus non pasteurisé préparé ailleurs ne se jugent pas de la même manière.', 'Laver l’écorce avant de peler.', 'oranges'],
    ['mandarin', 'Mandarine', 'Même lorsqu’on épluche la mandarine à la main, les doigts peuvent toucher les quartiers après la peau. La précaution relève de l’hygiène des fruits.', 'Laver le fruit et les mains avant d’éplucher.', 'mandarines'],
    ['clementine', 'Clémentine', 'La clémentine est un fruit à peau retirée ; la laver avant de l’éplucher limite le transfert depuis l’extérieur vers les quartiers.', 'Rincer la peau avant de peler.', 'clementines'],
    ['lemon', 'Citron', 'Le citron peut parfumer un plat. Son jus ne désinfecte pas de façon fiable une viande, un poisson ou un œuf cru : l’acidité ne remplace pas leur cuisson.', 'Laver le citron avant de le couper ou de prélever le zeste.', 'citrons', { sources: ['spf'] }],
    ['lime', 'Citron vert', 'Le citron vert lavé peut servir d’assaisonnement. Dans un ceviche, il ne transforme pas le poisson cru en poisson cuit au sens des précautions de grossesse.', 'Laver avant de presser ou de zester.', 'lime limes', { sources: ['spf'] }],
    ['grapefruit', 'Pamplemousse & pomelo', 'Le pamplemousse lavé et épluché relève du repère général des fruits. En cas de traitement, la compatibilité avec le médicament doit être vérifiée séparément auprès du pharmacien.', 'Laver l’écorce avant découpe ; suivre les consignes de vos médicaments.', 'pomelos pamplemousses', { sources: ['interactions'] }],
    ['mango', 'Mangue', 'La mangue mûre peut se manger en dés ou en tranches. Sa peau n’étant pas consommée, le point pratique est surtout d’éviter le transfert par le couteau.', 'Laver avant de retirer la peau et le noyau.', 'mangues'],
    ['papaya', 'Papaye mûre', 'Cette fiche applique les repères généraux des fruits à la chair d’une papaye mûre préparée pour être mangée. Elle ne porte pas sur le latex, les extraits ou les compléments de papaye.', 'Laver le fruit, retirer peau et graines, puis couper avec un couteau propre.', 'papayes'],
    ['passion-fruit', 'Fruit de la passion', 'La pulpe du fruit de la passion se mange après ouverture de la coque. Comme pour le melon, la lame traverse la surface avant d’atteindre la partie consommée.', 'Laver la coque avant de couper et prélever la pulpe.', 'maracuja grenadille'],
    ['pomegranate', 'Grenade', 'Les grains de grenade peuvent agrémenter un plat après une préparation propre. Le lavage de l’écorce précède l’ouverture et le détachement des grains.', 'Laver puis ouvrir sur une planche propre.', 'grenades'],
    ['fig', 'Figue fraîche', 'La figue fraîche se mange souvent entière avec sa peau fine. Elle doit donc être rincée même si elle est fragile et paraît propre.', 'Rincer doucement et écarter les figues abîmées.', 'figues'],
    ['persimmon', 'Kaki', 'Le kaki mûr peut varier les fruits. Sa peau se lave avant de manger la chair, qu’on choisisse de l’éplucher ou de la prélever à la cuillère.', 'Laver puis découper sur une surface propre.', 'kakis plaquemine'],
    ['lychee', 'Litchi', 'Le litchi est un fruit dont on retire l’enveloppe ; l’hygiène des mains pendant l’épluchage est donc importante pour ne pas contaminer la chair.', 'Laver l’enveloppe avant de peler, puis retirer le noyau.', 'litchis lychee'],
    ['guava', 'Goyave', 'La goyave destinée à être mangée fraîche relève des mêmes précautions que les autres fruits crus, notamment lorsque sa peau est consommée.', 'Rincer et frotter avant de couper.', 'goyaves'],
    ['dragon-fruit', 'Fruit du dragon', 'Le pitaya se consomme après ouverture de sa peau. La chair peut être mangée crue lorsque la préparation et la conservation sont propres.', 'Laver avant de couper et réfrigérer la chair restante.', 'pitaya pitahaya'],
    ['watermelon', 'Pastèque', 'La pastèque a une grande écorce qui peut contaminer la lame lors de la découpe. Les morceaux préparés doivent ensuite être conservés au froid.', 'Laver l’écorce avant découpe et utiliser une planche propre.', 'pasteque watermelon'],
    ['blueberry', 'Myrtille', 'Les myrtilles se mangent sans épluchage : leur lavage reste nécessaire, y compris lorsqu’elles sont vendues en petite barquette.', 'Rincer soigneusement à l’eau potable.', 'myrtilles bleuets'],
    ['blackberry', 'Mûre', 'La mûre se compose de petites parties qui retiennent des impuretés. Rincer sans écraser permet de la préparer pour une consommation crue.', 'Laver doucement et retirer les fruits altérés.', 'mures mûres'],
    ['redcurrant', 'Groseille', 'Les groseilles fraîches peuvent être ajoutées à un dessert après lavage. Vérifier séparément les œufs ou la crème de ce dessert.', 'Rincer avant d’égrapper.', 'groseilles'],
    ['blackcurrant', 'Cassis', 'Les baies de cassis préparées comme fruit ne sont pas équivalentes à un extrait de plante ou à une liqueur de cassis. Le lavage reste la précaution pour les baies fraîches.', 'Rincer puis retirer les tiges.', 'baies cassis'],
    ['cranberry', 'Canneberge fraîche', 'La canneberge en fruit peut entrer dans une préparation alimentaire. Cette fiche ne valide pas une cure de gélules ou d’extraits concentrés.', 'Laver puis préparer selon la recette.', 'cranberry cranberries'],
    ['coconut', 'Noix de coco fraîche', 'La chair de noix de coco peut être mangée après une ouverture propre. Une fois extraite, elle doit être conservée comme un aliment préparé, selon son conditionnement.', 'Nettoyer l’extérieur avant ouverture et utiliser des ustensiles propres.', 'coco'],
    ['starfruit', 'Carambole', 'La carambole lavée relève ici des recommandations générales sur les fruits. Il existe une exception importante, indépendante de la grossesse : la National Kidney Foundation demande de l’éviter en cas de maladie rénale, car certaines de ses substances peuvent alors devenir toxiques.', 'Laver avant de trancher. En cas de maladie rénale, éviter la carambole et suivre les conseils de votre équipe soignante.', 'caramboles', { sources: ['starfruit'], note: 'Le repère général ne s’applique pas en cas de maladie rénale.' }],
    ['quince', 'Coing à cuire', 'Le coing se prépare habituellement cuit en compote ou en morceaux. Le lavage précède l’épluchage ; une pâte de coing très sucrée demande aussi de modérer la portion.', 'Laver, éplucher et cuire selon la recette.', 'coings'],
    ['rhubarb', 'Rhubarbe, tiges à cuire', 'Cette fiche concerne uniquement les tiges de rhubarbe préparées en cuisine. Une compote se juge aussi selon son sucre ajouté ; les feuilles ne sont pas un aliment couvert par ce repère.', 'Laver les tiges, retirer les feuilles et cuire selon la recette.', 'rhubarbe tiges']
  ]);

  add('produce', 'veggies', 'vegetable', 'cookedProduce', [
    ['sweet-potato', 'Patate douce', 'La patate douce est un féculent possible pendant la grossesse. Sa chair orangée n’entraîne pas la précaution liée au rétinol du foie : on applique ici les repères des végétaux lavés puis cuits.', 'Laver, éplucher si souhaité et cuire à cœur, au four ou à la vapeur.', 'patates douces sweet potato', { sources: ['nhs'] }],
    ['eggplant', 'Aubergine', 'L’aubergine cuite peut varier les légumes d’un repas. Le statut concerne le légume préparé ; une sauce ou un gratin doit aussi utiliser des ingrédients adaptés.', 'Laver avant de couper puis cuire la chair.', 'aubergines'],
    ['cauliflower', 'Chou-fleur', 'Les bouquets du chou-fleur peuvent retenir de la terre dans leurs interstices. Les séparer avant lavage facilite sa préparation pour une cuisson complète.', 'Détacher les bouquets, laver puis cuire.', 'chou fleur choux fleurs'],
    ['romanesco', 'Chou romanesco', 'La forme serrée du romanesco demande le même soin de nettoyage que les autres choux à bouquets. La grossesse ne justifie pas son exclusion une fois préparé.', 'Diviser en bouquets, laver puis cuire.', 'romanesco'],
    ['brussels-sprouts', 'Choux de Bruxelles', 'Les choux de Bruxelles sont des légumes à feuilles serrées, différents des graines germées crues malgré le mot anglais « sprouts ». Ils peuvent se manger cuits.', 'Retirer les feuilles abîmées, laver et cuire.', 'chou bruxelles'],
    ['green-cabbage', 'Chou vert', 'Les feuilles de chou vert peuvent retenir des impuretés entre les couches. Une préparation lavée puis cuite peut faire partie des repas.', 'Détacher les feuilles nécessaires, les rincer puis les cuire.', 'choux verts chou frisé'],
    ['red-cabbage', 'Chou rouge', 'Le chou rouge peut être préparé cuit ; pour une version crue émincée, il faut maîtriser le lavage et la propreté de la râpe ou du couteau.', 'Retirer les feuilles abîmées et laver avant d’émincer.', 'choux rouges'],
    ['white-cabbage', 'Chou blanc', 'Le chou blanc peut être cuit ou préparé cru après lavage. Une salade de type coleslaw nécessite aussi de vérifier la sauce, notamment l’absence d’œuf cru.', 'Laver les feuilles avant de les couper.', 'choux blancs coleslaw'],
    ['chinese-cabbage', 'Chou chinois', 'Les feuilles de chou chinois peuvent retenir des impuretés à leur base. Dans un wok, une garniture crue ajoutée après cuisson doit elle aussi être bien lavée.', 'Séparer et rincer les feuilles avant cuisson.', 'pe tsai pak choi bok choy'],
    ['kale', 'Chou kale', 'Les feuilles frisées du kale demandent un lavage attentif. Une cuisson est une façon simple de le préparer lorsqu’on veut éviter une salade crue difficile à nettoyer.', 'Laver les replis, retirer les parties dures et cuire.', 'kale chou kale'],
    ['leek', 'Poireau', 'Le poireau retient fréquemment de la terre entre ses couches. L’ouvrir avant de le rincer permet de nettoyer les parties qui seront cuisinées.', 'Fendre puis rincer entre les feuilles avant cuisson.', 'poireaux'],
    ['onion', 'Oignon', 'L’oignon peut parfumer les plats. Sa peau sèche se retire, mais les mains et la planche qui la touchent ne doivent pas contaminer les autres aliments prêts à manger.', 'Peler proprement puis préparer dans la recette.', 'oignons'],
    ['shallot', 'Échalote', 'L’échalote cuisinée ne nécessite pas d’exclusion pendant la grossesse. Pour une vinaigrette crue, le matériel de coupe et la préparation doivent rester propres.', 'Peler puis hacher avec un couteau propre.', 'echalotes'],
    ['garlic', 'Ail', 'L’ail utilisé pour assaisonner un plat est un usage alimentaire. Ce repère ne porte pas sur des gélules, huiles essentielles ou extraits concentrés d’ail.', 'Peler les gousses et cuisiner selon la recette.', 'gousse ail'],
    ['beetroot', 'Betterave', 'La betterave peut être préparée cuite après nettoyage de la terre. Une betterave vendue déjà cuite exige de respecter la date et le froid indiqués.', 'Laver puis cuire, ou suivre l’emballage d’une betterave cuite.', 'betteraves'],
    ['turnip', 'Navet', 'Le navet est un légume racine : son contact avec le sol explique la nécessité de laver avant d’éplucher et de couper.', 'Laver, éplucher puis cuire.', 'navets'],
    ['parsnip', 'Panais', 'Le panais peut servir en purée ou rôti. Comme les autres racines, il faut retirer la terre sans la transférer à la chair pendant l’épluchage.', 'Laver avant d’éplucher et cuire en morceaux.', 'panais racine'],
    ['rutabaga', 'Rutabaga', 'Le rutabaga lavé et cuit est une façon de varier les légumes racines. Les restes de purée doivent être rapidement réfrigérés.', 'Laver, éplucher et cuire jusqu’à tendreté.', 'chou navet'],
    ['celeriac', 'Céleri-rave', 'Le céleri-rave demande un nettoyage avant épluchage. En rémoulade, la sauce doit être examinée séparément car une mayonnaise maison peut contenir de l’œuf cru.', 'Laver et éplucher ; cuire ou préparer avec une sauce adaptée.', 'celeri rave remoulade'],
    ['celery', 'Céleri branche', 'La base et les creux des branches de céleri peuvent retenir des impuretés. Le légume peut être consommé après lavage maîtrisé ou cuisson.', 'Séparer les branches et rincer leurs creux.', 'celeri branches'],
    ['fennel', 'Fenouil, bulbe', 'Le bulbe de fenouil cuisiné comme légume n’est pas une infusion de graines ni un extrait concentré. Cette fiche porte uniquement sur le bulbe préparé pour un repas.', 'Retirer les parties abîmées, laver et préparer le bulbe.', 'fenouil bulbes'],
    ['asparagus', 'Asperge', 'Les asperges ont des pointes et une base à nettoyer avant cuisson. Elles peuvent être consommées dans un plat ou en salade après une cuisson et une conservation adaptées.', 'Rincer, préparer les tiges et cuire.', 'asperges'],
    ['artichoke', 'Artichaut', 'L’artichaut peut être mangé après préparation et cuisson. Une sauce à l’œuf cru ou une conservation prolongée du plat poserait une question distincte.', 'Laver avant cuisson et utiliser une sauce adaptée.', 'artichauts'],
    ['jerusalem-artichoke', 'Topinambour', 'La surface irrégulière du topinambour peut retenir de la terre. Un nettoyage attentif précède son utilisation en soupe ou en purée.', 'Brosser sous l’eau, éplucher si nécessaire puis cuire.', 'topinambours'],
    ['salsify', 'Salsifis', 'Le salsifis est une racine qui se prépare après nettoyage du sol. Une version en conserve prête à consommer n’a pas besoin du même épluchage.', 'Laver et éplucher la racine fraîche avant cuisson.', 'scorsonere'],
    ['green-beans', 'Haricots verts', 'Les haricots verts cuits peuvent accompagner les repas. Le repère vise les gousses préparées, pas des graines germées crues.', 'Rincer, équeuter puis cuire selon la recette.', 'haricot vert'],
    ['peas', 'Petits pois', 'Les petits pois cuits, frais, surgelés ou en conserve peuvent varier les légumes. Les formes surgelées doivent être préparées comme l’indique le sachet.', 'Cuire selon les instructions et conserver rapidement les restes.', 'petit pois pois verts'],
    ['snow-peas', 'Pois mange-tout', 'Les pois mange-tout se préparent avec leur gousse, ce qui rend utile le lavage de toute la surface avant cuisson.', 'Rincer les gousses, préparer puis cuire.', 'pois gourmands'],
    ['pumpkin', 'Potiron', 'Le potiron est préparé après découpe d’une écorce qui peut porter de la terre. Nettoyer cette surface protège la chair au passage de la lame.', 'Laver avant de découper, puis cuire la chair.', 'citrouille potirons'],
    ['red-kuri', 'Potimarron', 'La peau du potimarron est parfois gardée dans la recette. Il faut alors particulièrement bien la nettoyer avant cuisson.', 'Frotter sous l’eau, retirer les graines et cuire.', 'potimarrons'],
    ['butternut', 'Courge butternut', 'La courge butternut peut se préparer en soupe, en purée ou rôtie. L’écorce se lave avant d’être traversée par le couteau.', 'Laver avant d’éplucher et de découper.', 'doubeurre butternuts'],
    ['spaghetti-squash', 'Courge spaghetti', 'La courge spaghetti cuite peut varier les accompagnements. La sauce ajoutée à sa chair filamenteuse se vérifie indépendamment.', 'Laver l’écorce, ouvrir prudemment et cuire selon la recette.', 'courges spaghetti'],
    ['pattypan', 'Pâtisson', 'Le pâtisson est une courge dont les replis doivent être nettoyés avant de couper ou de garder la peau dans une recette.', 'Laver les replis puis cuire.', 'patisson patissons'],
    ['chard', 'Blette', 'Feuilles et côtes de blette peuvent retenir de la terre. Elles se préparent après lavage, avec une cuisson adaptée à leurs épaisseurs différentes.', 'Séparer, laver puis cuire les côtes et les feuilles.', 'blettes bettes poirée'],
    ['endive', 'Endive', 'L’endive peut se manger cuite, ou crue lorsque son nettoyage est maîtrisé. Dans un gratin au jambon, celui-ci doit être recuit à cœur avec le plat.', 'Nettoyer les feuilles et utiliser des ingrédients adaptés.', 'endives chicon'],
    ['okra', 'Gombo', 'Le gombo cuisiné comme légume entre dans le repère général des végétaux. La surface des gousses se lave avant découpe.', 'Rincer puis cuire dans le plat.', 'gombos okra'],
    ['chayote', 'Chayotte', 'La chayotte cuite peut varier les légumes. Laver avant épluchage évite de transporter les impuretés extérieures vers la chair.', 'Laver, éplucher puis cuire.', 'christophine chouchou chayote'],
    ['corn', 'Maïs doux', 'Le maïs doux cuit ou en conserve peut entrer dans un repas. En salade composée, les autres ingrédients et le maintien au froid déterminent aussi la sécurité du plat.', 'Cuire l’épi ou suivre les indications de la conserve.', 'mais épi maïs doux'],
    ['plantain', 'Banane plantain', 'La banane plantain est ici un féculent à cuisiner, distinct de la banane dessert mangée crue. Laver la peau avant de peler puis cuire selon la recette.', 'Laver, peler et cuire la chair.', 'plantains'],
    ['yam', 'Igname à cuire', 'Cette fiche concerne l’igname alimentaire du commerce préparée selon ses instructions. Le nom du tubercule ne suffit pas à valider une espèce sauvage ou une consommation crue.', 'Éplucher et cuire complètement selon les indications du vendeur.', 'ignames']
  ]);

  add('produce', 'veggies', 'vegetable', 'produce', [
    ['cucumber', 'Concombre', 'Le concombre est souvent mangé cru avec ou sans peau. Le lavage doit précéder l’épluchage et la découpe ; vérifier aussi le yaourt d’un tzatziki.', 'Laver et frotter la peau avant préparation.', 'concombres'],
    ['bell-pepper', 'Poivron', 'Le poivron peut être mangé cru après lavage ou cuit dans un plat. Le soin de préparation est le même pour les variétés rouges, jaunes et vertes.', 'Laver l’extérieur puis retirer pédoncule et graines.', 'poivrons'],
    ['radish', 'Radis', 'Le radis pousse dans la terre et est souvent consommé cru. Un nettoyage complet de la racine est donc nécessaire.', 'Retirer la terre, couper les extrémités et rincer soigneusement.', 'radis rose radis noir daikon'],
    ['rocket', 'Roquette', 'La roquette se mange généralement crue et ne bénéficie donc pas d’une cuisson. Vérifier le lavage, même pour une poignée ajoutée sur une pizza après le four.', 'Rincer soigneusement les feuilles avant de servir.', 'roquette rucola'],
    ['lambs-lettuce', 'Mâche', 'Les rosettes de mâche peuvent retenir de la terre à leur base. Le rinçage doit atteindre cette zone avant une consommation en salade.', 'Séparer les rosettes si nécessaire et retirer toute terre.', 'mache doucette'],
    ['watercress', 'Cresson de culture', 'Cette fiche porte sur le cresson acheté dans un circuit alimentaire contrôlé. Elle ne valide pas une plante sauvage ramassée au bord d’un cours d’eau.', 'Laver soigneusement ; préférer une préparation cuite si le lavage est incertain.', 'cresson'],
    ['sorrel', 'Oseille', 'L’oseille utilisée comme légume ou condiment frais se prépare après lavage. La quantité culinaire décrite ne vaut pas avis sur des extraits de plante.', 'Rincer les feuilles puis préparer dans la recette.', 'oseille feuilles']
  ]);

  add('produce', 'leafy', 'herb', 'produce', [
    ['parsley', 'Persil frais', 'Quelques feuilles de persil dans un plat sont un usage culinaire. Elles peuvent porter de la terre comme une salade et doivent être lavées ; cette fiche ne couvre pas les extraits concentrés.', 'Laver avant de hacher, même pour une petite garniture.', 'persil plat frisé'],
    ['coriander', 'Coriandre fraîche', 'La coriandre fraîche est souvent ajoutée après cuisson. Son lavage est donc nécessaire même si le plat principal est servi très chaud.', 'Rincer feuilles et tiges avant de ciseler.', 'coriandre cilantro'],
    ['basil', 'Basilic frais', 'Le basilic peut parfumer les repas après lavage. Dans un pesto, vérifier aussi le fromage utilisé et le délai de conservation de la préparation.', 'Rincer les feuilles avant de les mixer ou de les ajouter.', 'basilic pesto'],
    ['mint', 'Menthe fraîche en cuisine', 'La menthe fraîche utilisée dans une salade ou une sauce relève des herbes alimentaires lavées. Ce repère ne se transpose pas à une huile essentielle ou à un extrait.', 'Laver les feuilles avant usage culinaire.', 'menthe feuilles'],
    ['chives', 'Ciboulette', 'La ciboulette ciselée est souvent servie sans cuisson. Sa petite quantité ne dispense pas de la laver avant de la couper.', 'Rincer puis ciseler avec du matériel propre.', 'ciboulette ciboule'],
    ['dill', 'Aneth frais', 'L’aneth peut aromatiser un plat après lavage. L’ajouter à du saumon fumé ne modifie pas la précaution propre au saumon fumé.', 'Rincer les brins avant de les hacher.', 'aneth'],
    ['thyme', 'Thym en cuisine', 'Le thym utilisé comme assaisonnement alimentaire n’est pas une huile essentielle ni un traitement par les plantes. Laver les brins frais avant usage.', 'Employer la quantité culinaire de la recette.', 'thym frais'],
    ['rosemary', 'Romarin en cuisine', 'Quelques brins de romarin dans un plat correspondent à un usage alimentaire. Cette fiche ne donne pas de validation pour une infusion concentrée, une gélule ou une huile essentielle.', 'Laver les brins frais et utiliser comme assaisonnement.', 'romarin frais'],
    ['ginger', 'Gingembre en cuisine', 'Le gingembre frais peut servir d’assaisonnement dans un plat. Une cure, un complément ou une préparation concentrée contre les nausées nécessite un avis distinct sur la dose.', 'Laver la racine avant d’éplucher et de râper.', 'gingembre frais']
  ]);

  add('dairy', 'milk', 'dairy', 'dairy', [
    ['burrata', 'Burrata', 'La burrata associe une enveloppe de fromage frais et une garniture crémeuse. Le repère est celui des fromages frais : vérifier la pasteurisation de l’ensemble et le maintien au froid.', 'Choisir une burrata explicitement pasteurisée et respecter sa date.'],
    ['mascarpone', 'Mascarpone', 'Le mascarpone pasteurisé peut être utilisé dans un dessert. Il ne rend pas compatible un tiramisu qui contient aussi de l’œuf cru ou de l’alcool.', 'Vérifier la pasteurisation et toute la recette.', '', named],
    ['fromage-blanc', 'Fromage blanc', 'Le fromage blanc fabriqué avec du lait pasteurisé est un laitage frais possible. La date et le délai après ouverture comptent, même pour une version nature.', 'Choisir du lait pasteurisé et conserver au froid.'],
    ['skyr', 'Skyr', 'Le skyr est un produit laitier frais. Sa texture épaisse ou sa teneur en protéines ne renseignent pas sur le traitement du lait : la pasteurisation reste à vérifier.', 'Lire le traitement du lait et les consignes du pot.'],
    ['petit-suisse', 'Petit-suisse', 'Le petit-suisse peut être consommé s’il est fabriqué avec du lait pasteurisé et bien conservé. Les versions aromatisées peuvent aussi ajouter du sucre.', 'Vérifier la pasteurisation et la conservation.', 'petits suisses'],
    ['cottage-cheese', 'Cottage cheese', 'Ce fromage frais en grains est possible lorsqu’il est pasteurisé. Il ne se juge pas comme un fromage à croûte fleurie ; l’étiquette et le froid restent nécessaires.', 'Choisir une version pasteurisée.', '', named],
    ['cream-cheese', 'Fromage frais à tartiner', 'Un fromage frais à tartiner pasteurisé peut servir sur du pain. Les couteaux déjà utilisés pour d’autres aliments peuvent contaminer le pot après ouverture.', 'Vérifier le lait utilisé et prélever avec un couteau propre.', 'fromage tartiner cheese cream'],
    ['fresh-goat', 'Chèvre frais pasteurisé', 'Le chèvre frais sans croûte fleurie est distinct d’une bûche affinée. Le repère concerne une version pasteurisée, correctement conservée.', 'Vérifier qu’il s’agit bien de chèvre frais pasteurisé.', 'chevre frais'],
    ['halloumi', 'Halloumi pasteurisé', 'Un halloumi fabriqué avec du lait pasteurisé est cité parmi les fromages possibles par le NHS. Le griller n’exonère pas de vérifier son étiquette et sa conservation.', 'Choisir du lait pasteurisé et préparer selon l’emballage.', '', named],
    ['paneer', 'Paneer', 'Le paneer est un fromage frais utilisé en cuisine. Cette fiche applique le repère des fromages frais pasteurisés ; une fabrication maison au lait cru ne bénéficie pas de la même information.', 'Vérifier le traitement du lait et chauffer dans le plat si prévu.'],
    ['butter', 'Beurre pasteurisé', 'Le beurre pasteurisé peut entrer dans les repas en quantité adaptée. La mention cru ou une fabrication fermière demande de vérifier le traitement plutôt que de se fier à la couleur ou au goût.', 'Choisir du beurre pasteurisé et respecter sa conservation.', 'beurre doux demi sel'],
    ['greek-yogurt', 'Yaourt à la grecque', 'Le yaourt à la grecque peut se manger si le lait est pasteurisé et la conservation respectée. Sa texture crémeuse ne justifie pas à elle seule une interdiction.', 'Vérifier le lait et la durée après ouverture.', 'yaourt grec'],
    ['sheep-yogurt', 'Yaourt de brebis', 'Le yaourt de brebis suit la même précaution de traitement que celui au lait de vache. L’espèce de l’animal ne remplace pas la pasteurisation.', 'Choisir un yaourt au lait pasteurisé.', 'brebis yaourts']
  ]);
  add('dairy', 'cheese', 'cheese', 'hardCheese', [
    ['beaufort', 'Beaufort', 'Le beaufort est une pâte pressée cuite explicitement citée comme possible pendant la grossesse. Même au lait cru, il relève de cette exception de fabrication.', 'Retirer la croûte et préférer un morceau.', '', named],
    ['gruyere', 'Gruyère', 'Le gruyère appartient aux pâtes pressées cuites admises dans les recommandations. Un sachet de fromage râpé se vérifie autrement qu’un morceau entier.', 'Acheter en morceau et râper soi-même.', 'gruyere suisse', named]
  ]);
  add('dairy', 'cheese', 'cheese', 'softCheese', [
    ['munster', 'Munster', 'Le munster est un fromage à pâte molle et croûte lavée cité parmi les fromages à éviter froids. Une pasteurisation éventuelle du lait ne suffit pas à changer cette consigne.', 'Choisir une autre variété ou une cuisson complète.', '', named],
    ['gorgonzola', 'Gorgonzola', 'Le gorgonzola est un fromage bleu à pâte molle. Le NHS distingue sa consommation froide d’une préparation chauffée jusqu’à être fumante à cœur.', 'Chauffer complètement la sauce, pas simplement faire fondre.', '', named],
    ['pont-leveque', 'Pont-l’évêque', 'Le pont-l’évêque relève de la famille des fromages à pâte molle et croûte lavée. Poum lui applique la précaution française sur cette famille, même si le lait est pasteurisé.', 'Éviter froid ; choisir une pâte pressée cuite sans croûte.', 'pont l eveque'],
    ['epoisses', 'Époisses', 'L’époisses est un fromage à pâte molle et croûte lavée. Le guide applique la précaution contre Listeria liée à cette famille de fromages affinés.', 'Privilégier un autre fromage pour une consommation froide.', 'epoisses'],
    ['taleggio', 'Taleggio', 'Le taleggio est un fromage mou affiné à croûte lavée : Poum applique la recommandation générale sur cette famille de fromages consommés froids.', 'Choisir une préparation entièrement chauffée ou un autre fromage.']
  ]);
  add('protein', 'meat', 'meat', 'meat', [
    ['lamb', 'Agneau', 'L’agneau peut être mangé entièrement cuit. Une côte rosée ou un gigot saignant ne répondent pas au repère contre la toxoplasmose pendant la grossesse.', 'Cuire jusqu’au centre, y compris près de l’os.', 'agneaux gigot'],
    ['veal', 'Veau', 'Le veau est une viande possible lorsqu’il est bien cuit. Un carpaccio de veau reste une préparation crue malgré une viande très claire.', 'Vérifier la cuisson dans la partie la plus épaisse.', 'escalope veau'],
    ['rabbit', 'Lapin', 'Le lapin acheté dans un circuit alimentaire peut être cuisiné à cœur. Une sauce au vin ajoute une précaution séparée concernant l’alcool résiduel.', 'Cuire complètement et choisir une sauce sans alcool.', 'lapins'],
    ['mutton', 'Mouton', 'La viande de mouton doit être entièrement cuite comme les autres viandes. Un mijotage se vérifie au centre des morceaux et pas seulement à la température de la sauce.', 'Cuire tous les morceaux jusqu’au cœur.'],
    ['fresh-sausage', 'Saucisse fraîche à cuire', 'Une saucisse fraîche est une préparation de viande à cuire. Sa coloration extérieure peut arriver avant la cuisson complète de la farce ; ne pas la confondre avec un saucisson sec.', 'Cuire la farce intégralement selon l’emballage.', 'chipolata merguez saucisses'],
    ['bacon', 'Lardons & poitrine à cuire', 'Les lardons crus ou fumés sont destinés à une cuisson. Le fumage et le sel n’éliminent pas les précautions de la viande crue.', 'Cuire entièrement avant de les incorporer au plat.', 'lardon bacon poitrine'],
    ['meatballs', 'Boulettes de viande', 'Des boulettes peuvent contenir un centre encore insuffisamment cuit, même dans une sauce chaude. Il faut vérifier leur cuisson dans toute l’épaisseur.', 'Cuire à cœur selon la viande ; 71 °C pour viande hachée, 74 °C pour volaille.', 'boulette kefta', { sources: ['temperature'] }]
  ]);
  add('protein', 'poultry', 'poultry', 'poultry', [
    ['duck', 'Canard', 'Le canard est une volaille : pendant la grossesse, un magret saignant ne répond pas au repère de cuisson complète. Le foie gras est une autre préparation à vérifier séparément.', 'Cuire à cœur, sans se fier au seul gras bien grillé.', 'magret canard'],
    ['guinea-fowl', 'Pintade', 'La pintade doit être cuite dans toute son épaisseur comme les autres volailles. Le temps dépend de sa taille et du mode de cuisson.', 'Vérifier la température dans les parties épaisses.', 'pintades'],
    ['quail', 'Caille', 'La petite taille d’une caille ne dispense pas de cuire complètement la volaille. Une farce peut demander un contrôle supplémentaire au centre.', 'Vérifier la cuisson à cœur, y compris de la farce.', 'cailles'],
    ['goose', 'Oie', 'Une oie entière est une grosse pièce de volaille dont la cuisson peut être inégale. Le repère vise la viande ; le foie et les produits de foie sont traités séparément.', 'Contrôler plusieurs parties épaisses et la farce éventuelle.', 'oies']
  ]);
  add('protein', 'eggs', 'eggs', 'eggs', [
    ['quail-eggs', 'Œufs de caille', 'Les œufs de caille ne bénéficient pas d’une exemption par rapport aux œufs de poule. Blanc et jaune doivent être entièrement cuits pour appliquer le repère français.', 'Cuire jusqu’à ce que le centre du jaune soit ferme.', 'oeufs caille']
  ]);
  add('protein', 'meat', 'offal', 'liver', [
    ['liver', 'Foie & produits de foie', 'Le foie se distingue des autres viandes par sa teneur élevée en rétinol. Même bien cuit, il reste concerné par la recommandation du NHS de l’éviter pendant la grossesse.', 'Choisir une autre viande bien cuite.', 'foie veau foie volaille abats foie', named],
    ['foie-gras', 'Foie gras', 'Le foie gras est un produit de foie : Poum retient la précaution du NHS liée au rétinol. Une forme mi-cuite réfrigérée ajoute la question de Listeria ; une conserve stérilisée ne règle pas la teneur en vitamine A.', 'Remplacer par une tartinade sans foie, bien préparée.', 'foie gras mi cuit', { sources: ['spf'], basis: 'family' }]
  ]);
  add('fish', 'fish', 'fish', 'fish', [
    ['hake', 'Merlu', 'Le merlu figure parmi les espèces proposées pour varier les poissons. Il peut se manger bien cuit ; la mention colin ne renseigne pas toujours à elle seule sur l’espèce exacte.', 'Vérifier l’espèce puis cuire le filet à cœur.', 'merlus', named],
    ['pollock', 'Lieu noir & lieu jaune', 'Les lieus font partie des poissons proposés par Santé publique France. Une préparation panée peut masquer un centre encore cru : suivre les consignes de cuisson.', 'Cuire complètement jusqu’au centre.', 'lieu colin lieu', named],
    ['haddock-fresh', 'Églefin frais', 'L’églefin frais relève ici du repère général des poissons bien cuits et variés. Il est distinct du haddock fumé, qui appelle une vérification de la préparation et de la cuisson.', 'Choisir du poisson frais à cuire entièrement.', 'eglefin aiglefin'],
    ['whiting', 'Merlan', 'Le merlan fait partie des espèces proposées pour alterner les poissons. Il garde les mêmes précautions de cuisson et de conservation que les autres poissons frais.', 'Cuire les filets intégralement.', 'merlans', named],
    ['sole', 'Sole', 'La sole est un poisson possible parmi les espèces à varier. Sa chair fine peut cuire vite, mais le temps de recette ne garantit pas à lui seul une cuisson complète.', 'Vérifier la cuisson de toute la chair.', 'soles', named],
    ['plaice', 'Carrelet', 'Le carrelet relève ici du repère général des poissons bien cuits et variés. La cuisson à cœur reste nécessaire même pour un poisson qui n’est pas dans la liste des prédateurs à limiter.', 'Cuire intégralement selon l’épaisseur.', 'plie carrelets'],
    ['mackerel', 'Maquereau', 'Le maquereau courant peut varier les poissons gras, selon les recommandations françaises. Le nom exact de l’espèce reste utile pour les produits importés ; une version fumée froide se juge différemment.', 'Choisir une préparation bien cuite et varier les espèces.', 'maquereaux', named],
    ['herring', 'Hareng frais', 'Le hareng frais peut entrer dans la variété des poissons. Cette fiche ne couvre pas les filets fumés, salés ou marinés mangés sans cuisson.', 'Acheter frais puis cuire complètement.', 'harengs', named],
    ['anchovy', 'Anchois frais', 'Les anchois frais sont cités parmi les poissons possibles. Des filets salés à l’huile ne sont pas automatiquement équivalents à du poisson entièrement cuit.', 'Cuire les anchois frais à cœur.', 'anchois frais', named]
  ]);
  add('fish', 'fish', 'fish', 'cannedFish', [
    ['canned-sardines', 'Sardines en conserve', 'Une conserve stérilisée de sardines n’est pas un poisson cru. La sardine est une espèce conseillée pour varier les poissons ; le conditionnement doit rester intact et la conservation après ouverture respectée.', 'Choisir une boîte intacte et suivre le délai après ouverture.', 'sardines boite conserve'],
    ['canned-mackerel', 'Maquereau en conserve', 'Une conserve stérilisée de maquereau a subi un traitement thermique. Elle peut varier les repas de poisson, en vérifiant l’espèce, les ingrédients de la sauce et l’état de la boîte.', 'Vérifier la sauce et conserver selon l’étiquette après ouverture.', 'maquereau boite conserve']
  ]);
  add('fish', 'fish', 'seafood', 'shellfish', [
    ['crab', 'Crabe à cuire', 'Le crabe cru acheté pour être cuit peut se préparer avec les précautions des crustacés. Une chair déjà décortiquée réfrigérée a subi des manipulations supplémentaires et ne relève pas de cette même fiche.', 'Cuire entièrement puis décortiquer proprement.', 'tourteau araignée mer'],
    ['lobster', 'Homard à cuire', 'Le homard de provenance contrôlée peut être préparé entièrement cuit. La cuisson et les manipulations après cuisson sont plus pertinentes que le caractère festif de l’aliment.', 'Cuire complètement et servir aussitôt.', 'homards langouste'],
    ['langoustine', 'Langoustine à cuire', 'Les langoustines doivent être entièrement cuites avant de manger la chair. Un produit vendu cuit décortiqué au frais ne reçoit pas ici le même repère.', 'Acheter dans un circuit contrôlé puis cuire.', 'langoustines'],
    ['scallop', 'Noix de Saint-Jacques', 'Les Saint-Jacques peuvent se manger bien cuites. Une noix juste saisie qui garde un centre cru reste insuffisamment cuite pour le repère de grossesse.', 'Cuire à cœur, pas seulement colorer chaque face.', 'coquille saint jacques pétoncle'],
    ['clam', 'Palourdes & coques', 'Palourdes et coques sont des coquillages à acheter dans un circuit contrôlé puis à cuire. Les laver ne remplace pas la cuisson.', 'Suivre les consignes du vendeur et cuire complètement.', 'palourde coque vongole'],
    ['whelk', 'Bulots & bigorneaux à cuire', 'Ces coquillages se consomment après cuisson complète. Cette fiche porte sur ceux achetés pour être cuits, pas sur un plateau froid dont on ne connaît pas la conservation.', 'Vérifier la provenance et les consignes de cuisson.', 'bulot bigorneau'],
    ['squid', 'Calamar & encornet', 'Le calamar et l’encornet peuvent être cuisinés entièrement. Une cuisson très brève pour préserver la texture ne suffit que si toute la chair a réellement cuit.', 'Cuire toute l’épaisseur et respecter le froid.', 'calamars encornets seiche'],
    ['octopus', 'Poulpe', 'Le poulpe servi cuit peut entrer dans un repas si sa préparation est maîtrisée. Une salade de poulpe cuite puis refroidie dépend aussi de la chaîne du froid.', 'Cuire complètement et réfrigérer rapidement si servi plus tard.', 'pieuvre poulpes']
  ]);
  add('fish', 'fish', 'fish', 'mercury', [
    ['monkfish', 'Lotte', 'La lotte, ou baudroie, fait partie des poissons prédateurs sauvages à limiter pendant la grossesse. La cuisson ne supprime pas le mercure accumulé.', 'Alterner avec des poissons conseillés, bien cuits.', 'baudroie lottes', named],
    ['halibut', 'Flétan', 'Le flétan figure dans la liste française des prédateurs sauvages à limiter. La forme en filet ou en pavé n’enlève pas cette précaution.', 'Espacer les consommations et varier les poissons.', 'fletan halibut', named],
    ['ray', 'Raie', 'La raie est citée parmi les poissons à limiter pendant la grossesse pour le mercure. Une aile de raie bien cuite reste concernée.', 'Varier avec une autre espèce à chaque repas de poisson.', 'raies aile raie', named],
    ['pike', 'Brochet', 'Le brochet est un poisson prédateur d’eau douce présent dans la liste de limitation. La provenance et la répétition des consommations comptent.', 'Vérifier la provenance et choisir souvent d’autres espèces.', 'brochets', named],
    ['eel', 'Anguille', 'L’anguille figure parmi les prédateurs sauvages à limiter. Une recette laquée, fumée ou cuite ne permet pas de retirer le mercure.', 'Varier les espèces et choisir une préparation bien cuite.', 'anguilles unagi', named],
    ['bonito', 'Bonite', 'La bonite fait partie des poissons prédateurs à limiter dans les recommandations françaises. Le séchage ou la mise en conserve n’annulent pas la précaution sur le mercure.', 'Vérifier l’espèce et espacer les consommations.', 'bonites', named]
  ]);
  add('fish', 'fish', 'fish', 'highMercury', [
    ['marlin', 'Marlin', 'Le marlin est explicitement écarté pendant la grossesse dans les recommandations françaises sur le mercure, même lorsqu’il est servi entièrement cuit.', 'Choisir une autre espèce de poisson.', 'marlins', named],
    ['lamprey', 'Lamproie', 'La lamproie figure parmi les espèces à éviter pendant la grossesse. Une longue cuisson en sauce ne change pas la précaution liée au mercure.', 'Remplacer par une espèce conseillée.', 'lamproies', named]
  ]);
  add('pantry', 'beans', 'legume', 'grains', [
    ['white-beans', 'Haricots blancs', 'Les haricots blancs cuits permettent de varier les légumes secs. Les graines sèches demandent la préparation indiquée sur le paquet ; une conserve est déjà traitée.', 'Cuire les graines sèches selon le paquet ou utiliser une conserve intacte.', 'haricot blanc coco mogette'],
    ['kidney-beans', 'Haricots rouges', 'Les haricots rouges destinés à la cuisson ne se mangent pas crus. Le guide concerne des graines correctement préparées selon l’emballage ou une conserve prête à consommer.', 'Respecter entièrement la préparation du paquet ; ne pas improviser une cuisson insuffisante.', 'haricot rouge kidney beans'],
    ['black-beans', 'Haricots noirs', 'Les haricots noirs cuits peuvent remplacer d’autres légumes secs dans un plat. Une farce de tacos doit aussi être gardée et réchauffée correctement.', 'Cuire selon les instructions et réfrigérer les restes rapidement.', 'haricot noir'],
    ['flageolet', 'Flageolets', 'Les flageolets cuits peuvent accompagner les repas. Leur statut ne dispense pas de vérifier la viande ou la charcuterie servie avec eux.', 'Préparer selon le paquet et vérifier les autres ingrédients.', 'flageolet'],
    ['split-peas', 'Pois cassés', 'Les pois cassés sont consommés cuits en soupe ou en purée. La quantité préparée doit pouvoir être refroidie rapidement si elle n’est pas mangée immédiatement.', 'Cuire jusqu’à la texture prévue puis répartir les restes en petits contenants.', 'pois casse'],
    ['broad-beans', 'Fèves', 'Les fèves cuites peuvent varier les légumes secs. Ce repère général ne remplace pas une exclusion personnelle déjà prescrite, notamment en cas de déficit en G6PD.', 'Écosser puis cuire ; respecter toute restriction médicale personnelle.', 'feve feves'],
    ['mung-beans', 'Haricots mungo cuits', 'Le haricot mungo en graine bien cuite est distinct des pousses crues souvent appelées « pousses de soja ». Les deux préparations ne partagent pas le même repère.', 'Cuire les graines selon le paquet ; ne pas remplacer par des pousses crues.', 'mungo haricot mungo']
  ]);
  add('pantry', 'bread', 'starch', 'grains', [
    ['bulgur', 'Boulgour', 'Le boulgour peut varier les féculents. Pour un taboulé, il faut aussi maîtriser le lavage des herbes et la conservation au froid.', 'Préparer selon le paquet et laver soigneusement les herbes.', 'boulghour bulgur'],
    ['couscous', 'Semoule de couscous', 'La semoule peut accompagner légumes et protéines adaptées. La préparation varie selon qu’elle est précuite ou non : suivre les indications du produit.', 'Hydrater ou cuire selon l’emballage et servir sans attente prolongée.', 'couscous semoule'],
    ['polenta', 'Polenta', 'La semoule de maïs se consomme cuite. Du fromage ou du lait ajouté doit être choisi selon ses propres précautions.', 'Cuire selon le paquet avec de l’eau ou un laitage adapté.', 'semoule mais polenta'],
    ['buckwheat', 'Sarrasin', 'Le sarrasin peut être préparé en grains cuits ou en galettes entièrement cuites. La pâte crue d’une galette n’a pas reçu le même traitement.', 'Cuire les grains ou la pâte selon la recette.', 'kasha blé noir'],
    ['millet', 'Millet', 'Le millet en grains cuits permet de diversifier les accompagnements. Une salade froide reste à conserver rapidement au réfrigérateur.', 'Cuire selon le paquet puis servir ou réfrigérer rapidement.'],
    ['barley', 'Orge', 'L’orge cuite peut entrer dans une soupe ou un accompagnement. Un plat préparé en grande quantité doit être refroidi rapidement pour sa conservation.', 'Cuire selon l’emballage et répartir les restes.', 'orge perlé mondé'],
    ['spelt', 'Épeautre', 'L’épeautre en grains est un féculent à préparer selon le paquet. Le pain d’épeautre déjà cuit peut se manger sans nouvelle cuisson.', 'Cuire les grains ; vérifier la forme du produit.', 'epeautre petit epeautre'],
    ['sorghum', 'Sorgho', 'Les grains de sorgho cuits peuvent varier les céréales. Le repère ne s’étend pas à une farine crue dégustée avant cuisson.', 'Cuire les grains selon les instructions.', 'sorghum'],
    ['gnocchi', 'Gnocchis', 'Les gnocchis sont une préparation à cuire selon l’emballage. Les œufs éventuellement présents ne posent pas la même question une fois toute la pâte cuite.', 'Cuire complètement et choisir une sauce adaptée.', 'gnocchi gnocchis pomme terre'],
    ['rice-noodles', 'Nouilles de riz', 'Les nouilles de riz peuvent être préparées dans un plat chaud. La sauce et les ingrédients crus ajoutés au dernier moment se vérifient séparément.', 'Préparer selon le paquet et servir sans attente prolongée.', 'vermicelle riz'],
    ['udon', 'Nouilles udon', 'Les udon sont des nouilles à préparer selon leur conditionnement. Les versions fraîches demandent aussi de respecter le froid avant cuisson.', 'Suivre la cuisson et la conservation de l’emballage.', 'nouille udon'],
    ['soba', 'Nouilles soba', 'Les soba cuites peuvent varier les pâtes. Elles contiennent souvent un mélange de farines : l’étiquette reste nécessaire pour les allergies.', 'Cuire selon le paquet et vérifier les allergènes.', 'nouille soba'],
    ['tortilla', 'Tortillas & wraps', 'Une tortilla destinée à être consommée après préparation peut faire partie d’un repas. Sa garniture, souvent ajoutée froide, détermine des précautions supplémentaires.', 'Suivre le paquet et garnir avec des aliments correctement préparés.', 'tortilla wrap galette mais'],
    ['pita', 'Pain pita', 'Le pain pita est déjà cuit et n’exige pas de nouvelle cuisson du fait de la grossesse. Une garniture au poulet ou une sauce au yaourt doit être adaptée.', 'Vérifier la conservation et la préparation de la garniture.', 'pita pains pita'],
    ['flour', 'Farine destinée à la cuisson', 'La farine est un ingrédient cru qui peut contenir des bactéries. Elle devient utilisable dans une préparation entièrement cuite ; goûter la pâte avant cuisson garde le risque de la farine crue.', 'Cuire complètement la pâte et ne pas la goûter crue.', 'farines pâte crue', { sources: ['flour'], basis: 'specific' }],
    ['chestnut', 'Châtaigne & marron comestible', 'La châtaigne alimentaire cuite peut varier les féculents. Cette fiche ne couvre pas les marrons d’Inde ni une graine ramassée dont l’identification est incertaine.', 'Utiliser des châtaignes alimentaires identifiées et bien cuites.', 'chataigne marrons comestibles']
  ]);
  add('pantry', 'nuts', 'nuts', 'nuts', [
    ['hazelnut', 'Noisette', 'La noisette n’a pas à être exclue systématiquement pendant la grossesse. L’allergie personnelle et la conservation du produit restent les points à vérifier.', 'Choisir des noisettes nature saines.', 'noisettes'],
    ['cashew', 'Noix de cajou', 'La noix de cajou vendue pour l’alimentation peut être consommée si vous n’y êtes pas allergique. Les versions très salées ou caramélisées se modèrent selon leur composition.', 'Choisir de préférence une version nature.', 'cajou cajous'],
    ['pistachio', 'Pistache', 'La pistache relève du repère général des fruits à coque. Une crème de pistache très sucrée ou un dessert à l’œuf cru demande une lecture distincte de sa recette.', 'Choisir des pistaches saines et respecter vos allergies.', 'pistaches'],
    ['pecan', 'Noix de pécan', 'La noix de pécan peut varier les fruits à coque. Le statut de la noix nature ne s’étend pas automatiquement à une tarte ou à un mélange très sucré.', 'Vérifier les allergies et choisir une noix bien conservée.', 'pecan pacane'],
    ['macadamia', 'Noix de macadamia', 'La noix de macadamia est traitée ici comme un fruit à coque alimentaire. Il n’y a pas de suppression systématique de cette famille pendant la grossesse.', 'Choisir un emballage intact et suivre la conservation.', 'macadamia'],
    ['peanut', 'Cacahuète & arachide', 'Le NHS précise qu’il n’est pas nécessaire d’éviter les arachides pendant la grossesse si vous n’y êtes pas allergique et n’avez pas reçu de consigne contraire.', 'Respecter votre allergie éventuelle et modérer le sel ajouté.', 'cacahuetes arachides', named],
    ['peanut-butter', 'Purée de cacahuète', 'Une purée de cacahuète peut être consommée en respectant les allergies. Une version à base de cacahuètes seules se distingue d’une pâte avec beaucoup de sucre ajouté.', 'Lire la composition et utiliser une cuillère propre.', 'beurre cacahuete peanut butter'],
    ['almond-butter', 'Purée d’amande', 'La purée d’amande garde la précaution d’allergie de l’amande. Le broyage ne transforme pas ce produit en boisson ni en complément alimentaire.', 'Choisir un pot sain et respecter la conservation.', 'purée amandes beurre amande']
  ]);
  add('pantry', 'bowl', 'pantry', 'grains', [
    ['hummus', 'Houmous de pois chiches cuits', 'Un houmous peut être préparé avec des pois chiches bien cuits et des ingrédients adaptés. Une préparation froide mixée doit rester au réfrigérateur, avec du matériel propre.', 'Utiliser des pois chiches cuits et suivre la conservation du produit.', 'hummus hoummous'],
    ['seitan', 'Seitan', 'Le seitan nature est une préparation de gluten de blé, distincte du tofu. Il se prépare selon l’emballage ; une sauce au soja ou un autre ingrédient peut demander une précaution séparée.', 'Vérifier la composition, la cuisson et l’allergie au blé.', 'gluten blé seitan'],
    ['red-lentil-pasta', 'Pâtes de lentilles', 'Les pâtes de lentilles bien cuites permettent de varier les féculents et légumes secs. La farine utilisée ne se consomme pas crue avant préparation.', 'Cuire selon l’emballage et vérifier la sauce.', 'pates lentilles corail'],
    ['chickpea-pasta', 'Pâtes de pois chiches', 'Les pâtes de pois chiches se consomment après la préparation indiquée. Leur base végétale ne dispense pas d’une bonne conservation du plat cuisiné.', 'Cuire selon le paquet puis servir ou réfrigérer rapidement.', 'pates pois chiche']
  ]);
  add('pantry', 'sweet', 'sweet', 'sweet', [
    ['honey', 'Miel', 'Le miel est un produit sucré : Poum lui applique le repère de modération des sucres pendant la grossesse. Cette fiche sur l’alimentation de la personne enceinte ne constitue pas un conseil pour nourrir un bébé.', 'Utiliser une petite quantité selon la recette.', 'miels'],
    ['jam', 'Confiture', 'La confiture est limitée pour sa richesse en sucre, pas parce qu’elle serait interdite pendant la grossesse. Une cuillère déjà utilisée peut contaminer le pot.', 'Utiliser un ustensile propre et respecter la conservation.', 'confitures gelée'],
    ['maple-syrup', 'Sirop d’érable', 'Le sirop d’érable reste un produit sucré même s’il est d’origine végétale. Il peut servir occasionnellement pour parfumer une portion.', 'Modérer la quantité et suivre les consignes après ouverture.', 'sirop erable'],
    ['agave-syrup', 'Sirop d’agave', 'Le sirop d’agave apporte du sucre ; le mot « naturel » ne supprime pas ce point nutritionnel. Le repère relève de la modération des produits sucrés.', 'Utiliser selon l’appétit et les éventuelles consignes personnalisées.', 'sirop agave'],
    ['ice-cream', 'Glace industrielle pasteurisée', 'Une glace fabriquée avec des ingrédients pasteurisés n’est pas la même préparation qu’une glace maison à l’œuf cru. La chaîne du froid doit être maintenue et la portion reste celle d’un dessert.', 'Vérifier les ingrédients et éviter toute glace ayant décongelé puis recongelé.', 'glaces crème glacée', { sources: ['nhs', 'spf'] }],
    ['sorbet', 'Sorbet', 'Le sorbet ne contient pas toujours de lait, mais reste généralement sucré. Vérifier la recette, notamment l’alcool possible dans certains sorbets et desserts glacés.', 'Lire les ingrédients et respecter la conservation au congélateur.', 'sorbets', { sources: ['spf'] }],
    ['cookies', 'Biscuits cuits', 'Des biscuits entièrement cuits ne sont pas des préparations à l’œuf cru même si l’œuf figure dans les ingrédients. Leur classement limité tient surtout à leur composition sucrée ou grasse.', 'Choisir des biscuits cuits, sans fourrage alcoolisé.', 'cookies biscuit', { sources: ['spf', 'flour'] }],
    ['cake', 'Gâteau entièrement cuit', 'Un gâteau dont la pâte est entièrement cuite peut être consommé en portion adaptée. Un cœur encore liquide à base d’œuf, une crème crue ou de l’alcool changeraient la réponse.', 'Vérifier aussi le fourrage et la cuisson du centre.', 'gateaux cake brownie', { sources: ['spf', 'flour'] }],
    ['dates', 'Dattes séchées', 'Les dattes séchées concentrent les sucres du fruit dans un petit volume. Elles ne sont pas classées interdites ; leur quantité se choisit dans l’ensemble de l’alimentation.', 'Vérifier l’état du fruit, retirer le noyau et suivre l’emballage.', 'datte dattes'],
    ['raisins', 'Raisins secs', 'Les raisins secs sont une forme concentrée du fruit. Une petite poignée représente davantage de sucre que le même poids de raisin frais ; le classement vise la portion.', 'Vérifier le conditionnement et modérer les ajouts dans les desserts.', 'raisin sec'],
    ['dried-apricots', 'Abricots secs', 'Les abricots secs peuvent varier les fruits séchés, avec une attention à la portion et aux ingrédients ajoutés. Vérifier aussi les sulfites en cas de sensibilité connue.', 'Suivre les indications de lavage et de conservation du paquet.', 'abricot sec'],
    ['prunes', 'Pruneaux', 'Les pruneaux sont des fruits séchés, à intégrer en tenant compte de leur portion. Un dessert de pruneaux au vin ajoute en revanche de l’alcool.', 'Choisir une version sans alcool et suivre la conservation.', 'pruneau', { sources: ['spf'] }]
  ]);
  add('pantry', 'sweet', 'sweet', 'liquorice', [
    ['liquorice', 'Réglisse', 'La réglisse est explicitement contre-indiquée pendant la grossesse selon l’Assurance Maladie, y compris dans les confiseries et les mélanges de tisanes. Le problème ne se limite pas au sucre.', 'Choisir des bonbons et infusions sans réglisse.', 'reglisse licorice liquorice', named]
  ]);
  add('drinks', 'drink', 'drinks', 'caffeine', [
    ['decaf', 'Café décaféiné', 'Le décaféiné contient généralement beaucoup moins de caféine qu’un café classique, sans nécessairement en être totalement dépourvu. Il peut aider à réduire le total quotidien.', 'Vérifier la teneur si disponible et additionner les autres sources.', 'deca décaféiné decaf'],
    ['mate', 'Maté', 'Le maté est une boisson pouvant apporter de la caféine. Le fait de l’appeler infusion ne le rend pas équivalent à une boisson sans stimulant.', 'Compter sa caféine et vérifier la quantité préparée.', 'yerba mate'],
    ['hot-chocolate', 'Chocolat chaud', 'Le chocolat chaud apporte la caféine du cacao, ainsi que du sucre selon la recette. Le lait doit être pasteurisé ou UHT et correctement conservé.', 'Compter la caféine et choisir un lait adapté.', 'cacao chocolat chaud', { sources: ['nutrition', 'spf'] }]
  ]);
  add('drinks', 'drink', 'drinks', 'juice', [
    ['orange-juice', 'Jus d’orange pasteurisé', 'Le jus d’orange pasteurisé peut être consommé occasionnellement. « Pur jus » ou « sans sucre ajouté » ne signifie pas qu’il ne contient pas les sucres du fruit.', 'Vérifier la pasteurisation et la durée après ouverture.', 'jus orange'],
    ['apple-juice', 'Jus de pomme pasteurisé', 'Un jus de pomme pasteurisé est différent d’un jus frais non traité. Il reste une boisson sucrée, à alterner principalement avec de l’eau.', 'Lire le traitement et garder au froid après ouverture si indiqué.', 'jus pomme'],
    ['grape-juice', 'Jus de raisin pasteurisé', 'Le jus de raisin pasteurisé sans alcool ne se confond pas avec le vin. Il reste une boisson riche en sucres à modérer.', 'Vérifier les ingrédients et le traitement.', 'jus raisin'],
    ['smoothie', 'Smoothie pasteurisé', 'Un smoothie vendu pasteurisé a reçu un traitement que n’a pas nécessairement une boisson fraîche mixée au comptoir. Il reste à consommer occasionnellement plutôt que comme boisson principale.', 'Lire les ingrédients, le traitement et la conservation.', 'smoothies']
  ]);
  add('drinks', 'drink', 'drinks', 'rawJuice', [
    ['raw-juice', 'Jus non pasteurisé', 'Un jus fraîchement pressé peut garder des microbes provenant des fruits ou de la préparation. Sa fraîcheur n’apporte pas la même information qu’un traitement validé contre les bactéries.', 'Choisir un jus pasteurisé lorsque la préparation n’est pas vérifiable.', 'jus cru frais presse', named]
  ]);
  add('drinks', 'water', 'drinks', 'water', [
    ['sparkling-water', 'Eau gazeuse', 'Une eau gazeuse potable sans autres ingrédients reste de l’eau. Si la boisson est aromatisée, lire sa composition plutôt que déduire l’absence de sucre ou de caféine.', 'Choisir une eau potable et vérifier les ajouts.', 'eau petillante gazeuse'],
    ['tap-water', 'Eau du robinet potable', 'L’eau du robinet peut être bue lorsqu’elle est déclarée potable localement. Une restriction ponctuelle de consommation prime sur ce repère général.', 'Suivre les éventuelles consignes de votre réseau d’eau.', 'eau robinet']
  ]);
  add('drinks', 'drink', 'drinks', 'herbs', [
    ['rooibos', 'Rooibos en infusion', 'Une boisson au rooibos peut contenir d’autres plantes dans le mélange. Poum ne dispose pas ici d’un repère de dose propre à cette infusion pendant la grossesse et conserve donc « À vérifier ».', 'Faire vérifier la composition et la quantité consommée.'],
    ['chamomile', 'Camomille en infusion', 'Le nom camomille ne décrit pas à lui seul l’espèce, la dose ni les autres plantes du sachet. Le guide ne transforme pas l’absence de données précises en interdiction, ni en feu vert.', 'Montrer la composition du mélange au pharmacien.', 'camomille tisane'],
    ['verbena', 'Verveine en infusion', 'Une infusion de verveine demande de connaître la plante exacte et l’usage envisagé. Un mélange ou un extrait concentré ne se juge pas sur son seul nom commercial.', 'Faire vérifier la plante, le mélange et la fréquence.', 'verveine tisane'],
    ['mint-tea', 'Infusion de menthe', 'L’infusion de menthe est distincte de quelques feuilles dans une recette et d’une huile essentielle. Le guide garde un repère à vérifier faute de dose individualisée.', 'Vérifier le mélange et l’usage auprès d’un pharmacien.', 'tisane menthe'],
    ['kombucha', 'Kombucha', 'Le kombucha est une boisson fermentée dont la composition et le traitement varient. Il peut rester de l’alcool et de la caféine ; le seul nom ne permet pas de confirmer ces teneurs ni la pasteurisation.', 'Vérifier alcool, caféine et traitement sur l’étiquette.', '', { sources: ['spf', 'efsa'] }]
  ]);
  add('pantry', 'bowl', 'pantry', 'pantry', [
    ['olive-oil', 'Huile d’olive', 'L’huile d’olive peut assaisonner ou cuisiner un plat pendant la grossesse. C’est une matière grasse à doser dans l’ensemble des repas, pas un aliment à exclure systématiquement.', 'Utiliser selon la recette et conserver à l’abri de la lumière.', 'huile olive'],
    ['rapeseed-oil', 'Huile de colza', 'L’huile de colza peut varier les matières grasses des repas. Le mode d’utilisation dépend de l’huile choisie et de ses indications, notamment pour la cuisson.', 'Suivre les usages et la conservation de l’étiquette.', 'huile colza'],
    ['sunflower-oil', 'Huile de tournesol', 'L’huile de tournesol est un ingrédient alimentaire possible. La dose utilisée compte comme pour les autres matières grasses, même si la bouteille est d’origine végétale.', 'Respecter l’usage culinaire prévu sur la bouteille.', 'huile tournesol'],
    ['olives', 'Olives en bocal', 'Les olives vendues en bocal peuvent être consommées selon leur conditionnement. La saumure n’autorise pas à dépasser le délai après ouverture ; le sel reste à modérer.', 'Vérifier l’intégrité du bocal et prélever proprement.', 'olive olives vertes noires'],
    ['gherkins', 'Cornichons en bocal', 'Les cornichons conditionnés pour être consommés tels quels peuvent accompagner un plat. Les conserver selon l’étiquette après ouverture et tenir compte du sel ajouté.', 'Prélever avec un ustensile propre.', 'cornichon pickles'],
    ['mustard', 'Moutarde', 'La moutarde utilisée en condiment peut faire partie d’une recette. Il faut distinguer la moutarde seule d’une sauce mayonnaise à l’œuf cru et respecter une allergie éventuelle.', 'Lire les ingrédients de la sauce complète.', 'moutardes'],
    ['wine-vinegar', 'Vinaigre de vin', 'Le vinaigre de vin est un condiment transformé, distinct du vin ajouté dans une sauce. Le nom « vin » dans ce condiment ne justifie pas de l’assimiler automatiquement à une boisson alcoolisée.', 'Utiliser comme condiment ; vérifier les autres ingrédients d’une sauce.', 'vinaigre vin cidre balsamique'],
    ['tomato-paste', 'Concentré de tomate', 'Le concentré de tomate conditionné peut servir à cuisiner. Une fois ouvert, il doit être conservé selon l’emballage : son goût acide ne garantit pas une conservation indéfinie.', 'Respecter le délai après ouverture.', 'concentre tomate'],
    ['canned-tomato', 'Tomates en conserve', 'Les tomates en conserve intacte ont subi un traitement. Elles peuvent être cuisinées dans une sauce ; après ouverture, les consignes de conservation s’appliquent.', 'Choisir une boîte intacte et conserver les restes comme indiqué.', 'tomate concassee pulpe tomate'],
    ['applesauce', 'Compote de fruits', 'Une compote cuite et correctement conservée peut varier les desserts. Choisir sans sucre ajouté permet de distinguer le fruit préparé d’une recette davantage sucrée.', 'Vérifier le sucre ajouté et le délai après ouverture.', 'compotes pomme poire'],
    ['frozen-vegetables', 'Légumes surgelés à cuire', 'Les légumes surgelés destinés à être cuits peuvent faciliter les repas. La congélation ne remplace pas la cuisson indiquée sur le sachet.', 'Suivre la cuisson du paquet ; ne pas supposer le produit prêt à manger.', 'legumes surgeles'],
    ['canned-vegetables', 'Légumes en conserve', 'Les légumes en conserve intacte peuvent compléter les légumes frais. Le conditionnement traite le produit avant ouverture ; ensuite, le délai de conservation doit être respecté.', 'Lire les indications après ouverture et vérifier la boîte.', 'legumes conserve bocaux'],
    ['soy-sauce', 'Sauce soja', 'Santé publique France distingue la sauce soja utilisée occasionnellement des aliments comme le tofu : elle apporte moins de phytoestrogènes dans cet usage. Elle reste un condiment salé à doser.', 'Utiliser occasionnellement en assaisonnement.', 'sauce soja shoyu tamari', { basis: 'specific', sources: ['spf'] }],
    ['almond-drink', 'Boisson à l’amande', 'La boisson à l’amande n’est pas une boisson au soja. Le sucre ajouté et les apports en calcium ou protéines varient ; elle ne remplace pas automatiquement un laitage sur le plan nutritionnel.', 'Vérifier le traitement, la composition et le délai après ouverture.', 'lait amande boisson amande']
  ]);
  // Keep drinks in the drinks filter, even when their general profile is shared with pantry foods.
  foods.find(f => f.id === 'almond-drink').category = 'drinks';
  add('pantry', 'beans', 'legume', 'soy', [
    ['edamame', 'Edamame', 'L’edamame est la fève de soja consommée jeune. La faire cuire ne permet pas d’écarter la précaution française sur les isoflavones des aliments au soja.', 'Varier avec des pois ou d’autres légumes secs adaptés.', 'edamames feves soja'],
    ['soy-yogurt', 'Dessert & yaourt au soja', 'Un dessert au soja reste un aliment à base de soja, même fermenté ou enrichi en calcium. Le guide lui applique la précaution française pendant la grossesse.', 'Choisir une autre option compatible avec vos besoins alimentaires.', 'yaourt soja dessert soja', named]
  ]);
  const illustrations = {
    pineapple: ['pineapple'], sweetpotato: ['sweet-potato'], pear: ['pear', 'quince'],
    peach: ['peach', 'nectarine', 'apricot', 'mango', 'persimmon'],
    citrus: ['orange', 'mandarin', 'clementine', 'lemon', 'lime', 'grapefruit'],
    grapes: ['grape', 'plum', 'fig', 'blackcurrant', 'blueberry', 'blackberry'],
    cherry: ['cherry', 'cranberry', 'redcurrant'], berries: ['raspberry'],
    kiwi: ['kiwi', 'passion-fruit'], melon: ['watermelon', 'papaya'],
    eggplant: ['eggplant'], pepper: ['bell-pepper'],
    onion: ['onion', 'shallot', 'garlic', 'fennel'], pumpkin: ['pumpkin', 'butternut', 'red-kuri', 'spaghetti-squash', 'pattypan'],
    leafy: ['rocket', 'lambs-lettuce', 'endive', 'chard', 'sorrel', 'watercress', 'kale', 'red-cabbage', 'white-cabbage', 'green-cabbage', 'chinese-cabbage'],
    zucchini: ['cucumber', 'okra', 'chayote'], radish: ['radish', 'beetroot', 'turnip'],
    carrot: ['parsnip', 'salsify'], potato: ['rutabaga', 'celeriac', 'jerusalem-artichoke', 'yam'],
    leek: ['leek', 'celery', 'rhubarb'], asparagus: ['asparagus'], banana: ['plantain'],
    beans: ['peas', 'green-beans', 'snow-peas']
  };
  for (const [art, ids] of Object.entries(illustrations)) {
    for (const food of foods) if (ids.includes(food.id)) food.art = art;
  }
  for (const food of foods) if (food.family === 'herb') food.art = 'leafy';
  const data = { annotations, foods, detail };
  if (typeof module !== 'undefined' && module.exports) module.exports = data;
  root.MietteCatalogue = data;
})(typeof window !== 'undefined' ? window : globalThis);
