(function (root) {
  'use strict';
  // Shared explanations. Food-specific context lives in catalogue.js; OFF only detects signals.
  const sources = {
    culinaryHerbs: { name: 'MotherToBaby · OTIS', title: 'Plantes : distinguer usage culinaire et produits à base de plantes', url: 'https://mothertobaby.org/fact-sheets/herbal-products-pregnancy/' },
    reflux: { name: 'NHS · Royaume-Uni', title: 'Grossesse : aliments épicés et reflux', url: 'https://www.nhs.uk/pregnancy/common-symptoms/indigestion-and-heartburn/' },
    cinnamon: { name: 'NIH · NCCIH', title: 'Cannelle : usages alimentaires, grossesse et précautions', url: 'https://www.nccih.nih.gov/health/cinnamon' },
    coumarin: { name: 'Anses', title: 'Cannelle et coumarine : risques liés à une surconsommation (PDF)', url: 'https://vigilanses.anses.fr/sites/default/files/VigilAnsesN15_Novembre2021_Coumarine.pdf' },
    turmeric: { name: 'NIH · NCCIH', title: 'Curcuma et curcumine : compléments et grossesse', url: 'https://www.nccih.nih.gov/health/turmeric' },
    fenugreek: { name: 'NIH · NCCIH', title: 'Fenugrec : quantité alimentaire et précautions pendant la grossesse', url: 'https://www.nccih.nih.gov/health/fenugreek' },
    sage: { name: 'NIH · NCCIH', title: 'Sauge : thuyone et précautions pendant la grossesse', url: 'https://www.nccih.nih.gov/health/sage' },
    produce: { name: 'FDA · États-Unis', title: 'Fruits, légumes et jus pendant la grossesse', url: 'https://www.fda.gov/food/people-risk-foodborne-illness/fruits-veggies-and-juices-food-safety-moms-be' },
    canned: { name: 'CDC · États-Unis', title: 'Choix alimentaires pendant la grossesse : poissons et fruits de mer en conserve', url: 'https://www.cdc.gov/food-safety/foods/pregnant-women.html' },
    interactions: { name: 'Assurance Maladie', title: 'Aliments, boissons et interactions avec les médicaments', url: 'https://www.ameli.fr/assure/sante/medicaments/effets-indesirables-et-interactions-lies-aux-medicaments/interactions-aliments-boissons-tabac-avec-medicaments' },
    starfruit: { name: 'National Kidney Foundation · États-Unis', title: 'Carambole : précaution en cas de maladie rénale', url: 'https://www.kidney.org/kidney-topics/why-you-should-avoid-eating-starfruit?page=1' },
    nhs: { name: 'NHS · Royaume-Uni', title: 'Aliments pendant la grossesse : fromages, fruits à coque et autres cas', url: 'https://www.nhs.uk/pregnancy/keeping-well/foods-to-avoid/' },
    poultry: { name: 'CDC · États-Unis', title: 'Poulet : bactéries, cuisson et contamination en cuisine', url: 'https://www.cdc.gov/food-safety/foods/chicken.html' },
    rice: { name: 'Food Standards Agency · Royaume-Uni', title: 'Riz cuit : refroidissement, conservation et réchauffage (PDF)', url: 'https://www.food.gov.uk/sites/default/files/media/document/sfbb-indian-05-cooking-06-rice_0.pdf' },
    flour: { name: 'FDA · États-Unis', title: 'Farine crue et pâtes non cuites : précautions (PDF)', url: 'https://www.fda.gov/media/157257/download' },
    soy: { name: 'Anses', title: 'Évaluation du risque lié aux isoflavones de soja, janvier 2025 (PDF)', url: 'https://www.anses.fr/sites/default/files/NUT2022SA0221.pdf' },
    mercury: { name: 'Anses', title: 'Étude de l’alimentation totale 3 : métaux, dont le méthylmercure, octobre 2025 (PDF)', url: 'https://www.anses.fr/system/files/ERCA2019-SA-0010-RA-2.pdf' },
    plants: { name: 'Assurance Maladie', title: 'Grossesse : médicaments, plantes, compléments et huiles essentielles', url: 'https://www.ameli.fr/assure/sante/devenir-parent/grossesse/grossesse-en-bonne-sante/medicament-grossesse' },
    caffeineAmounts: { name: 'EFSA', title: 'La caféine : repères et teneurs indicatives par portion (PDF)', url: 'https://www.efsa.europa.eu/sites/default/files/corporate_publications/files/efsaexplainscaffeine150527fr.pdf' },
    potato: { name: 'Anses', title: 'Glycoalcaloïdes de la pomme de terre : évaluation toxicologique (PDF)', url: 'https://www.anses.fr/system/files/ERCA2014sa0115.pdf' }
  };
  const profile = (status, title, mechanism, condition, steps, refs) => ({ status, title, mechanism, condition, steps, sources: refs });
  const profiles = {
    spice: profile('compatible', 'Assaisonner un plat est un usage alimentaire',
      'Poum applique ici le repère sur les plantes utilisées modérément en cuisine. Une épice répartie dans un plat est distincte d’un extrait concentré, d’une huile essentielle ou d’un complément.',
      'Ce repère concerne la petite quantité nécessaire pour assaisonner une recette, avec une épice alimentaire bien identifiée. Il ne fournit pas de dose pour une cure ou un usage médicinal.',
      ['Utiliser la quantité culinaire de la recette et respecter ses allergies ; garder le pot au sec et le refermer.', 'Ne pas extrapoler ce conseil aux gélules, huiles essentielles, extraits ou grandes quantités prises seules.'], ['culinaryHerbs', 'plants']),
    spicy: profile('compatible', 'Adapter le piquant à son confort digestif',
      'L’assaisonnement piquant peut aggraver les brûlures d’estomac de certaines personnes enceintes. Le NHS conseille alors de réduire les aliments épicés ; cela concerne les symptômes digestifs.',
      'Une quantité culinaire peut convenir si elle est bien tolérée. Diminuer le piquant s’il provoque du reflux ; l’épice ne dispense pas de vérifier la cuisson et les ingrédients du plat.',
      ['Commencer par peu et adapter selon son confort ; choisir une version douce si nécessaire.', 'Utiliser un produit alimentaire identifié, dans un plat correctement préparé.'], ['reflux', 'culinaryHerbs']),
    spiceBlend: profile('precaution', 'Le nom d’un mélange ne donne pas toute sa recette',
      'La composition d’un mélange d’épices peut varier selon la marque et la recette. Poum demande de lire les ingrédients avant d’appliquer les repères culinaires : sel, allergènes et plantes particulières peuvent changer le conseil.',
      'Un mélange alimentaire connu, utilisé pour assaisonner, se juge à partir de ses ingrédients. Une préparation dont les plantes ne sont pas identifiées reste à vérifier.',
      ['Lire la composition complète, notamment moutarde, sésame, céleri et éventuelle réglisse.', 'Utiliser la quantité prévue pour le plat et modérer le piquant en cas de reflux.'], ['culinaryHerbs', 'ameli', 'nutrition', 'reflux']),
    cassia: profile('limit', 'Coumarine : surtout la répétition et la quantité',
      'La cannelle de Chine et certaines autres cannelles peuvent apporter davantage de coumarine que celle de Ceylan. Un excès peut affecter le foie ; ce risque n’est pas propre à la grossesse.',
      'Une utilisation culinaire ponctuelle n’équivaut pas à une consommation importante répétée. Sans teneur connue en coumarine, cette fiche ne peut pas fournir un seuil en cuillères applicable à tous les pots.',
      ['Employer avec parcimonie pour parfumer un plat ; vérifier l’espèce si elle est indiquée.', 'Éviter les cures et compléments de cannelle sans avis médical, particulièrement en cas de maladie du foie.'], ['coumarin', 'cinnamon']),
    fenugreek: profile('precaution', 'La quantité alimentaire est une distinction essentielle',
      'Le NCCIH distingue le fenugrec utilisé comme épice des quantités supérieures à l’usage alimentaire, qu’il considère non sûres pendant la grossesse. Une gélule ne se juge pas comme un assaisonnement.',
      'Le repère ne couvre que le fenugrec présent en quantité culinaire dans un plat. Ne pas entreprendre de cure ni chercher à modifier la glycémie ou préparer l’allaitement avec ce produit.',
      ['Rester à l’usage alimentaire de la recette et respecter ses allergies.', 'Éviter les compléments et quantités supérieures à l’usage alimentaire pendant la grossesse ; demander conseil pour un produit concentré.'], ['fenugreek', 'plants']),
    pantry: profile('compatible', 'La composition et la conservation restent à lire',
      'Les recommandations alimentaires de grossesse permettent de varier les ingrédients usuels. Pour ce produit préparé, le repère suppose des ingrédients adaptés, un conditionnement intact et le respect des instructions du fabricant.',
      'Un condiment, une huile ou un produit préparé n’a pas besoin d’une exclusion systématique. La quantité de sel, de sucre et de matières grasses reste à considérer dans l’ensemble des repas.',
      ['Lire les ingrédients, le traitement si pertinent et la conservation après ouverture.', 'Prélever avec un ustensile propre et respecter ses propres allergies.'], ['nutrition', 'spf']),
    sprouts: profile('avoid', 'La germination favorise la multiplication des bactéries',
      'Des bactéries peuvent être présentes dans les graines puis se multiplier avec la chaleur et l’humidité de germination. Elles ne restent pas forcément à la surface : le rinçage ne suffit pas, même pour des graines germées à la maison.',
      'La précaution porte sur les pousses crues ou à peine chauffées. Une cuisson complète réduit le risque ; une poignée ajoutée crue en fin de recette reste concernée.',
      ['Éviter les graines germées crues dans les salades, sandwichs et garnitures.', 'Si vous en cuisinez, les cuire entièrement et les servir chaudes.'], ['produce', 'spf']),
    produce: profile('compatible', 'Le point à maîtriser : la contamination en surface',
      'La terre ou l’eau peuvent déposer des microbes et le parasite Toxoplasma gondii sur les végétaux. Une première toxoplasmose pendant la grossesse peut atteindre le fœtus. Le fruit ou le légume lui-même n’est pas la cause de ce risque.',
      'Un végétal destiné à être mangé cru peut faire partie des repas si son lavage est soigneux. L’immunité à la toxoplasmose ne dispense pas de l’hygiène contre les autres microbes.',
      ['Rincer à l’eau potable courante, même avant d’éplucher ou de couper. Éliminer toute terre ; ne pas utiliser de savon ou de désinfectant ménager.', 'Préparer avec des mains et ustensiles propres. Si le lavage n’est pas maîtrisé, choisir une version cuite.'], ['toxo', 'produce', 'nutrition']),
    cookedProduce: profile('compatible', 'Lavage et préparation du légume',
      'Un légume peut porter des contaminants provenant du sol. Laver puis cuire réduit le risque infectieux ; cela permet de conserver une place aux légumes dans une alimentation variée pendant la grossesse.',
      'Le repère concerne le légume préparé pour être mangé. Le lavage reste utile avant cuisson pour ne pas contaminer les mains et le plan de travail.',
      ['Retirer la terre, laver à l’eau potable et préparer avec des ustensiles propres.', 'Cuire selon la recette. Réfrigérer rapidement les restes, au plus tard dans les deux heures, et les garder au maximum trois jours à 4 °C ou moins.'], ['toxo', 'nutrition', 'spf']),
    dairy: profile('precaution', 'Pasteurisation et chaîne du froid',
      'Le traitement thermique réduit les microbes du lait, notamment Listeria. Cette bactérie peut cependant contaminer un produit ensuite et se multiplier au réfrigérateur. Une infection parfois discrète chez la mère peut avoir des conséquences graves pour la grossesse.',
      'Pour les laitages et fromages frais concernés ici, choisir une fabrication à partir de lait pasteurisé ou UHT. Cette condition ne rend pas tous les fromages affinés consommables froids.',
      ['Vérifier la mention « pasteurisé » ou « UHT » et la nature exacte du produit.', 'Respecter la date limite, le froid et le délai après ouverture figurant sur l’emballage.'], ['spf', 'nhs']),
    hardCheese: profile('compatible', 'Une exception liée au procédé de fabrication',
      'Les pâtes pressées cuites sont distinguées des fromages mous dans les recommandations françaises : le chauffage du caillé et l’affinage long rendent le milieu moins favorable aux microbes. Certains restent possibles même fabriqués avec du lait cru.',
      'Ce repère vise un morceau de ce type de fromage. Il ne s’étend pas à tous les fromages durs en apparence, ni aux sachets de fromage déjà râpé.',
      ['Retirer la croûte et utiliser un couteau propre.', 'Préférer un morceau à râper soi-même ; conserver selon l’étiquette.'], ['spf', 'agriculture']),
    softCheese: profile('avoid', 'Listeria : le type de fromage compte aussi',
      'L’humidité et les caractéristiques de certains fromages affinés favorisent Listeria. Une contamination après pasteurisation reste possible ; retirer seulement la croûte ne suffit pas pour les fromages concernés.',
      '« À éviter » porte sur la consommation froide ou simplement tiédie. Une cuisson complète, jusqu’à ce que le plat soit fumant à cœur, change la situation ; un fromage juste fondu n’apporte pas cette assurance.',
      ['Pour une consommation froide, choisir plutôt une pâte pressée cuite sans croûte.', 'Dans un plat au four, chauffer complètement jusqu’au centre et servir aussitôt.'], ['spf', 'nhs']),
    rawMilk: profile('avoid', 'Absence de pasteurisation',
      'Le lait cru n’a pas reçu le traitement thermique destiné à réduire les microbes pathogènes. Il peut transmettre notamment Listeria, Salmonella ou certaines souches d’Escherichia coli, même si son odeur paraît normale.',
      'Le lait thermisé n’offre pas le même traitement qu’un lait pasteurisé. Le cas particulier des fromages à pâte pressée cuite se juge séparément.',
      ['Choisir du lait pasteurisé ou UHT pour boire et cuisiner.', 'Un produit fermier, bio ou très frais n’est pas nécessairement pasteurisé. Lire l’étiquette.'], ['agriculture', 'spf']),
    meat: profile('precaution', 'Toxoplasmose et bactéries de la viande crue',
      'La viande peut contenir des kystes de Toxoplasma et être contaminée par des bactéries. La toxoplasmose est particulièrement importante en cas de première infection pendant la grossesse ; les autres infections restent possibles même en cas d’immunité.',
      'Une cuisson complète à cœur est nécessaire. Une marinade, une viande saisie seulement en surface ou le contrôle de la couleur extérieure ne suffisent pas.',
      ['Cuire jusqu’au centre, sans portion crue ou saignante. Respecter les consignes de cuisson du produit.', 'Séparer viande crue et aliments prêts à manger ; laver mains, couteau et planche après manipulation.'], ['toxo', 'spf']),
    poultry: profile('precaution', 'Salmonella et Campylobacter',
      'La volaille crue peut porter Salmonella ou Campylobacter. Ces bactéries provoquent des infections digestives, avec notamment diarrhée et fièvre. La contamination peut aussi passer aux autres aliments par les mains ou les ustensiles.',
      'La température au centre est un contrôle plus fiable que le temps de recette ou la couleur. Le repère des autorités américaines utilisé ici est 74 °C à cœur pour la volaille.',
      ['Vérifier 74 °C dans la partie la plus épaisse avec un thermomètre propre, sans toucher l’os.', 'Ne pas rincer la volaille crue : les éclaboussures dispersent les microbes. Nettoyer les ustensiles après manipulation.'], ['poultry', 'temperature']),
    groundMeat: profile('precaution', 'Le hachage répartit les microbes au centre',
      'Le hachage peut répartir à l’intérieur de la viande des bactéries présentes en surface. Une croûte grillée autour d’un steak haché ne renseigne donc pas sur la sécurité du centre ; la précaution contre la toxoplasmose reste applicable.',
      'Cuire intégralement. Le repère FoodSafety.gov pour la viande hachée est 71 °C à cœur ; pour de la volaille hachée, retenir 74 °C.',
      ['Mesurer la température au centre du steak ; suivre aussi les instructions du fabricant.', 'Respecter strictement le froid et la date limite de la viande hachée.'], ['temperature', 'toxo']),
    rawMeat: profile('avoid', 'Séchage, salage et marinade ne sont pas une cuisson',
      'Une viande consommée crue ou séchée peut transmettre des parasites ou des bactéries. Le risque ne se résume pas à la toxoplasmose : être immunisée ne permet pas de considérer toutes les charcuteries crues comme compatibles.',
      'Choisir une préparation où la viande est entièrement cuite. La congélation domestique ne constitue pas une garantie contre l’ensemble des agents infectieux.',
      ['Remplacer la portion crue par une viande bien cuite.', 'Une recette chaude doit cuire tous les morceaux à cœur ; un ajout après cuisson reste une consommation sans cuisson.'], ['toxo', 'spf']),
    deli: profile('avoid', 'Listeria dans les aliments réfrigérés prêts à manger',
      'Une charcuterie déjà cuite peut être contaminée lors des manipulations puis conservée plusieurs jours au froid. Listeria peut s’y multiplier sans modifier l’odeur ou le goût. Une cuisson antérieure ne suffit donc pas à garantir le produit servi froid.',
      'Les recommandations françaises écartent les charcuteries réfrigérées prêtes à manger froides. Elles prévoient notamment le jambon blanc recuit à cœur dans un plat.',
      ['Éviter cette forme réfrigérée consommée froide.', 'Pour le jambon blanc, le recuire dans un gratin ou une pizza jusqu’à ce que l’ensemble soit bien chaud à cœur.'], ['spf', 'ameli']),
    eggs: profile('precaution', 'Salmonella : le jaune compte autant que le blanc',
      'Les œufs peuvent transmettre Salmonella. Un œuf très frais ou élevé en plein air n’est pas une garantie d’absence de cette bactérie. Une cuisson suffisante réduit le risque d’infection digestive.',
      'Le guide suit les précautions françaises : blanc et jaune cuits, sans partie liquide. Un œuf incorporé à un biscuit entièrement cuit n’équivaut pas à un œuf cru.',
      ['Préparer des œufs durs, brouillés bien pris ou une omelette cuite jusqu’au centre.', 'Éviter les recettes maison où l’œuf reste cru ou peu cuit.'], ['spf', 'agriculture', 'temperature']),
    rawEggs: profile('avoid', 'Un œuf cru reste cru après réfrigération',
      'Battre un œuf, ajouter du sucre ou du citron puis mettre la préparation au frais ne constitue pas une cuisson. Salmonella peut donc rester présente dans une mousse, une sauce ou un dessert à l’œuf cru.',
      'La recette exacte détermine le repère : une version sans œuf cru n’a pas cette même précaution. Un produit industriel exige de vérifier le traitement et la conservation.',
      ['Choisir une recette sans œuf cru ou une préparation dont le traitement est adapté et confirmé.', 'Vérifier séparément l’alcool, les produits laitiers et le délai de conservation.'], ['spf', 'agriculture']),
    fish: profile('precaution', 'Le poisson reste au menu, bien cuit',
      'Les recommandations de grossesse conservent une place au poisson, avec des espèces variées. Sa consommation crue, fumée ou insuffisamment cuite expose à des risques infectieux ; la cuisson traite ce risque, sans retirer les contaminants chimiques.',
      'Repère français : deux repas de poisson par semaine, dont un poisson gras, en variant espèces et provenances. Ce total comprend l’ensemble des poissons consommés.',
      ['Cuire complètement à cœur ; ne pas utiliser une marinade au citron comme remplacement.', 'Respecter la chaîne du froid. Varier les espèces plutôt que répéter toujours le même poisson.'], ['spf', 'mercury']),
    rawFish: profile('avoid', 'Listeria et parasites selon la préparation',
      'Le poisson cru peut porter des parasites ; les produits fumés ou marinés prêts à manger présentent aussi un risque de Listeria. Le froid de conservation et le fumage ne sont pas des garanties de destruction de cette bactérie.',
      'La congélation utilisée contre certains parasites ne détruit pas Listeria. Elle ne suffit donc pas à rendre un sushi cru ou un poisson fumé compatible pendant la grossesse.',
      ['Choisir du poisson entièrement cuit et servi chaud.', 'Vérifier aussi les ingrédients ajoutés après cuisson et l’hygiène de préparation.'], ['ameli', 'spf']),
    shellfish: profile('precaution', 'Provenance, cuisson et manipulations',
      'Coquillages et crustacés peuvent véhiculer des microbes. La provenance contrôlée et la cuisson complète sont complémentaires ; un produit cuit puis décortiqué et conservé au frais peut être contaminé ensuite.',
      'Cette fiche concerne un produit cru acheté pour être entièrement cuit à la maison. Les crustacés vendus cuits et décortiqués au rayon frais relèvent d’une autre précaution.',
      ['Acheter dans un circuit contrôlé et respecter les consignes de conservation et de cuisson.', 'Bien cuire et servir aussitôt ; manipuler le produit cuit avec des ustensiles propres.'], ['spf', 'agriculture']),
    rawShellfish: profile('avoid', 'Le coquillage est consommé sans étape de cuisson',
      'Un coquillage cru peut transmettre une infection alimentaire. Être vivant ou fraîchement ouvert ne démontre pas l’absence de microbes ; du citron ou du vinaigre ne remplace pas une cuisson.',
      'Les recommandations françaises écartent les coquillages crus pendant la grossesse. Une version de provenance contrôlée entièrement cuite se juge différemment.',
      ['Choisir un coquillage bien cuit, acheté dans un circuit contrôlé.', 'Une huître légèrement gratinée mais encore crue au centre ne répond pas à cette condition.'], ['spf', 'agriculture']),
    cannedFish: profile('compatible', 'Une conserve stérilisée est déjà cuite',
      'Les poissons en conserve stérilisée figurent parmi les choix possibles pour prévenir les infections alimentaires pendant la grossesse. Le traitement thermique distingue cette forme du poisson cru ou simplement mariné.',
      'Une conserve du commerce prête à consommer peut se manger froide selon son étiquette. Cela ne supprime pas le mercure : la sardine et le maquereau courant se distinguent du thon à limiter.',
      ['Choisir une boîte intacte, non bombée, et suivre les instructions du fabricant.', 'Après ouverture, réfrigérer et respecter le délai indiqué ; varier les poissons dans le repère de deux repas par semaine, dont un poisson gras.'], ['canned', 'spf']),
    mercury: profile('limit', 'Méthylmercure : un contaminant accumulé',
      'Le méthylmercure s’accumule dans la chaîne alimentaire, notamment chez certains poissons prédateurs. Le système nerveux en développement du fœtus est particulièrement sensible à l’exposition. Ce risque dépend des consommations répétées et de l’espèce.',
      'Cuire, congeler ou mettre en conserve ne supprime pas ce contaminant. Les recommandations françaises consultées demandent de limiter ces prédateurs ; elles ne donnent pas un nombre universel de boîtes de thon autorisées.',
      ['Espacer ces poissons et alterner avec sardine, saumon, truite ou cabillaud bien cuits.', 'Garder le repère global de deux repas de poisson par semaine, dont un poisson gras ; ce n’est pas un quota de deux repas de thon.'], ['mercury', 'spf']),
    highMercury: profile('avoid', 'Espèces explicitement écartées pour le mercure',
      'Ces grands prédateurs figurent parmi les espèces à éviter pendant la grossesse dans les recommandations françaises. Le méthylmercure peut affecter le développement du système nerveux ; une cuisson parfaite ne change pas cette précaution chimique.',
      'La recommandation concerne l’espèce, qu’elle soit crue, cuite, congelée ou en conserve.',
      ['Remplacer par une espèce conseillée et bien cuite, comme le saumon, la sardine ou le cabillaud.', 'Vérifier le nom exact de l’espèce sur l’étiquette ou auprès du vendeur.'], ['mercury', 'spf']),
    grains: profile('compatible', 'Un féculent ou un légume sec préparé correctement',
      'Les féculents et légumes secs ont leur place dans une alimentation variée pendant la grossesse. Pour cette famille, les précautions concernent surtout la préparation indiquée sur le paquet et la conservation du plat après cuisson.',
      '« Compatible » vise la forme cuite ou prête à consommer décrite. Une farine ou une pâte destinée à être cuite peut contenir des bactéries avant cuisson.',
      ['Suivre les instructions de préparation ; ne pas goûter de farine ou de pâte crue destinée à être cuite.', 'Réfrigérer les restes au plus tard dans les deux heures, puis les consommer sous trois jours maximum à 4 °C ou moins.'], ['nutrition', 'flour', 'spf']),
    rice: profile('compatible', 'Bacillus cereus : surtout après cuisson',
      'Des spores de Bacillus cereus peuvent survivre à la cuisson du riz. Si le riz cuit reste tiède, les bactéries peuvent se multiplier et produire des toxines ; réchauffer ensuite ne suffit pas toujours à rendre le plat sûr.',
      'Le problème n’est pas une interdiction du riz pendant la grossesse. Pour ses restes, Poum retient le repère prudent de la Food Standards Agency britannique, plus court que le repère français général des restes.',
      ['Manger le riz juste après cuisson, ou le refroidir rapidement en petites portions et le réfrigérer idéalement dans l’heure.', 'Conserver le riz cuit au réfrigérateur au maximum 24 heures ; réchauffer une seule fois jusqu’à ce qu’il soit fumant partout.'], ['rice', 'nutrition']),
    nuts: profile('compatible', 'Pas d’exclusion systématique des fruits à coque',
      'La grossesse n’impose pas d’écarter les noix ou les arachides pour prévenir une allergie chez l’enfant. L’allergie personnelle à l’aliment reste, elle, une raison de l’éviter.',
      'Ce repère vise un aliment courant, en quantité alimentaire, dans un emballage intact et bien conservé. Les mélanges salés ou sucrés se modèrent selon leur composition.',
      ['Choisir une version nature et respecter ses propres allergies.', 'Conserver au sec selon l’emballage ; ne pas manger un produit moisi ou altéré.'], ['nhs', 'nutrition']),
    sweet: profile('limit', 'Une question de composition et de quantité',
      'Les aliments très sucrés ou gras se modèrent pour garder une alimentation variée. Le classement « À limiter » ne signifie pas qu’une portion transmet une infection ou qu’il existe une interdiction spécifique à la grossesse.',
      'Il n’y a pas de portion universelle adaptée à toutes les personnes. La recette peut ajouter une précaution distincte : œuf cru, alcool, caféine ou produit laitier mal conservé.',
      ['Choisir la portion selon son appétit et varier les aliments au fil de la journée.', 'Lire la recette ou l’étiquette et suivre les consignes individualisées en cas de diabète gestationnel.'], ['nutrition']),
    caffeine: profile('limit', 'Additionner la caféine de la journée',
      'La caféine est une substance stimulante. L’EFSA distingue la grossesse de la population adulte générale et évalue l’exposition totale, y compris café, thé, cola, cacao et autres ingrédients caféinés.',
      'Poum retient le repère EFSA de 200 mg par jour au maximum, toutes sources confondues. C’est un repère de consommation, pas une frontière où un milligramme supplémentaire provoquerait forcément un dommage.',
      ['Additionner les teneurs de toutes les portions ; la taille de la tasse et la préparation changent beaucoup la quantité.', 'Privilégier le décaféiné si nécessaire et vérifier les boissons ou compléments contenant du guarana.'], ['efsa', 'caffeineAmounts']),
    alcohol: profile('avoid', 'L’alcool atteint aussi le fœtus',
      'L’alcool traverse le placenta et peut perturber le développement, notamment cérébral. Aucun seuil de consommation sans risque n’a été établi pendant la grossesse ; la recommandation française est donc zéro alcool durant toute la grossesse.',
      'La bière, le vin et les spiritueux sont concernés, tout comme les desserts et les sauces alcoolisés. Une cuisson peut laisser de l’alcool résiduel.',
      ['Choisir une boisson sans alcool et vérifier sa teneur réelle sur l’étiquette.', 'Cuisiner avec du bouillon ou de l’eau à la place du vin et des spiritueux.'], ['spf', 'nutrition']),
    soy: profile('avoid', 'Une précaution française sur les isoflavones',
      'Le soja contient des isoflavones, des substances capables d’interagir avec les récepteurs des œstrogènes. Les recommandations françaises déconseillent les aliments riches en soja pendant la grossesse par précaution face à cette activité hormonale.',
      'La teneur varie selon la fabrication. Cette recommandation ne signifie pas qu’une portion déjà consommée a causé un dommage ; une trace d’allergène ou de la lécithine ne permet pas non plus de déduire une dose d’isoflavones.',
      ['Varier avec lentilles, pois chiches ou autres protéines adaptées.', 'La sauce soja en usage occasionnel est distinguée des aliments au soja par Santé publique France.'], ['soy', 'spf']),
    herbs: profile('unknown', 'La plante, l’extrait et la dose changent la réponse',
      'Une infusion, une huile essentielle et quelques feuilles dans un plat n’exposent pas aux mêmes substances ni aux mêmes doses. Le nom général « plantes » ne suffit pas à juger un mélange ou un extrait pendant la grossesse.',
      '« À vérifier » indique une information insuffisante pour conseiller ce produit. Faire examiner la composition et l’usage par un pharmacien ; les plantes à usage médicinal et les huiles essentielles demandent une vigilance particulière.',
      ['Présenter la liste complète des plantes, la forme et la dose au pharmacien, médecin ou à la sage-femme.', 'Ne pas remplacer un avis sur l’infusion par celui donné pour une petite quantité culinaire.'], ['plants']),
    water: profile('compatible', 'L’eau potable comme boisson de référence',
      'L’eau destinée à la consommation humaine permet de s’hydrater sans alcool, sans caféine et sans sucre ajouté. Le caractère potable, plutôt que la marque, est la condition de ce repère.',
      'Boire régulièrement selon sa soif, en tenant compte des éventuelles consignes personnelles de son équipe soignante.',
      ['Utiliser une eau potable et un contenant propre.', 'Respecter une éventuelle restriction locale de consommation de l’eau.'], ['nutrition']),
    energy: profile('avoid', 'Une boisson stimulante déconseillée',
      'Les boissons énergisantes apportent souvent beaucoup de caféine dans une seule canette, parfois avec d’autres stimulants. L’Assurance Maladie les déconseille pendant la grossesse ; compter seulement le sucre ne suffit pas.',
      'Une version sans sucre reste une boisson énergisante. Les boissons de réhydratation prescrites ne sont pas cette même catégorie.',
      ['Choisir de l’eau à la place.', 'Compter aussi la caféine de la journée si une boisson a déjà été consommée.'], ['nutrition', 'efsa']),
    juice: profile('limit', 'Sucre des boissons et traitement du jus',
      'Un jus, même sans sucre ajouté, apporte les sucres du fruit sous forme de boisson. Il ne remplace pas systématiquement le fruit entier. Il faut aussi distinguer un jus traité d’un jus cru dont l’hygiène n’est pas maîtrisée.',
      'Choisir un jus pasteurisé et le consommer occasionnellement ; l’eau reste la boisson de référence.',
      ['Vérifier le traitement et la durée après ouverture sur l’étiquette.', 'Garder l’eau comme boisson habituelle et respecter la conservation du jus.'], ['nutrition', 'produce']),
    rawJuice: profile('avoid', 'Un jus cru peut conserver des microbes',
      'Presser les fruits ne détruit pas les microbes éventuellement présents. La FDA conseille aux femmes enceintes d’écarter les jus non pasteurisés ou non traités contre les bactéries pathogènes.',
      'Ce repère complémentaire américain porte sur le jus non traité, particulièrement lorsque la préparation n’est pas contrôlable.',
      ['Choisir un jus pasteurisé, en quantité modérée.', 'Au comptoir, demander si le jus a subi un traitement adapté.'], ['produce', 'nutrition']),
    liver: profile('avoid', 'Vitamine A préformée en quantité élevée',
      'Le foie et certains produits qui en contiennent sont très riches en vitamine A sous forme de rétinol. Un apport excessif de cette forme de vitamine A peut être nocif au développement du fœtus.',
      'Le NHS recommande d’éviter foie et produits de foie pendant la grossesse. Cette précaution ne concerne pas de la même manière le bêta-carotène des légumes, comme la carotte.',
      ['Choisir une autre viande bien cuite ou des légumes secs.', 'Ne pas prendre d’huile de foie de poisson ou de supplément de rétinol sans avis médical.'], ['nhs']),
    liquorice: profile('avoid', 'La réglisse peut agir sur la tension',
      'La réglisse peut notamment provoquer une hausse de la pression artérielle et des troubles du rythme cardiaque. L’Assurance Maladie indique une contre-indication pendant la grossesse et l’allaitement.',
      'Toutes les formes contenant de la réglisse sont concernées, y compris bonbons, sirops, tisanes et boissons sans alcool.',
      ['Vérifier la présence de réglisse dans les mélanges de plantes et les confiseries.', 'Choisir une préparation sans réglisse.'], ['ameli']),
    potato: profile('compatible', 'Un tubercule sain, correctement préparé',
      'La pomme de terre est un féculent possible pendant la grossesse. Des glycoalcaloïdes naturellement présents peuvent toutefois être plus concentrés dans les parties vertes ou germées et provoquer une intoxication ; ce risque concerne tout le monde.',
      'Choisir des pommes de terre saines. Une cuisson ne permet pas de récupérer à coup sûr un tubercule vert, très germé ou amer.',
      ['Écarter les pommes de terre vertes, très germées, altérées ou amères ; ne pas goûter pour tester.', 'Laver, éplucher et cuire ; conserver les restes rapidement au froid.'], ['potato', 'nutrition'])
  };
  const data = { sources, profiles, reviewed: '9 septembre 2026', reviewedISO: '2026-09-09' };
  if (typeof module !== 'undefined' && module.exports) module.exports = data;
  root.MietteEvidence = data;
})(typeof window !== 'undefined' ? window : globalThis);
