/* A small, optional introduction. Draft allergies stay in memory until consented save. */
(() => {
  'use strict';
  const Diet=window.PoumDiet;
  const moods=[['all','Un peu de tout','Laissez-moi découvrir.','recipe'],['color','De la couleur','Des bowls, des légumes, du croquant.','leaf'],['comfort','Du réconfort','Un plat chaud, simple et généreux.','heart'],['travel','Une escapade','Des saveurs qui changent.','globe']];
  const moodCollections={color:['bowls'],comfort:['soupes','italie','four'],travel:['voyage']};
  function create(host){
    const esc=host.escape,icon=host.icon;let state=null;
    const ready=()=>!['checking','loading','saving'].includes(host.cloud().status);
    function reset(){const n=host.read();state={owner:host.owner(),step:0,mood:'all',time:30,vegetarian:n.vegetarian,diet:Diet.clean(n.diet),base:JSON.stringify([Diet.clean(n.diet),n.vegetarian]),error:'',offset:0,saved:false,localSaved:false};}
    function ensure(){if(!state||state.owner!==host.owner())reset();}
    function paint(){host.render();requestAnimationFrame(()=>document.querySelector('#ob-title')?.focus({preventScroll:true}));window.scrollTo({top:0,behavior:'instant'});}
    function choices(name,items,value){return items.map(([id,title,description,symbol])=>`<label class="ob-choice"><input type="radio" name="${name}" value="${id}" ${String(value)===String(id)?'checked':''}><span class="ob-choice-icon">${icon(symbol||'clock',22)}</span><span><strong>${title}</strong><small>${description}</small></span><span class="ob-choice-check" aria-hidden="true">${icon('check',14)}</span></label>`).join('');}
    function progress(){return `<ol class="ob-progress" aria-label="Votre parcours">${['Vos envies','Vos préférences','Votre première idée'].map((label,i)=>`<li ${state.step===i+1?'aria-current="step"':''} class="${state.step>=i+1?'is-reached':''}"><span>${state.step>i+1?icon('check',12):i+1}</span><b>${label}</b></li>`).join('')}</ol>`;}
    function header(){return `<header class="ob-header"><a class="ob-brand" href="#accueil" aria-label="Poum, accueil"><img src="assets/brand/mark.svg" alt="" width="34" height="34"><span>poum<span class="ob-brand-dot">.</span></span></a><span class="ob-signature">Alimentation & grossesse</span><a class="ob-exit" href="#accueil">${state.step===3?'Terminer':'Passer pour le moment'} ${icon('arrow',15)}</a></header>`;}
    function intro(){return `<section class="ob-welcome"><div class="ob-welcome-copy"><p class="ob-kicker">Bienvenue à votre table</p><h1 id="ob-title" tabindex="-1">Enceinte.<br>Et toujours<br><em>gourmande.</em></h1><p class="ob-lead">Des repas qui vous ressemblent,<br>pendant votre grossesse.</p><p class="ob-intro-detail">Vos envies changent. On commence par ce qui vous ferait plaisir aujourd’hui&nbsp;?</p><button class="btn ob-primary" data-action="ob-start" ${ready()?'':'disabled'}>Trouver mon premier repas ${icon('arrow',19)}</button><p class="ob-small">${ready()?'Deux petites étapes · Sans carte bancaire':'Chargement de vos préférences…'}</p></div><figure class="ob-welcome-art"><img src="assets/brand/table-maternite-v4-640.webp" alt="Une femme enceinte savoure son repas, la main sur son ventre" width="640" height="640"><figcaption>Une place pour vous.<br><em>Et vos envies du jour.</em></figcaption></figure></section><div class="ob-intro-footer"><span>${icon('leaf',16)} Des précautions grossesse expliquées</span><span>${icon('heart',16)} Vos préférences, à votre rythme</span><a href="#sources">Nos sources ${icon('arrow',14)}</a></div>`;}
    function preferences(){return `<form id="ob-form" class="ob-form"><p class="ob-kicker">01 — Vos envies du jour</p><h1 id="ob-title" tabindex="-1">Qu’est-ce qui vous<br><em>ferait plaisir&nbsp;?</em></h1><p class="ob-description">Aucune bonne réponse. Juste ce qui vous tente.</p><fieldset><legend>Dans votre assiette</legend><div class="ob-choices">${choices('mood',moods,state.mood)}</div></fieldset><fieldset><legend>Le temps que vous avez</legend><div class="ob-times">${[['20','20 min','Au plus simple'],['30','30 min','Un peu de cuisine'],['0','Peu importe','Je prends mon temps']].map(([id,label,note])=>`<label><input type="radio" name="time" value="${id}" ${state.time===Number(id)?'checked':''}><strong>${label}</strong><small>${note}</small></label>`).join('')}</div></fieldset><div class="ob-bottom"><button class="ob-back" type="button" data-action="ob-back">Retour</button><button class="btn ob-primary" type="submit">Continuer ${icon('arrow',18)}</button></div></form>`;}
    function exclusions(){const d=state.diet;return `<form id="ob-form" class="ob-form"><p class="ob-kicker">02 — Ce qui compte pour vous</p><h1 id="ob-title" tabindex="-1">On garde le plaisir.<br><em>On écarte le reste.</em></h1><p class="ob-description">Vos choix sont facultatifs et modifiables dans votre profil.</p><label class="ob-check ob-vegetarian"><input type="checkbox" name="vegetarian" ${state.vegetarian?'checked':''}><span>Je préfère les recettes végétariennes</span>${icon('leaf',19)}</label><fieldset><legend>Des allergies alimentaires ?</legend><div class="ob-allergies">${Diet.allergens.map(a=>`<label><input type="checkbox" name="allergy" value="${a.id}" ${d.allergies.includes(a.id)?'checked':''}><span>${a.id==='gluten'?'Gluten':esc(a.label)}</span></label>`).join('')}</div></fieldset><div class="ob-field"><label for="ob-other">Une autre allergie ?</label><input id="ob-other" class="text-input" name="otherAllergies" maxlength="240" placeholder="Kiwi, banane…" value="${esc(d.otherAllergies)}"></div><label class="ob-check ob-consent"><input id="ob-consent" type="checkbox" name="consent" ${d.consent?'checked':''} aria-describedby="ob-feedback"><span>J’accepte que Poum enregistre mes allergies pour filtrer mes recettes et les synchronise avec mon compte.</span></label><p class="ob-small ob-allergy-note">Vérifiez toujours les ingrédients, les étiquettes et les traces. Le filtrage ne garantit pas l’absence d’allergènes.</p><div class="ob-field"><label for="ob-avoid">Et ce qui ne vous tente pas en ce moment ?</label><input id="ob-avoid" class="text-input" name="avoid" maxlength="240" value="${esc(d.avoid)}" placeholder="Champignons, coriandre…"><small>Séparez les aliments par des virgules. Ce sont vos goûts, distincts des allergies.</small></div><p id="ob-feedback" class="ob-error" role="alert">${esc(state.error)}</p>${state.stale?'<button class="btn btn-outline" type="button" data-action="ob-reload">Reprendre mes préférences enregistrées</button>':''}<div class="ob-bottom"><button class="ob-back" type="button" data-action="ob-back">Retour</button><button class="btn ob-primary" type="submit">Trouver mon repas ${icon('arrow',18)}</button></div></form>`;}
    function selection(){const n=host.read();return host.recipes.filter(r=>!r.premium&&['lunch','dinner'].includes(r.type)&&(!state.time||r.time<=state.time)&&(!n.vegetarian||r.vegetarian)&&Diet.allows(r,n.diet)).sort((a,b)=>Number(moodCollections[state.mood]?.includes(b.collection)||false)-Number(moodCollections[state.mood]?.includes(a.collection)||false)||a.time-b.time);}
    function status(){const c=host.cloud();if(c.user){if(c.status==='synced')return 'Vos préférences sont synchronisées avec votre compte.';if(['error','conflict'].includes(c.status))return 'Vos choix sont appliqués ici. Ouvrez votre profil pour terminer la synchronisation.';return c.status==='offline'?'Vos choix sont appliqués ici. La synchronisation reprendra à la reconnexion.':'Vos choix sont appliqués ici. Synchronisation avec votre compte en cours.';}return state.localSaved?'Vos préférences sont enregistrées sur cet appareil.':'Vos choix sont appliqués dans cet onglet. Votre navigateur ne peut pas les enregistrer.';}
    function result(){const pool=selection(),r=pool[state.offset%Math.max(1,pool.length)];return `<section class="ob-result"><p class="ob-kicker">Votre première idée</p><h1 id="ob-title" tabindex="-1">${r?'Et si on commençait<br><em>par ça&nbsp;?</em>':'On ajuste<br><em>un petit détail&nbsp;?</em>'}</h1><p class="ob-description">${r?`${state.time?'Dans le temps que vous avez. ':''}Vos exclusions déclarées sont appliquées.`:'Aucun déjeuner ou dîner de la sélection gratuite ne correspond à tous vos choix. Vous pouvez ajuster le temps ou explorer le catalogue.'}</p>${r?`<article class="ob-recipe"><div class="ob-recipe-image"><img src="assets/${esc(r.image)}.jpg" alt="" width="600" height="440"><span>${r.time} min · ${r.servings||2} personnes</span></div><div class="ob-recipe-copy"><span class="ob-kicker">Recette complète offerte</span><h2>${esc(r.title)}</h2><p>${esc(r.subtitle||'Les ingrédients, les étapes et les précautions grossesse vous attendent.')}</p><button class="btn ob-primary" data-action="recipe" data-id="${esc(r.id)}">Voir la recette ${icon('arrow',18)}</button>${pool.length>1?'<button class="ob-another" data-action="ob-another">Une autre idée</button>':''}</div></article>`:'<button class="btn ob-primary" data-action="ob-adjust">Ajuster mes choix</button>'}<p class="ob-save-status" id="ob-save-status" role="status">${esc(status())} <a href="#profil">Mon profil</a></p><div class="ob-next"><div><span class="ob-kicker">Et pour les prochains jours ?</span><h2>Une semaine de moins<br>à improviser.</h2><p>Avec Plus, composez vos menus, changez les plats et retrouvez les courses regroupées.</p></div><a class="btn btn-outline" href="#plus">Découvrir Poum Plus ${icon('arrow',16)}</a></div><a class="ob-catalogue" href="#recettes${state.time?'?duree='+state.time:''}">Continuer vers les recettes ${icon('arrow',16)}</a></section>`;}
    function render(){ensure();return `<div class="ob-shell">${header()}${state.step===0?intro():`<div class="ob-layout"><aside class="ob-rail"><p>À votre rythme.<br><em>À votre goût.</em></p><img src="assets/brand/carnet-cuisine-v4-640.webp" alt="" width="640" height="426"><span>Les repas changent.<br>Le plaisir reste à table.</span></aside><div class="ob-content">${progress()}${state.step===1?preferences():state.step===2?exclusions():result()}</div></div>`}</div>`;}
    function input(event){if(!event.target.closest('#ob-form'))return false;ensure();const data=new FormData(event.target.closest('form'));if(state.step===1){state.mood=String(data.get('mood')||'all');state.time=Number(data.get('time')||0);}else{state.vegetarian=data.has('vegetarian');state.diet={...state.diet,allergies:data.getAll('allergy'),otherAllergies:String(data.get('otherAllergies')||''),avoid:String(data.get('avoid')||''),consent:data.has('consent')};}return true;}
    function submit(form){if(form.id!=='ob-form')return false;ensure();input({target:form.querySelector('input')});if(state.step===1){state.step=2;paint();return true;}try{const n=host.read();if(JSON.stringify([Diet.clean(n.diet),n.vegetarian])!==state.base){state.stale=true;throw Error('Vos préférences ont changé ailleurs. Reprenez les derniers choix enregistrés avant de continuer.');}const diet=Diet.validate({...state.diet,completed:true});state.localSaved=host.commit({diet,vegetarian:state.vegetarian});state.saved=true;state.error='';state.step=3;state.base=JSON.stringify([diet,state.vegetarian]);paint();}catch(error){state.error=error.message;paint();requestAnimationFrame(()=>{const target=document.querySelector(!state.diet.consent&&!state.stale?'#ob-consent':'#ob-feedback');target?.scrollIntoView({block:'center'});if(target?.id==='ob-consent'){target.setAttribute('aria-invalid','true');target.focus({preventScroll:true});}});}return true;}
    function click(trigger){const action=trigger.dataset.action;if(!action?.startsWith('ob-'))return false;ensure();if(action==='ob-start'&&ready()){reset();state.step=1;}else if(action==='ob-back')state.step=Math.max(0,state.step-1);else if(action==='ob-another')state.offset++;else if(action==='ob-adjust')state.step=1;else if(action==='ob-reload'){const n=host.read();state.diet=Diet.clean(n.diet);state.vegetarian=n.vegetarian;state.base=JSON.stringify([state.diet,n.vegetarian]);state.stale=false;state.error='';}paint();return true;}
    function refresh(){if(!state)return;if(state.owner!==host.owner()){reset();host.render();return;}const start=document.querySelector('[data-action="ob-start"]');if(start){start.disabled=!ready();const note=start.nextElementSibling;if(note)note.textContent=ready()?'Deux petites étapes · Sans carte bancaire':'Chargement de vos préférences…';}const notice=document.querySelector('#ob-save-status');if(notice)notice.innerHTML=`${esc(status())} <a href="#profil">Mon profil</a>`;}
    return {render,submit,input,click,refresh,editing:()=>state&&state.owner===host.owner()&&[1,2].includes(state.step)};
  }
  window.PoumOnboarding={create};
})();
