(function (root) {
  'use strict';
  const C = typeof module !== 'undefined' && module.exports ? require('./catalogue.js') : root.MietteCatalogue;
  const foods = [];
  function add(family, profile, rows) {
    for (const [id, name, why, step, aliases = '', options = {}] of rows) {
      const familyWords = { spice: 'épices', blend: 'mélange épices', herb: 'aromate herbe', condiment: 'condiment sauce' };
      foods.push({ id, name, category: 'seasoning', family, art: options.art || (family === 'herb' ? 'leafy' : 'spice'), aliases: aliases + ' ' + familyWords[family], summary: step,
        ...C.detail(options.profile || profile, why, step, options) });
    }
  }
  const named = { basis: 'specific' };
  add('spice', 'spice', [
    ['black-pepper', 'Poivre noir', 'Quelques tours de moulin dans un repas relèvent de l’assaisonnement culinaire. Ils ne sont pas équivalents à un extrait de pipérine, notamment associé à de la curcumine en complément.', 'Poivrer selon la recette et votre tolérance.', 'poivre pepper poivres', { sources: ['turmeric'] }],
    ['white-pepper', 'Poivre blanc', 'Le poivre blanc peut parfumer une purée ou une sauce en quantité culinaire. Le repère porte sur l’épice alimentaire, avec une attention au piquant si le plat déclenche des brûlures.', 'Ajouter progressivement dans la préparation.', 'poivres blancs', { sources: ['reflux'] }],
    ['green-peppercorn', 'Poivre vert', 'Le poivre vert utilisé comme épice se distingue d’une sauce au poivre prête à servir. Pour des grains en saumure, le conditionnement et le délai après ouverture restent à respecter.', 'Suivre la conservation du pot et vérifier la sauce complète.', 'poivres verts', { sources: ['spf'] }],
    ['pink-peppercorn', 'Baies roses', 'Les baies roses vendues comme condiment alimentaire relèvent ici du repère culinaire général. Cette fiche ne valide pas des baies sauvages cueillies sans identification.', 'Choisir un pot destiné à la cuisine et assaisonner légèrement.', 'poivre rose baies rose'],
    ['sichuan-pepper', 'Poivre de Sichuan', 'Le poivre de Sichuan peut être employé comme assaisonnement identifié. Sa sensation particulière en bouche ne fournit pas une information sur la sécurité du reste du plat.', 'Utiliser peu pour parfumer la recette.', 'szechuan poivre sichuan'],
    ['paprika', 'Paprika doux', 'Le paprika doux donne une saveur de piment peu piquante. Dans ce repère culinaire, il permet de parfumer un plat sans devoir utiliser une sauce très relevée.', 'Ajouter dans des légumes rôtis ou une sauce bien préparée.', 'paprika doux piment doux'],
    ['smoked-paprika', 'Paprika fumé', 'Le mot fumé décrit ici une épice sèche, pas du poisson fumé réfrigéré. On lui applique les précautions de l’assaisonnement alimentaire plutôt que celles du saumon fumé.', 'Choisir doux ou fort selon l’étiquette et votre tolérance.', 'pimenton paprika fume'],
    ['cumin', 'Cumin', 'Le cumin en graines ou moulu peut assaisonner une recette. Un plat de lentilles parfumé au cumin est différent d’une cure de graines ou d’un extrait de plante.', 'Ajouter aux légumes ou aux légumes secs pendant leur préparation.', 'cumin graine moulu'],
    ['coriander-seed', 'Graines de coriandre', 'Les graines de coriandre sont une épice différente des feuilles fraîches à laver. Cette fiche couvre l’usage sec dans une recette, avec un produit alimentaire conservé correctement.', 'Écraser ou moudre la quantité prévue par la recette.', 'coriandre graine moulue'],
    ['turmeric', 'Curcuma en cuisine', 'Le curcuma utilisé pour colorer et parfumer un plat ne reçoit pas le même conseil qu’un complément de curcumine. Le NCCIH signale que les compléments de curcuma peuvent être non sûrs pendant la grossesse.', 'Utiliser comme épice du plat ; ne pas transformer ce repère en cure.', 'curcuma turmeric curcumine', { sources: ['turmeric'], note: 'Une gélule ou un extrait de curcumine n’est pas couvert par le repère culinaire.' }],
    ['cinnamon-ceylon', 'Cannelle de Ceylan', 'Le NCCIH distingue les quantités habituelles dans l’alimentation des quantités élevées pendant la grossesse. La cannelle de Ceylan contient généralement moins de coumarine que la cannelle cassia, ce qui ne valide pas une cure.', 'Parfumer une compote ou un porridge avec une petite quantité.', 'cannelle ceylan verum', { sources: ['cinnamon', 'coumarin'], basis: 'specific', art: 'cinnamon' }],
    ['cinnamon-cassia', 'Cannelle cassia ou d’espèce inconnue', 'Lorsque le pot indique cassia, Chine ou ne précise pas l’espèce, la teneur en coumarine n’est pas connue. Le classement à limiter vise surtout une utilisation importante ou répétée, pas l’idée qu’un dessert serait automatiquement dangereux.', 'Employer avec parcimonie ; ne pas en prendre en cure quotidienne.', 'cannelle chine casse cassia poudre', { profile: 'cassia', basis: 'specific', art: 'cinnamon' }],
    ['nutmeg', 'Noix de muscade', 'Une petite quantité de muscade râpée dans un gratin est un assaisonnement. Le guide n’étend pas ce repère à une noix entière consommée seule, à une boisson concentrée ou à un usage médicinal.', 'Râper légèrement pour parfumer une purée ou une béchamel.', 'muscade noix muscade nutmeg'],
    ['mace', 'Macis', 'Le macis utilisé comme épice aromatise la recette en petite quantité. Sa présence dans un mélange ne permet pas de déduire la composition des autres ingrédients.', 'Suivre la quantité culinaire prévue par la recette.', 'macis fleur muscade'],
    ['clove', 'Clou de girofle', 'Le clou de girofle ajouté à un plat correspond à un usage culinaire. Cette fiche ne s’applique pas à son huile essentielle ni à un remède dentaire préparé avec un extrait concentré.', 'Parfumer la cuisson puis retirer les clous entiers avant de servir.', 'girofle clous girofle'],
    ['cardamom', 'Cardamome', 'La cardamome peut parfumer un dessert ou un plat en quantité culinaire. Une boisson qui en contient peut aussi apporter caféine ou sucre : il faut examiner la recette complète.', 'Employer la quantité de la recette et retirer les cosses si nécessaire.', 'cardamome verte noire cardamom', { sources: ['efsa', 'nutrition'] }],
    ['saffron', 'Safran en cuisine', 'Quelques filaments répartis dans un plat relèvent de l’usage culinaire du safran. Cela ne permet pas de conseiller des gélules, des extraits ou une consommation recherchée pour agir sur la grossesse.', 'Utiliser les filaments prévus pour parfumer le plat entier.', 'safran saffron'],
    ['vanilla', 'Vanille en gousse ou en poudre', 'La vanille alimentaire peut parfumer un dessert. Cette fiche se distingue d’un extrait liquide contenant de l’alcool : vérifier l’étiquette de la forme réellement utilisée.', 'Gratter une gousse ou choisir une poudre sans alcool ajouté.', 'vanille vanilla gousse poudre', { sources: ['spf'] }],
    ['star-anise', 'Badiane alimentaire', 'La badiane vendue pour la cuisine est ici considérée comme un assaisonnement identifié. Le repère ne couvre ni une plante cueillie, ni une tisane concentrée, ni une cure de badiane.', 'Choisir de la badiane alimentaire et retirer l’épice entière avant de servir.', 'badiane anis etoile étoilé'],
    ['anise-seed', 'Anis vert en graines', 'Quelques graines d’anis vert dans une recette sont un usage culinaire. Leur nom ne valide pas une huile essentielle, une infusion concentrée ni une boisson anisée contenant de l’alcool.', 'Utiliser dans la recette et vérifier les boissons séparément.', 'anis vert graine', { sources: ['spf'] }],
    ['fennel-seed', 'Graines de fenouil', 'Les graines de fenouil employées comme assaisonnement sont distinctes d’une infusion ou d’un complément à base de fenouil. Cette fiche ne conseille aucun usage pour traiter un symptôme.', 'Ajouter la petite quantité culinaire prévue dans le plat.', 'fenouil graine'],
    ['caraway', 'Carvi', 'Le carvi peut parfumer du pain ou des légumes en quantité culinaire. Le repère concerne le condiment identifié, sans assimilation à un traitement digestif par les plantes.', 'Doser selon la recette de pain ou de légumes.', 'carvi cumin pres'],
    ['dill-seed', 'Graines d’aneth', 'Les graines d’aneth sont employées ici comme épice sèche. Elles se distinguent des feuilles fraîches à laver et des préparations concentrées à base d’aneth.', 'Ajouter en assaisonnement et conserver les graines au sec.', 'aneth graine'],
    ['mustard-seed', 'Graines de moutarde', 'Les graines de moutarde peuvent assaisonner un plat, sous réserve d’une allergie personnelle. La grossesse ne permet pas d’ignorer un allergène déjà connu.', 'Vérifier ses allergies et utiliser dans une recette adaptée.', 'moutarde graine jaune brune', { sources: ['nutrition'] }],
    ['fenugreek', 'Fenugrec en cuisine', 'Le fenugrec utilisé comme épice appelle une distinction particulièrement explicite : le NCCIH écarte pendant la grossesse les quantités supérieures à l’usage alimentaire. La fiche ne valide donc aucun complément.', 'Employer seulement dans la quantité culinaire de la recette.', 'fenugrec methi', { profile: 'fenugreek', ...named }],
    ['nigella', 'Graines de nigelle en cuisine', 'Quelques graines alimentaires sur un pain relèvent de l’assaisonnement. Ce repère général ne démontre pas la compatibilité d’une huile de nigelle prise en cure ou d’une gélule.', 'Utiliser seulement comme garniture alimentaire de la recette.', 'nigelle cumin noir habba sawda'],
    ['sumac', 'Sumac alimentaire', 'Le sumac acheté comme condiment peut apporter une saveur acidulée à un plat. L’acidité ne remplace pas le lavage des légumes ou la cuisson d’un ingrédient cru à risque.', 'Assaisonner un plat préparé proprement avec du sumac alimentaire.', 'sumac sumak', { sources: ['spf'] }],
    ['juniper', 'Baies de genièvre', 'Miamama ne dispose pas ici d’un repère de grossesse suffisamment précis pour conseiller la quantité de baies de genièvre. Une utilisation comme plante médicinale et une baie dans un plat ne se confondent pas ; demander conseil pour l’usage envisagé.', 'Faire vérifier la forme et la quantité ; choisir une autre épice en attendant.', 'genievre genièvre baies juniper', { profile: 'herbs' }],
    ['ginger-ground', 'Gingembre moulu', 'Le gingembre moulu peut assaisonner une recette. Cette fiche ne donne pas de dose pour traiter les nausées et ne couvre pas un shot concentré ou un complément de gingembre.', 'Utiliser la quantité d’assaisonnement prévue, répartie dans le plat.', 'gingembre poudre ground ginger'],
    ['garlic-powder', 'Ail en poudre', 'L’ail déshydraté destiné à la cuisine peut parfumer un plat. Un sel à l’ail ajoute du sel, tandis qu’un complément d’ail concentré relève d’un autre usage.', 'Vérifier s’il s’agit d’ail seul ou d’un sel aromatisé.', 'ail poudre semoule deshydrate', { sources: ['nutrition'] }],
    ['onion-powder', 'Oignon en poudre', 'L’oignon déshydraté est un assaisonnement alimentaire possible. Pour un mélange à l’oignon, la composition complète et le sel ajouté restent à prendre en compte.', 'Lire l’étiquette et répartir la quantité dans la recette.', 'oignon poudre deshydrate', { sources: ['nutrition'] }],
    ['allspice', 'Piment de la Jamaïque', 'Le piment de la Jamaïque vendu comme épice unique ne se confond pas avec un mélange quatre-épices. Le guide lui applique le repère de l’assaisonnement en quantité culinaire.', 'Vérifier le produit puis utiliser selon la recette.', 'piment jamaique tout epice allspice quatre epices baie']
  ]);
  add('spice', 'spicy', [
    ['cayenne', 'Piment de Cayenne', 'Le piment de Cayenne peut rendre un plat très relevé. Le point pratique est la tolérance au reflux : réduire sa quantité si des brûlures apparaissent, en conservant les autres précautions du repas.', 'Commencer par très peu et ajuster selon votre confort.', 'cayenne piment fort', { art: 'pepper' }],
    ['espelette', 'Piment d’Espelette', 'Le piment d’Espelette utilisé comme assaisonnement peut convenir selon la tolérance digestive. Son origine ne dispense pas de modérer le piquant s’il favorise des brûlures d’estomac.', 'Assaisonner progressivement plutôt que rendre tout le plat très piquant.', 'espelette piment', { art: 'pepper' }],
    ['chilli-flakes', 'Piment en flocons', 'Les flocons de piment peuvent varier fortement en intensité. Il faut adapter la quantité au produit et au confort digestif, sans supposer qu’une cuillère de chaque piment se vaut.', 'Ajouter en petite quantité ; choisir une version douce si nécessaire.', 'chili chilli flocon piment', { art: 'pepper' }]
  ]);
  add('herb', 'spice', [
    ['bay-leaf', 'Laurier-sauce alimentaire', 'Le laurier-sauce identifié pour la cuisine peut parfumer une cuisson. Ce repère ne concerne pas les autres plantes appelées laurier ni une plante de jardin non identifiée.', 'Utiliser du laurier-sauce alimentaire puis retirer la feuille avant de servir.', 'laurier sauce feuille bouquet garni'],
    ['oregano', 'Origan en cuisine', 'L’origan utilisé sur une sauce ou une pizza relève de l’usage culinaire des aromates. L’huile essentielle d’origan n’est pas couverte par cette fiche alimentaire.', 'Utiliser en assaisonnement ; laver les feuilles si elles sont fraîches.', 'origan oregano', { sources: ['toxo'] }],
    ['marjoram', 'Marjolaine en cuisine', 'La marjolaine peut parfumer une recette en petite quantité alimentaire. Le guide ne donne pas de conseil pour une infusion régulière ou un extrait destiné à agir sur un symptôme.', 'Assaisonner selon la recette et laver les brins frais.', 'marjolaine', { sources: ['toxo'] }],
    ['tarragon', 'Estragon en cuisine', 'L’estragon ajouté comme aromate à un plat se distingue d’une huile essentielle. Une sauce à l’estragon doit aussi être jugée sur ses œufs, ses produits laitiers et son éventuel alcool.', 'Laver l’estragon frais et vérifier tous les ingrédients de la sauce.', 'estragon tarragon', { sources: ['spf', 'toxo'] }],
    ['sage-leaf', 'Sauge officinale', 'Le NCCIH signale une précaution pendant la grossesse liée à la thuyone de certaines sauges et conseille un avis professionnel. Faute de quantité précise applicable à votre usage, Miamama conserve « À vérifier », y compris pour choisir la forme culinaire.', 'Faire vérifier l’espèce, la forme et l’usage ; éviter les huiles essentielles et cures.', 'sauge officinale salvia', { profile: 'herbs', sources: ['sage'], ...named }]
  ]);
  add('blend', 'spiceBlend', [
    ['curry-powder', 'Curry en poudre', 'Le curry est un mélange, pas une épice unique. Sa composition peut inclure curcuma, cumin, fenugrec ou piment : le nom ne donne ni la proportion de chaque épice ni l’intensité.', 'Lire le mélange et doser pour un curry de légumes ou de volaille bien cuite.', 'curry poudre madras'],
    ['garam-masala', 'Garam masala', 'Le garam masala peut associer plusieurs épices, notamment cannelle, cardamome ou girofle. Une petite quantité d’assaisonnement se distingue de la prise répétée de chaque plante sous forme concentrée.', 'Lire la composition puis utiliser la quantité culinaire de la recette.', 'garam masala'],
    ['ras-el-hanout', 'Ras el-hanout', 'La recette du ras el-hanout varie beaucoup. Un mélange dont les plantes sont nommées peut être examiné ; une poudre sans composition identifiable ne reçoit pas de feu vert sur son seul nom.', 'Choisir une composition lisible et assaisonner le plat avec modération.', 'ras el hanout raz hanout'],
    ['colombo', 'Colombo', 'La poudre de colombo est un assemblage d’épices. La présence possible de moutarde ou de fenugrec et les autres ingrédients doivent être lus avant de l’utiliser.', 'Vérifier le mélange et incorporer la quantité de la recette.', 'colombo poudre'],
    ['four-spice', 'Quatre-épices', 'Quatre-épices désigne un mélange dont les proportions et parfois les ingrédients changent. Vérifier notamment la cannelle et ne pas en déduire un avis sur une seule épice isolée.', 'Lire l’étiquette puis parfumer légèrement une préparation cuite.', 'quatre epices 4 epices'],
    ['five-spice', 'Cinq-épices', 'Un mélange cinq-épices peut associer badiane, fenouil, cannelle et d’autres épices. Cette association culinaire doit être identifiée ; elle n’est pas une infusion ou une préparation médicinale.', 'Vérifier les ingrédients et utiliser en assaisonnement du plat.', 'cinq epices cinq parfums 5 epices'],
    ['zaatar', 'Za’atar', 'Le za’atar peut contenir des herbes, du sumac, du sésame et du sel. Le sésame est à considérer en cas d’allergie ; la fiche ne suppose pas la même composition pour toutes les marques.', 'Vérifier notamment le sésame et le sel ajouté.', 'zaatar za atar zahtar'],
    ['herbes-provence', 'Herbes de Provence', 'Les herbes de Provence sont un mélange culinaire sec. Vérifier la liste, en particulier si une plante comme la sauge est ajoutée, plutôt que supposer une recette unique.', 'Lire les herbes présentes et utiliser dans la quantité de la recette.', 'herbes provence', { art: 'leafy' }],
    ['cajun', 'Mélange cajun', 'Un mélange cajun peut apporter à la fois du piment et du sel. Son usage demande de lire l’assaisonnement avant de saler le plat et d’adapter le piquant au reflux éventuel.', 'Doser progressivement et goûter le plat une fois ses ingrédients à risque cuits.', 'cajun epices'],
    ['tandoori', 'Mélange tandoori', 'Le mélange tandoori parfume une marinade, mais les épices ne cuisent pas la viande. Une recette au yaourt et à la volaille nécessite aussi lait pasteurisé, froid et cuisson complète.', 'Lire le mélange, garder la marinade au froid puis cuire la volaille à cœur.', 'tandoori tikka', { sources: ['poultry', 'temperature'] }]
  ]);
  add('condiment', 'pantry', [
    ['harissa', 'Harissa', 'La harissa est une pâte condimentaire dont la composition et la force varient. Le piquant peut aggraver un reflux ; après ouverture, la conservation indiquée compte aussi.', 'Employer peu, conserver selon le pot et réduire si des brûlures apparaissent.', 'harissa sauce piment', { sources: ['reflux'], art: 'pepper' }],
    ['sriracha', 'Sauce sriracha', 'La sriracha associe du piment à d’autres ingrédients, souvent du sucre et du sel. Elle se dose comme condiment et selon la tolérance digestive, sans que le nom valide toutes les recettes.', 'Lire les ingrédients et adapter la petite quantité ajoutée au repas.', 'sriracha sauce', { sources: ['reflux'], art: 'pepper' }],
    ['tabasco', 'Sauce type Tabasco', 'Une sauce pimentée vinaigrée se distingue d’un alcool de boisson. Son acidité et son piquant peuvent toutefois être mal tolérés en cas de reflux.', 'Ajouter quelques gouttes selon votre confort et lire l’étiquette.', 'tabasco sauce piquante', { sources: ['reflux'], art: 'pepper' }],
    ['salsa', 'Sauce salsa', 'Une salsa en bocal prêt à consommer se conserve selon son étiquette. Pour une salsa fraîche maison, tomates, herbes et autres végétaux doivent être soigneusement lavés.', 'Respecter le délai après ouverture ou laver tous les végétaux de la version maison.', 'salsa sauce tomate pimentee', { sources: ['toxo'], art: 'tomato' }],
    ['wasabi', 'Wasabi en condiment', 'Une pâte vendue comme wasabi peut contenir du raifort, de la moutarde et d’autres ingrédients. Lire le produit et ne pas considérer le condiment comme une protection pour du poisson cru.', 'Vérifier la composition et choisir un plat dont le poisson est entièrement cuit.', 'wasabi pate poudre', { sources: ['spf'], art: 'spice' }],
    ['horseradish', 'Raifort en condiment', 'Le raifort préparé se juge avec les ingrédients de sa sauce et sa conservation. Son goût fort peut demander une quantité plus faible en cas de reflux.', 'Choisir une préparation alimentaire et suivre ses consignes de conservation.', 'raifort horseradish', { sources: ['reflux'], art: 'spice' }],
    ['pesto', 'Pesto', 'Un pesto contient souvent herbes, fromage et fruits à coque. Le lavage des herbes pour une version maison, le type de fromage et la conservation sont plus utiles à vérifier que la seule couleur du pesto.', 'Vérifier le fromage, les allergies et le délai après ouverture.', 'pesto vert rouge basilic', { sources: ['spf', 'toxo'], art: 'leafy' }],
    ['capers', 'Câpres en bocal', 'Les câpres prêtes à consommer sont un condiment salé. Le vinaigre ou la saumure ne permettent pas d’ignorer les instructions de conservation après ouverture.', 'Prélever proprement et suivre l’étiquette du bocal.', 'capres caprons', { art: 'beans' }],
    ['preserved-lemon', 'Citron confit au sel', 'Le citron confit alimentaire peut parfumer un plat. Sa préparation au sel n’en fait pas un citron frais à consommer sans tenir compte du sel ni de la conservation.', 'Employer comme condiment, puis suivre le délai du bocal ouvert.', 'citron confit sale', { art: 'citrus' }],
    ['stock-cube', 'Bouillon cube ou en poudre', 'Un bouillon peut contenir beaucoup de sel, du céleri, du lait ou d’autres allergènes selon sa recette. Il ne remplace pas une vraie cuisson des ingrédients ajoutés dans la casserole.', 'Lire les ingrédients, préparer selon le paquet et ajuster le sel du plat.', 'bouillon cube poudre fond legumes volaille', { art: 'spice' }]
  ]);
  if (typeof module !== 'undefined' && module.exports) module.exports = foods;
  root.MietteSeasonings = foods;
})(typeof window !== 'undefined' ? window : globalThis);
