(() => {
  const V=window.PoumDinnerView,root=document.querySelector('#relay-content'),feedback=document.querySelector('#relay-feedback');
  const token=location.hash.slice(1);let meal=null,busy=false,closed=false,generation=0;
  async function request(body){const response=await fetch('/api/tonight',{method:'POST',credentials:'omit',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,token}),signal:AbortSignal.timeout(15000)});const result=await response.json();if(!response.ok){const e=Error(result.error||'La connexion a été interrompue.');e.status=response.status;throw e;}return result.meal;}
  function accept(next){if(meal&&meal.revision>next.revision)return;const first=!meal;meal=next;if(first)root.innerHTML=V.meal(meal);else V.sync(root,meal);const text='Les courses cochées sont partagées avec la personne qui a prévu le dîner.';if(feedback.textContent!==text)feedback.textContent=text;}
  function fail(e){if(e.status===404){closed=true;generation++;meal=null;root.innerHTML='';feedback.textContent='Ce lien est invalide, expiré ou désactivé. Demandez un nouveau lien à la personne qui vous l’a envoyé.';}else{feedback.textContent='La synchronisation est interrompue. Vos dernières modifications n’ont pas été enregistrées. Vérifiez votre connexion puis réessayez.';if(meal)V.sync(root,meal);else root.innerHTML='<button class="btn btn-outline" id="relay-retry">Réessayer</button>';}}
  async function load(){if(busy||closed||document.hidden)return;const ticket=generation;try{const next=await request({action:'shared-read'});if(ticket===generation)accept(next);}catch(e){fail(e);}}
  async function patch(field,value){if(busy||!meal)return;busy=true;root.querySelectorAll('input,button').forEach(el=>el.disabled=true);const ticket=generation;try{const next=await request({action:'shared-patch',field,value});if(ticket===generation){accept(next);if(field==='status'&&value==='cooking'){const details=root.querySelector('.dinner-method');details.open=true;details.scrollIntoView({block:'start'});}}}catch(e){fail(e);}finally{busy=false;root.querySelectorAll('input,button').forEach(el=>el.disabled=false);if(meal)V.sync(root,meal);}}
  root.addEventListener('change',e=>{if(e.target.matches('[data-dinner-item],[data-dinner-step]'))patch(e.target.dataset.dinnerStep!==undefined?'step:'+e.target.dataset.dinnerStep:Number(e.target.dataset.dinnerItem),e.target.checked);});
  root.addEventListener('click',e=>{const b=e.target.closest('[data-dinner-status]');if(b&&!b.disabled)patch('status',b.dataset.dinnerStatus);if(e.target.id==='relay-retry')load();});
  if(!/^[-_a-zA-Z0-9]{43}$/.test(token)){closed=true;feedback.textContent='Il manque le lien du dîner. Demandez à la personne qui cuisine avec vous de le partager depuis Poum.';}else load();
  setInterval(load,5000);window.addEventListener('online',load);document.addEventListener('visibilitychange',load);
})();
