const {test,expect}=require('@playwright/test');
const AxeBuilder=require('@axe-core/playwright').default;
const N=require('../js/notebook.js'),P=require('../js/pregnancy.js');
async function local(page){await page.route('**/api/config',r=>r.fulfill({json:{accounts:false}}));}
async function setup(page){await local(page);await page.goto('/#grossesse');await page.locator('#pregnancy-date').fill(P.add(P.today(),-100));await page.locator('#pregnancy-form [name=consent]').check();await page.locator('#pregnancy-form [type=submit]').click();await expect(page).toHaveURL(/#calendrier$/);}
function pdfBuffer(){const stream='BT /F1 20 Tf 50 740 Td (NFS) Tj 0 -40 Td (Ferritine : 25 ng/mL) Tj ET';const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`];let pdf='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(Buffer.byteLength(pdf));pdf+=`${i+1} 0 obj\n${o}\nendobj\n`;});const x=Buffer.byteLength(pdf);pdf+=`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(o=>String(o).padStart(10,'0')+' 00000 n \n').join('')}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${x}\n%%EOF`;return Buffer.from(pdf);}
async function addExam(page){await page.goto('/#examens');await page.locator('#exam-title').fill('Mon bilan');await page.locator('#exam-items').fill('NFS\nFerritine\nTSH');await page.locator('#journey-exam [type=submit]').click();await expect(page.locator('.j-exam-card')).toHaveCount(1);}
test('Pregnancy setup persists without putting health information in URLs and term changes preserve appointments',async({page})=>{
 await setup(page);expect(new URL(page.url()).search).toBe('');await expect(page.locator('[data-task]')).toHaveCount(23);
 const task=page.locator('[data-task=echo2]');await task.locator('summary').click();const appointment=P.add(P.today(),20);await task.locator('[name=date]').fill(appointment);await task.locator('[name=time]').fill('10:30');await task.locator('[name=status]').selectOption('scheduled');await task.locator('[name=note]').fill('Une question pour mon rendez-vous');await task.locator('[type=submit]').click();
 await page.goto('/#grossesse');await page.locator('#pregnancy-basis').selectOption('term');await page.locator('#pregnancy-date').fill(P.add(P.today(),190));await page.locator('#pregnancy-form [type=submit]').click();await page.reload();await task.locator('summary').click();await expect(task.locator('[name=date]')).toHaveValue(appointment);await expect(task.locator('[name=note]')).toHaveValue('Une question pour mon rendez-vous');
});
test('Results require explicit evidence confirmation; unseen analyses are never automatically marked received',async({page})=>{
 await setup(page);await addExam(page);await page.locator('.j-exam-card summary').filter({hasText:'Coller le texte'}).click();await page.locator('[data-compare-exam] textarea').fill('NFS : compte rendu\nFerritine : 25 ng/mL');await page.locator('[data-compare-exam] [type=submit]').click();
 await expect(page.locator('#document-review')).toBeVisible();await expect(page.locator('#document-review')).toContainText('Non retrouvé dans ce document');await expect(page.locator('#document-review input:checked')).toHaveCount(0);await page.locator('#document-review [type=submit]').click();await expect(page.locator('#journey-feedback')).toContainText('Cochez au moins');
 await page.locator('#document-review input').first().check();await page.locator('#document-review [type=submit]').click();await page.reload();const j=await page.evaluate(()=>JSON.parse(localStorage.getItem('miette-notebook-v1')).journey);expect(j.exams[0].items.map(i=>i.status)).toEqual(['received','expected','expected']);expect(j.exams[0].items[0].evidence).toContain('NFS');
});
test('A real PDF is read locally, supplies page evidence and never uploads its contents',async({page})=>{
 await setup(page);await addExam(page);const posts=[];page.on('request',r=>{if(r.method()==='POST')posts.push(r.url())});await page.locator('[data-document-kind=result]').setInputFiles({name:'bilan.pdf',mimeType:'application/pdf',buffer:pdfBuffer()});await expect(page.locator('#document-review')).toBeVisible({timeout:20000});await expect(page.locator('#document-review blockquote')).toHaveCount(2);expect(posts).toEqual([]);await expect(page.locator('#document-review')).toContainText('Page 1');
});
test('A real image is recognised on-device and prescription suggestions still require review',async({page})=>{
 test.setTimeout(90000);await setup(page);await page.goto('/#examens');const image=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=1200;c.height=350;const x=c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,1200,350);x.fillStyle='black';x.font='48px Arial';x.fillText('NFS',70,90);x.fillText('Ferritine',70,180);x.fillText('TSH',70,270);return c.toDataURL('image/png').split(',')[1]});const requests=[];page.on('request',r=>requests.push({url:r.url(),method:r.method()}));await page.locator('#prescription-file').setInputFiles({name:'ordonnance.png',mimeType:'image/png',buffer:Buffer.from(image,'base64')});await expect(page.locator('#exam-items')).toHaveValue(/Ferritine/,{timeout:60000});await expect(page.locator('#exam-items')).toHaveValue(/NFS/);expect(requests.filter(r=>r.method==='POST')).toEqual([]);expect(requests.filter(r=>/^https?:/.test(r.url)&&!r.url.startsWith('http://localhost:4176/'))).toEqual([]);await expect(page.locator('.j-exam-card')).toHaveCount(0);
});
test('Temporary cravings are visible and cannot erase saved allergies',async({page})=>{
 await local(page);await page.goto('/#profil');await page.locator('[name=allergy][value=milk]').check();await page.locator('[name=diet-consent]').check();await page.locator('#profile-save').click();await page.goto('/#envies');await page.locator('#craving-avoid').fill('coriandre');await page.locator('#craving-text').fill('poisson');await page.locator('#craving-duration').selectOption('today');await page.locator('#journey-cravings [type=submit]').click();await expect(page.locator('.j-diet-summary')).toContainText('Lait');await expect(page.locator('.j-diet-summary')).toContainText('poisson');const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('miette-notebook-v1')).diet);expect(state.allergies).toEqual(['milk']);expect(state.avoid).toBe('coriandre');expect(state.temporary.until).toBe(P.today());
 await page.goto('/#profil');await page.locator('#profile-name').fill('Camille');await page.locator('#profile-save').click();await expect(page.locator('#profile-avoid')).toHaveCount(0);const preserved=await page.evaluate(()=>JSON.parse(localStorage.getItem('miette-notebook-v1')).diet);expect(preserved.temporary.text).toBe('poisson');expect(preserved.avoid).toBe('coriandre');await page.getByRole('link',{name:'Gérer mes goûts et mes envies'}).click();await expect(page.locator('#craving-avoid')).toHaveValue('coriandre');await page.locator('[data-action=journey-craving-clear]').click();const cleared=await page.evaluate(()=>JSON.parse(localStorage.getItem('miette-notebook-v1')).diet);expect(cleared.temporary.text).toBe('');expect(cleared.avoid).toBe('coriandre');expect(cleared.allergies).toEqual(['milk']);
 await page.goto('/#envies');await page.locator('[data-action=journey-craving-clear]').click();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('miette-notebook-v1')).diet.allergies)).toEqual(['milk']);
});
test('Pause and withdrawal are explicit, persist and retain the separate food notebook',async({page})=>{
 await setup(page);await page.goto('/#grossesse');await page.locator('[data-action=journey-pause]').click();await page.goto('/#calendrier');await expect(page.locator('h1')).toContainText('pause');await page.goto('/#grossesse');await page.locator('summary').filter({hasText:'Effacer mon suivi'}).click();await page.locator('[data-action=journey-erase]').click();await page.reload();await expect(page.locator('#pregnancy-date')).toHaveValue('');const s=await page.evaluate(()=>JSON.parse(localStorage.getItem('miette-notebook-v1')));expect(s.journey).toEqual(P.empty());expect(s.shopping).toEqual([]);
});
test('The new mobile screens have no overflow or serious accessibility violations',async({page})=>{
 await setup(page);await page.setViewportSize({width:390,height:844});for(const url of ['/#accueil','/#grossesse','/#calendrier','/#examens','/#envies','/#plus']){await page.goto(url);await page.evaluate(async()=>{await document.fonts.ready;await Promise.allSettled(document.getAnimations().map(a=>a.finished));});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),url).toBe(true);const r=await new AxeBuilder({page}).analyze();expect(r.violations.filter(v=>['serious','critical'].includes(v.impact)).map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),url).toEqual([]);}
});
test('New health information stays isolated across two accounts and the guest notebook',async({page})=>{
 let user=null;const remote={};await page.route('**/api/**',async route=>{const path=new URL(route.request().url()).pathname;if(path==='/api/config')return route.fulfill({json:{accounts:true}});if(path==='/api/auth/get-session')return route.fulfill({json:user?{user}:null});if(path==='/api/auth/sign-in/email'){const {email}=route.request().postDataJSON();user={id:email,email};return route.fulfill({json:{user}})}if(path==='/api/auth/sign-out'){user=null;return route.fulfill({json:{}})}if(path==='/api/notebook'){if(!user)return route.fulfill({status:401,json:{error:'Connexion nécessaire'}});if(route.request().method()==='PUT'){const body=route.request().postDataJSON();remote[user.id]={notebook:body.notebook,revision:body.revision+1}}return route.fulfill({json:remote[user.id]||{notebook:null,revision:0}})}if(path==='/api/billing')return route.fulfill({json:{configured:false,access:{active:false}}});return route.fulfill({json:{}})});
 await page.goto('/#grossesse');await page.locator('#pregnancy-date').fill(P.add(P.today(),-90));await page.locator('[name=consent]').check();await page.locator('#pregnancy-form [type=submit]').click();
 const login=async(email)=>{await page.goto('/#profil');await page.locator('#auth-email').fill(email);await page.locator('#auth-password').fill('correct-password');await page.locator('[name=import]').uncheck();await page.locator('#auth-form [type=submit]').click();await expect(page.locator('[data-action=sign-out]')).toBeVisible();};
 await login('one@example.com');await page.goto('/#grossesse');await expect(page.locator('#pregnancy-date')).toHaveValue('');await page.locator('#pregnancy-date').fill(P.add(P.today(),-130));await page.locator('[name=consent]').check();await page.locator('#pregnancy-form [type=submit]').click();await page.goto('/#profil');await page.locator('[data-action=sign-out]').click();await expect(page.locator('#auth-form')).toBeVisible();await page.goto('/#grossesse');await expect(page.locator('#pregnancy-date')).toHaveValue(P.add(P.today(),-90));
 await login('two@example.com');await page.goto('/#grossesse');await expect(page.locator('#pregnancy-date')).toHaveValue('');expect(remote['one@example.com'].notebook.journey.profile.date).toBe(P.add(P.today(),-130));
});

test('Calendar labels show periods and deadlines instead of an invented declaration date, and export requires an entered date',async({page})=>{
 await page.clock.setFixedTime(new Date('2026-09-16T12:00:00Z'));await local(page);await page.goto('/#grossesse');await page.locator('#pregnancy-date').fill('2026-08-11');await page.locator('#pregnancy-form [name=consent]').check();await page.locator('#pregnancy-form [type=submit]').click();
 const declaration=page.locator('[data-task=declaration]');await expect(declaration.locator('.j-timeline-date')).toContainText('Avant la fin du 3e mois');await expect(declaration.locator('.j-timeline-date')).not.toContainText('6 octobre');
 await expect(page.locator('[data-task=echo1] .j-timeline-date')).toContainText('Du 27 octobre au 16 novembre');await expect(page.locator('[data-task=echo1]')).toContainText('11 SA à 13 SA + 6 jours');
 await page.locator('[data-action=journey-export]').click();await expect(page.locator('#journey-feedback')).toContainText('Renseignez d’abord la date');
 await declaration.locator('summary').click();await declaration.locator('[name=date]').fill('2026-11-05');await declaration.locator('[name=status]').selectOption('scheduled');await declaration.locator('[type=submit]').click();await expect(declaration.locator('.j-timeline-date')).toContainText('Le 5 novembre');await expect(declaration.locator('.j-timeline-date')).toContainText('Date saisie par vous');
});

test('Checking an appointment hides it from pending lists, survives reload and can be undone without losing details',async({page})=>{
 await setup(page);const task=page.locator('[data-task=echo2]'),appointment=P.add(P.today(),20);await task.locator('summary').click();await task.locator('[name=date]').fill(appointment);await task.locator('[name=time]').fill('10:30');await task.locator('[name=note]').fill('À apporter : mon dossier');await task.locator('[name=status]').selectOption('scheduled');await task.locator('[type=submit]').click();
 await task.locator('[data-action=journey-task-done]').click();await expect(task).toHaveCount(0);await expect(page.locator('#journey-feedback')).toContainText('conservée dans « Faits »');await page.reload();await expect(task).toHaveCount(0);
 await page.locator('[data-action=journey-filter][data-value=rendezvous]').click();await expect(task).toHaveCount(0);await page.locator('[data-action=journey-filter][data-value=done]').click();await expect(task).toBeVisible();await expect(task.locator('[data-action=journey-task-done]')).toBeChecked();await task.locator('summary').click();await expect(task.locator('[name=date]')).toHaveValue(appointment);await expect(task.locator('[name=time]')).toHaveValue('10:30');await expect(task.locator('[name=note]')).toHaveValue('À apporter : mon dossier');
 await task.locator('[data-action=journey-task-done]').press('Space');await expect(task).toHaveCount(0);await page.locator('[data-action=journey-filter][data-value=todo]').click();await expect(task).toBeVisible();await expect(task.locator('.j-status')).toHaveText('Rendez-vous fixé');
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('miette-notebook-v1')).journey.tasks.echo2);expect(saved.status).toBe('scheduled');expect(saved.date).toBe(appointment);expect(saved.note).toBe('À apporter : mon dossier');
});

test('An upcoming step opens its explanation on the home page, then targets that appointment when requested',async({page})=>{
 const notebook=N.empty();notebook.name='Poilon';notebook.journey.profile={...P.empty().profile,consent:true,date:P.add(P.today(),-100)};for(const task of P.timeline(notebook.journey))if(task.id!=='prevention')notebook.journey.tasks[task.id]={status:'done'};
 await local(page);await page.addInitScript(n=>localStorage.setItem('miette-notebook-v1',JSON.stringify(n)),notebook);await page.setViewportSize({width:390,height:844});await page.goto('/#accueil');
 const card=page.locator('.j-next-card[data-id=prevention]');await card.click();await expect(page).toHaveURL(/#accueil$/);const dialog=page.locator('#detail-dialog');await expect(dialog).toBeVisible();await expect(dialog.locator('#dialog-title')).toHaveText('Le bilan prénatal de prévention');await expect(dialog).toContainText('échange avec une sage-femme');await expect(dialog).toContainText('Si possible avant 24 SA');await expect(dialog.getByRole('link',{name:'Lire les informations officielles'})).toHaveAttribute('href',P.sources.follow);
 const a=await new AxeBuilder({page}).include('#detail-dialog').analyze();expect(a.violations.filter(v=>['serious','critical'].includes(v.impact))).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.keyboard.press('Escape');await expect(dialog).not.toBeVisible();await expect(card).toBeFocused();await card.press('Enter');await expect(dialog).toBeVisible();await dialog.getByRole('button',{name:'Noter une date ou une question'}).click();await expect(page).toHaveURL(/#calendrier$/);await expect(dialog).not.toBeVisible();await expect(page.locator('[data-task=prevention] details')).toHaveAttribute('open','');await expect(page.locator('#date-prevention')).toBeFocused();
});

test('The checklist and home share the logical order and each compact row unfolds explanations and editable notes',async({page})=>{
 const notebook=N.empty();notebook.journey.profile={...P.empty().profile,consent:true,date:P.add(P.today(),-40)};
 await local(page);await page.addInitScript(n=>localStorage.setItem('miette-notebook-v1',JSON.stringify(n)),notebook);await page.setViewportSize({width:390,height:844});await page.goto('/#accueil');
 await expect(page.locator('.j-next-card').first()).toHaveAttribute('data-id','first');await page.goto('/#calendrier');const rows=page.locator('[data-task]');await expect(rows.first()).toHaveAttribute('data-task','first');
 const ids=await rows.evaluateAll(els=>els.map(el=>el.dataset.task));expect(ids.indexOf('first')).toBeLessThan(ids.indexOf('declaration'));expect(ids.indexOf('declaration')).toBeLessThan(ids.indexOf('prevention'));
 const first=rows.first();await expect(first.locator('.j-task-body')).not.toBeVisible();expect((await first.boundingBox()).height).toBeLessThan(190);await first.locator('summary').focus();await page.keyboard.press('Enter');await expect(first.locator('.j-step-guide')).toBeVisible();await expect(first).toContainText('Antécédents, allergies, traitements');await expect(first).toContainText('À préparer');await expect(first.locator('[name=note]')).toBeVisible();
 await page.evaluate(()=>Promise.allSettled(document.getAnimations().map(a=>a.finished)));const a=await new AxeBuilder({page}).analyze();expect(a.violations.filter(v=>['serious','critical'].includes(v.impact))).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await first.locator('[data-action=journey-task-done]').click();await expect(page.locator('[data-task=first]')).toHaveCount(0);await page.goto('/#accueil');await expect(page.locator('.j-next-card').first()).toHaveAttribute('data-id','blood-first');
});
