const {test,expect}=require('@playwright/test'),AxeBuilder=require('@axe-core/playwright').default;
const {operation}=require('../server/tonight.cjs'),{memoryTonight}=require('./tonight-fixture.cjs');
async function mock(page,repo,owner='browser-owner',access={paid:false}) {
 await page.route('**/api/tonight',async route=>{try{const body=route.request().postDataJSON();const result=await operation(body,{repo,owner:typeof owner==='function'?owner():owner,paid:access.paid});await route.fulfill({json:result});}catch(e){await route.fulfill({status:e.status||503,json:{error:e.message,...e.details}});}});
 await page.route('**/api/config',r=>r.fulfill({json:{accounts:false}}));
 await page.route('**/api/billing',r=>r.fulfill({json:{configured:true,access:{active:access.paid},owner:null}}));
}
async function choose(page){await page.goto('/#cesoir');await page.locator('#tonight-form [type="submit"]').click();await expect(page.locator('.dinner-choice')).toHaveCount(3);await page.locator('[data-action="tonight-choose"]').first().click();await expect(page.locator('.dinner-sheet')).toBeVisible();}
for(const width of [390,1440])test(`Dinner choices, shared groceries and revocation work across two browsers at ${width}px`,async({page,browser})=>{
 const repo=memoryTonight();await page.setViewportSize({width,height:900});await mock(page,repo);await choose(page);
 await page.locator('[data-action="tonight-relay"]').click();await page.locator('[data-action="tonight-link"]').click();const link=await page.locator('#dinner-link').inputValue();expect(new URL(link).pathname).toBe('/relais/');expect(new URL(link).search).toBe('');
 const context=await browser.newContext({viewport:{width:390,height:844}});try{const recipient=await context.newPage();await mock(recipient,repo,'stranger');await recipient.goto(link);await expect(recipient.locator('.dinner-sheet')).toBeVisible();await recipient.locator('[data-dinner-item="0"]').check();await expect.poll(()=>[...repo.meals.values()][0].checked[0]).toBe(true);await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await expect(page.locator('[data-dinner-item="0"]')).toBeChecked();
 await recipient.locator('.dinner-method > summary').click();await recipient.locator('[data-dinner-step="0"]').check();await expect.poll(()=>[...repo.meals.values()][0].checked['step:0']).toBe(true);await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await page.locator('.dinner-method > summary').click();await expect(page.locator('[data-dinner-step="0"]')).toBeChecked();await page.locator('[data-dinner-item="1"]').check();await recipient.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await expect(recipient.locator('[data-dinner-item="1"]')).toBeChecked();await recipient.locator('[data-dinner-status="done"]').click();await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await expect(page.locator('[data-dinner-heading]')).toHaveText('Le dîner est prêt.');
 await expect(page.locator('#dinner-link')).toHaveValue(link);await page.locator('[data-action="tonight-revoke"]').click();await recipient.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await expect(recipient.locator('#relay-feedback')).toContainText('désactivé');await expect(recipient.locator('.dinner-sheet')).toHaveCount(0);await page.reload();await expect(page.locator('.dinner-sheet')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 }finally{await context.close();}
});
test('First complete dinner stays readable behind the next-dinner paywall; a paid member can continue',async({page})=>{
 const repo=memoryTonight(),access={paid:false};await mock(page,repo,'browser-owner',access);await choose(page);await page.locator('[data-action="tonight-new"]').click();await page.locator('#tonight-form [type="submit"]').click();await page.locator('[data-action="tonight-choose"]').first().click();await expect(page.getByRole('heading',{name:'Et les prochains soirs ?'})).toBeVisible();await page.locator('[data-action="tonight-back"]').click();await expect(page.locator('.dinner-sheet')).toBeVisible();access.paid=true;await page.locator('[data-action="tonight-new"]').click();await page.locator('#tonight-form [type="submit"]').click();await page.locator('[data-action="tonight-choose"]').first().click();await expect(page.locator('.dinner-sheet')).toBeVisible();expect(repo.meals.size).toBe(2);
});
test('Preferences persist, skipped ideas change, empty results are actionable, and mobile controls are accessible',async({page})=>{
 const repo=memoryTonight();await mock(page,repo);await page.setViewportSize({width:320,height:850});await page.goto('/#cesoir');await page.locator('[name="servings"]').selectOption('4');await page.locator('[name="vegetarian"]').check();await page.getByText('Utiliser ce que j’ai',{exact:true}).click();await page.locator('[name="pantry"][value="zucchini"]').check();await page.locator('#tonight-form [type="submit"]').click();await expect(page.locator('.dinner-choice')).toHaveCount(3);const first=await page.locator('[data-action="tonight-choose"]').evaluateAll(els=>els.map(el=>el.dataset.id));await page.locator('[data-action="tonight-more"]').click();await expect.poll(()=>page.locator('[data-action="tonight-choose"]').first().getAttribute('data-id')).not.toBe(first[0]);const second=await page.locator('[data-action="tonight-choose"]').evaluateAll(els=>els.map(el=>el.dataset.id));expect(second.every(x=>!first.includes(x))).toBe(true);await page.locator('[data-action="tonight-preferences"]').click();await expect(page.locator('[name="servings"]')).toHaveValue('4');await expect(page.locator('[name="pantry"][value="zucchini"]')).toBeChecked();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const audit=await new AxeBuilder({page}).analyze();expect(audit.violations.filter(v=>['serious','critical'].includes(v.impact))).toEqual([]);
 await page.getByText('Quelque chose qui ne passe pas aujourd’hui ?',{exact:true}).click();await page.locator('#dinner-avoid').fill('a, e, i, o, u');await page.locator('#tonight-form [type="submit"]').click();await expect(page.getByRole('heading',{name:'On ajuste un peu ?'})).toBeVisible();await expect(page.locator('[data-action="tonight-preferences"]')).toBeVisible();
});
test('Shared link errors stay private and dinners can be explicitly erased',async({page})=>{
 const repo=memoryTonight();await mock(page,repo);await page.goto('/relais/#missing');await expect(page.locator('#relay-feedback')).toContainText('Il manque');await choose(page);await page.locator('[data-action="tonight-erase"]').click();await page.locator('[data-action="tonight-erase-confirm"]').click();await expect(page.locator('#tonight-form')).toBeVisible();expect(repo.meals.size).toBe(0);await expect(page.locator('#tonight-page')).toContainText('premier essai a été utilisé');
});

test('Switching account immediately removes the previous dinner from the screen and preserves the guest copy',async({page})=>{
 const repo=memoryTonight();let owner='guest';await mock(page,repo,()=>owner);await choose(page);const title=await page.locator('.dinner-sheet h2').textContent();owner='bob';
 await page.evaluate(()=>{MietteCloud.state.user={id:'bob',email:'bob@example.test'};window.dispatchEvent(new CustomEvent('miette:cloud'));});
 await expect(page.locator('.dinner-sheet')).toHaveCount(0);await expect(page.locator('#tonight-form')).toBeVisible();await expect(page.locator('#tonight-page')).not.toContainText(title);
 owner='guest';await page.evaluate(()=>{MietteCloud.state.user=null;window.dispatchEvent(new CustomEvent('miette:cloud'));});await expect(page.locator('.dinner-sheet h2')).toHaveText(title);
});
