'use strict';
const I=(name,quantity,unit='g')=>({name,quantity,unit});
const family=(id,label,cuisine,image,time,ingredients,equipment,steps,check,tip)=>({id,label,cuisine,collection:'douceurs',image,time,ingredients,equipment,steps,check,tip,sweet:true});
const families=[
 family('porridge-fruits','Porridge aux fruits fondants','Royaume-Uni','porridge',35,[I('Flocons d’avoine',80),I('Lait UHT',300,'ml'),I('Eau pour les fruits',40,'ml')],['Casserole','Petite poêle','Spatule'],
 ['Versez les fruits préparés et l’eau pour les fruits dans la petite poêle. Couvrez et faites compoter 10 à 15 minutes à feu doux, en remuant ; les fruits fermes doivent pouvoir s’écraser à la fourchette.','Versez le lait et les flocons dans une casserole. Faites frémir doucement 5 à 8 minutes, selon les flocons, en remuant au fond. Répartissez dans les bols et ajoutez les fruits cuits.'],
 'Les flocons sont tendres, le porridge encore souple.','Ajoutez un peu d’eau chaude si les flocons ont absorbé tout le lait.'),
 family('avoine-four','Avoine au four','États-Unis','recipes/muffins',55,[I('Flocons d’avoine',80),I('Lait UHT',160,'ml'),I('Œuf',1,''),I('Sirop d’érable',15,'ml')],['Saladier','Fouet','Plat de 18 cm','Four'],
 ['Préchauffez le four à 180 °C. Battez l’œuf avec le lait et le sirop d’érable, puis incorporez les flocons et les fruits préparés. Ne goûtez pas la préparation crue.','Versez dans le plat et cuisez 30 à 35 minutes. Le milieu doit être pris, sans liquide d’œuf ; vérifiez avec une lame propre et prolongez si nécessaire. Laissez reposer 5 minutes.'],
 'Le centre est ferme et humide, sans appareil liquide.','Une couche de moins de 4 cm permet au milieu de cuire régulièrement.'),
 family('pancakes-fruits','Pancakes & fruits compotés','États-Unis','recipes/pancakes',45,[I('Farine de blé',100),I('Lait UHT',120,'ml'),I('Œuf',1,''),I('Levure chimique',4),I('Huile de colza',2,'c. à café'),I('Eau pour les fruits',40,'ml')],['Casserole','Saladier','Fouet','Poêle antiadhésive'],
 ['Cuisez les fruits préparés avec l’eau pour les fruits à couvert 10 à 15 minutes à feu doux, jusqu’à ce qu’ils soient tendres. Gardez-les pour garnir les pancakes.','Mélangez la farine et la levure. Battez l’œuf avec le lait, incorporez aux poudres jusqu’à disparition de la farine sèche. Ne goûtez pas la pâte crue.','Huilez légèrement la poêle avec l’huile de colza. Versez six petites portions de pâte en plusieurs fournées. Cuisez à feu moyen-doux environ 2 à 3 minutes par face ; ouvrez le premier pancake pour vérifier que le centre est cuit, sans pâte humide crue. Servez avec les fruits.'],
 'Le centre des pancakes est pris, sans traînée de pâte crue.','De petits pancakes cuisent plus facilement à cœur que des pancakes épais.'),
 family('muffins-fruits','Petits muffins aux fruits','États-Unis','recipes/muffins',55,[I('Farine de blé',120),I('Œuf',1,''),I('Lait UHT',60,'ml'),I('Huile de colza',25,'ml'),I('Sucre',30),I('Levure chimique',5)],['Deux saladiers','Fouet','Six moules à muffins','Four'],
 ['Préchauffez le four à 180 °C. Mélangez farine et levure. Dans l’autre saladier, battez l’œuf avec le sucre, le lait et l’huile de colza. Réunissez les deux mélanges sans trop travailler.','Incorporez les fruits préparés, bien égouttés. Répartissez dans six moules, remplis au maximum aux trois quarts ; utilisez un moule supplémentaire si nécessaire. Cuisez 25 à 30 minutes.','Piquez le centre d’un muffin avec une lame propre : aucune pâte crue ne doit y adhérer. Prolongez la cuisson si nécessaire, puis attendez 10 minutes avant de démouler. Ne goûtez pas la pâte crue.'],
 'Le dessus reprend sa forme sous une légère pression ; le centre est cuit.','Égouttez bien les fruits lavés pour ne pas détremper la pâte.'),
 family('cake-fruits','Petit cake aux fruits','France','recipes/muffins',70,[I('Farine de blé',130),I('Œuf',2,''),I('Yaourt nature au lait pasteurisé',60),I('Huile de colza',30,'ml'),I('Sucre',35),I('Levure chimique',5)],['Saladier','Fouet','Moule à cake de 20 cm','Four'],
 ['Préchauffez le four à 180 °C. Battez les œufs avec le sucre, le yaourt et l’huile. Incorporez la farine et la levure, puis les fruits préparés et bien égouttés. Ne goûtez pas la pâte crue.','Versez dans le moule chemisé et cuisez 40 à 45 minutes. Piquez au milieu : une lame doit ressortir sans pâte crue. Si le dessus colore trop avant que le cœur soit cuit, couvrez et poursuivez. Laissez reposer 10 minutes avant de démouler.'],
 'La lame ressort sans pâte crue, même au centre du cake.','Le jus d’un fruit peut mouiller la lame ; ce qui doit disparaître est la pâte collante non cuite.'),
 family('crumble-fruits','Crumble aux deux fruits','Royaume-Uni','recipes/cookies',50,[I('Farine de blé',50),I('Flocons d’avoine',30),I('Beurre pasteurisé',35),I('Sucre',25)],['Saladier','Plat de 18 cm','Four'],
 ['Préchauffez le four à 180 °C. Répartissez les fruits préparés au fond du plat. Mélangez farine, flocons et sucre ; ajoutez le beurre froid en dés et frottez du bout des doigts pour former des miettes.','Répartissez les miettes sans les tasser sur les fruits. Cuisez 30 à 35 minutes, jusqu’à ce que le dessus soit doré et les fruits tendres. Ne goûtez pas le mélange contenant de la farine crue.'],
 'Les fruits bouillonnent légèrement sur les bords et les miettes sont cuites.','Laissez de petits espaces entre les miettes pour que la vapeur s’échappe.'),
 family('clafoutis-fruits','Clafoutis aux fruits','France','recipes/waffles',60,[I('Œuf',2,''),I('Farine de blé',40),I('Lait UHT',160,'ml'),I('Sucre',25)],['Saladier','Fouet','Plat de 18 cm','Four'],
 ['Préchauffez le four à 180 °C. Battez les œufs avec le sucre. Incorporez la farine, puis versez progressivement le lait en fouettant pour éviter les grumeaux. Ne goûtez pas la pâte crue.','Répartissez les fruits préparés dans le plat chemisé, versez l’appareil et cuisez 35 à 40 minutes. Le milieu doit être pris, sans mélange liquide ; vérifiez au centre et prolongez si nécessaire. Reposez 5 minutes avant de servir.'],
 'Le centre est pris ; il peut rester souple mais ne doit pas être liquide.','Utilisez un petit plat assez large pour ne pas créer une couche trop épaisse.'),
 family('compote-duo','Compotée de fruits à la vanille','France','porridge',35,[I('Eau pour les fruits',50,'ml'),I('Vanille en poudre sans alcool',0.25,'c. à café')],['Casserole avec couvercle','Fourchette'],
 ['Placez les fruits préparés dans la casserole avec l’eau pour les fruits et la vanille. Couvrez et faites cuire à feu doux 15 à 20 minutes en remuant régulièrement. Ajoutez une cuillerée d’eau si le fond sèche.','Vérifiez que les morceaux les plus fermes s’écrasent à la fourchette. Écrasez grossièrement, ou poursuivez quelques minutes sans couvercle si le mélange est trop liquide. Servez tiède.'],
 'Tous les fruits sont tendres, sans morceau dur.','Le sucre naturellement présent dans les fruits suffit ; goûtez après cuisson.'),
 family('riz-lait-fruits','Riz au lait & fruits fondants','Europe','porridge',60,[I('Riz rond sec',70),I('Lait UHT',450,'ml'),I('Sucre',20),I('Eau pour les fruits',40,'ml')],['Casserole à fond épais','Petite casserole','Spatule'],
 ['Versez le riz et le lait dans la casserole à fond épais. Portez à petits frémissements, puis cuisez à feu très doux 30 à 40 minutes, selon le riz, en remuant souvent au fond. Le lait ne doit pas déborder.','Pendant cette cuisson, faites compoter les fruits préparés avec l’eau pour les fruits dans la petite casserole, à couvert, 10 à 15 minutes jusqu’à tendreté.','Quand le riz est tendre, ajoutez le sucre et remuez 2 minutes. Répartissez dans deux bols, ajoutez les fruits et servez tiède. Si le riz est trop épais, détendez avec un peu d’eau chaude.'],
 'Le grain de riz est tendre à cœur et baigne encore dans une crème souple.','Le riz continue à absorber le lait après cuisson : arrêtez avant qu’il soit sec.')
];
module.exports={families};
