'use strict';
const fs = require('node:fs');
const path = require('node:path');
const D = require('../js/data.js');
const { freeIDs } = require('../server/recipe-access.cjs');
const routes = require('../js/seo-routes.js');
const ORIGIN = 'https://poum.app';
const HOME_TITLE = 'Que peut-on manger enceinte ? Aliments et recettes | Poum';
const criticalCSS = fs.readFileSync(path.join(__dirname,'../assets/seo.css'),'utf8') + ['dm-sans','lora'].map(name => fs.readFileSync(path.join(__dirname,'../assets/fonts/'+name+'.css'),'utf8').replace(/url\(([^)]+)\)/g, 'url(/assets/fonts/$1)')).join('');
const HOME_DESCRIPTION = 'Que manger enceinte ? Consultez 360 aliments : ce qui est possible, à éviter ou à limiter, avec les précautions, les sources et des recettes pour la grossesse.';
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const absolute = url => ORIGIN + url;
const ld = value => JSON.stringify(value).replace(/</g, '\\u003c');
const organization = { '@type': 'Organization', '@id': ORIGIN + '/#organization', name: 'Poum', url: ORIGIN + '/', logo: ORIGIN + '/assets/brand/icon-512.png' };
const categories = [
  { id:'produce', slug:'fruits-legumes', title:'Fruits et légumes enceinte : lavage, cuisson et précautions', intro:'Ananas, patate douce, salade ou avocat : retrouvez la préparation de chaque fruit et légume. Le lavage, la découpe et la conservation font partie de la réponse.', profiles:['produce','cookedProduce','sprouts'] },
  { id:'dairy', slug:'fromages-produits-laitiers', title:'Quels fromages peut-on manger enceinte ?', intro:'Le nom du fromage, le traitement du lait et la préparation comptent ensemble. Retrouvez les différences entre mozzarella, brie, comté et autres produits laitiers.', profiles:['dairy','hardCheese','softCheese'] },
  { id:'protein', slug:'viandes-oeufs-charcuterie', title:'Viande, œufs et charcuterie enceinte : que choisir ?', intro:'Cuisson à cœur, préparations crues et charcuteries froides : chaque fiche précise la forme concernée et ce qui change dans une recette.', profiles:['meat','eggs','deli'] },
  { id:'fish', slug:'poissons-fruits-de-mer', title:'Poissons et fruits de mer enceinte : cuisson et espèces', intro:'Saumon frais, saumon fumé, thon ou crevettes ne se jugent pas de la même façon. Consultez les précautions de cuisson et celles liées à l’espèce.', profiles:['fish','rawFish','mercury'] },
  { id:'seasoning', slug:'epices-herbes-aromates', title:'Épices et herbes aromatiques enceinte : quels usages ?', intro:'Une épice dans une recette, une infusion et un complément concentré sont des usages différents. Les fiches distinguent les formes culinaires et leurs précautions.', profiles:['spice','spicy','spiceBlend'] },
  { id:'pantry', slug:'epicerie-feculents-condiments', title:'Féculents, sauces et épicerie pendant la grossesse', intro:'Pâtes, riz, légumineuses, sauces et desserts : retrouvez les ingrédients du placard, leurs conditions de préparation et les points à lire sur l’emballage.', profiles:['grains','pantry'] },
  { id:'drinks', slug:'boissons', title:'Que boire enceinte ? Café, thé et autres boissons', intro:'Retrouvez les repères par boisson. La présence d’alcool, la caféine et la composition des infusions peuvent modifier la réponse.', profiles:['caffeine','alcohol'] }
];
const catPath = c => '/alimentation-grossesse/' + c.slug + '/';
function link(url, text, cls = '') { return `<a${cls ? ` class="${cls}"` : ''} href="${esc(url)}">${esc(text)}</a>`; }
function sources(ids) {
  return `<ul class="seo-sources">${[...new Set(ids)].map(id => { const s=D.sources[id]; if(!s) throw Error('Unknown source: '+id); return `<li><a href="${esc(s.url)}" rel="noopener noreferrer" target="_blank">${esc(s.name)} — ${esc(s.title)}</a></li>`; }).join('')}</ul>`;
}
function evidenceNote(food) { return food.evidence.basis === 'specific' ? 'Cet aliment, ce type de produit ou cette préparation est cité dans les références ci-dessous.' : 'Cette fiche applique les recommandations générales à cette famille d’aliments. Les sources ne citent pas nécessairement cet aliment individuellement.'; }
function status(food) { return `<span class="seo-status ${food.status}">${esc(D.statuses[food.status].label)}</span>`; }
function foodList(foods, {reasons=false}={}) {
  return `<ul class="seo-food-list">${foods.map(f=>`<li data-food-name="${esc(f.name+' '+(f.aliases||''))}"><a href="${routes.food(f)}"><strong>${esc(f.name)}</strong>${status(f)}</a><p>${esc(reasons?f.reason:f.summary)}</p></li>`).join('')}</ul>`;
}
function recipeList(recipes) { return `<ul class="seo-recipes">${recipes.map(r=>`<li><a href="${routes.recipe(r)}"><img src="/assets/${esc(r.image)}.jpg" alt="" width="640" height="420" loading="lazy" decoding="async"><h3>${esc(r.title)}</h3></a><p>${r.time} min · ${r.servings} personnes${r.vegetarian?' · Végétarien':''}</p></li>`).join('')}</ul>`; }
function caution() { return '<p class="seo-caution">Ces repères généraux ne remplacent pas les conseils de votre sage-femme ou médecin. La préparation, la conservation, les allergies et votre situation personnelle restent à prendre en compte.</p>'; }
function attribution() { return `<p class="seo-byline">Synthèse éditoriale : ${link('/sources-et-methode/','Poum')} · Repères du guide consultés le <time datetime="${D.reviewedISO}">${esc(D.reviewed)}</time>.</p>`; }
function header() { return `<header class="seo-header"><a class="seo-brand" href="/"><img src="/assets/brand/mark.svg" alt="" width="36" height="36"><span>poum<small>Ta grossesse, à ton rythme.</small></span></a><nav aria-label="Navigation principale">${link('/aliments/','Les aliments')}${link('/recettes-grossesse/','Recettes')}${link('/#plus','Poum Plus')}</nav></header>`; }
function footer() { return `<footer class="seo-footer"><p>Poum · Alimentation et grossesse</p><nav aria-label="Informations">${link('/alimentation-grossesse/','Le guide')}${link('/sources-et-methode/','Sources et méthode')}${link('/#confidentialite','Vos données')}${link('/#profil','Mon compte')}</nav></footer>`; }
function cta() { return `<aside class="seo-cta"><div><h2>Et ce soir, on mange quoi ?</h2><p>Des recettes avec leurs précautions grossesse, des menus à ajuster et les courses qui vont avec.</p></div>${link('/#plus','Découvrir Poum Plus','seo-button')}</aside>`; }
function profileSections(ids) { return ids.map(id=>{const p=D.profiles[id];if(!p)throw Error('Unknown profile '+id);return `<section><h2>${esc(p.title)}</h2><p>${esc(p.mechanism)}</p><p>${esc(p.condition)}</p>${sources(p.sources)}</section>`;}).join(''); }
function breadcrumbs(items) { return `<nav class="seo-breadcrumb" aria-label="Fil d’Ariane"><ol>${items.map((x,i)=>`<li>${i===items.length-1?`<span aria-current="page">${esc(x[0])}</span>`:link(x[1],x[0])}</li>`).join('')}</ol></nav>`; }
function baseSchema(url,title,description,crumbs,type='WebPage') {
  return [{...organization},{'@type':type,'@id':absolute(url)+'#page',url:absolute(url),name:title,description,inLanguage:'fr-FR',isPartOf:{'@id':ORIGIN+'/#website'},publisher:{'@id':ORIGIN+'/#organization'},isAccessibleForFree:true}, {'@type':'BreadcrumbList',itemListElement:crumbs.map((c,i)=>({'@type':'ListItem',position:i+1,name:c[0],item:absolute(c[1])}))}];
}
function page({url,title,description,body,crumbs,type='WebPage',schema=[],image}) {
  const picture=absolute(image||'/assets/brand/table-maternite-v4.png');
  const graph=baseSchema(url,title,description,crumbs,type).concat(schema);
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} | Poum</title><meta name="description" content="${esc(description)}"><meta name="robots" content="index,follow,max-image-preview:large"><meta name="theme-color" content="#542b43"><link rel="canonical" href="${absolute(url)}"><meta property="og:type" content="${schema.some(x=>x['@type']==='Recipe')?'article':'website'}"><meta property="og:locale" content="fr_FR"><meta property="og:site_name" content="Poum"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${absolute(url)}"><meta property="og:image" content="${picture}"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/assets/brand/mark.svg" type="image/svg+xml"><style>${criticalCSS}</style><script type="application/ld+json">${ld({'@context':'https://schema.org','@graph':graph})}</script></head><body class="seo-page"><a class="seo-skip" href="#contenu">Aller au contenu</a>${header()}<main id="contenu" class="seo-main">${breadcrumbs(crumbs)}${body}</main>${footer()}</body></html>`;
}
function foodPage(f) {
  const cat=categories.find(c=>c.id===f.category), p=D.profiles[f.evidence.profile],url=routes.food(f);
  const related=D.foods.filter(x=>x.id!==f.id&&x.category===f.category).sort((a,b)=>(b.group===f.group)-(a.group===f.group)||a.name.localeCompare(b.name,'fr')).slice(0,6);
  const recipes=D.recipes.filter(r=>freeIDs.has(r.id)&&r.foods.includes(f.id)).slice(0,3);
  const description=`${f.name} pendant la grossesse : ${D.statuses[f.status].label.toLowerCase()}. ${f.summary}`;
  const body=`<article><p class="seo-kicker">Alimentation pendant la grossesse</p><h1>${esc(f.name)} enceinte : peut-on en manger ?</h1><div class="seo-answer">${status(f)}<p>${esc(f.evidence.why)}</p></div>${attribution()}<section><h2>Pourquoi cette recommandation ?</h2><h3>${esc(p.title)}</h3><p>${esc(p.mechanism)}</p>${sources([...f.evidence.sources,...p.sources])}<p class="seo-note">${esc(evidenceNote(f))}</p></section><section><h2>Ce qui change la réponse</h2><p>${esc(p.condition)}</p>${f.evidence.note?`<p>${esc(f.evidence.note)}</p>`:''}</section><section><h2>Comment le préparer pendant la grossesse ?</h2><ul class="seo-steps">${f.preparation.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>${sources(f.sources)}</section>${caution()}<p>${link('/#aliments?q='+encodeURIComponent(f.name),'Retrouver cet aliment dans mon carnet','seo-button secondary')}</p></article>${recipes.length?`<section><h2>Des idées pour le cuisiner</h2>${recipeList(recipes)}</section>`:''}<section><h2>À consulter aussi</h2>${foodList(related)}<p>${link(catPath(cat),'Tous les aliments de cette famille')}</p></section>${cta()}`;
  return {url,html:page({url,title:`${f.name} enceinte : précautions et préparation`,description,body,crumbs:[['Accueil','/'],['Aliments','/aliments/'],[D.categories.find(c=>c.id===f.category).label,catPath(cat)],[f.name,url]],schema:[{'@type':'WebPage','@id':absolute(url)+'#page',about:{'@type':'Thing',name:f.name},author:{'@id':ORIGIN+'/#organization'},citation:[...new Set([...f.sources,...p.sources])].map(id=>D.sources[id].url)}]})};
}
function recipePage(r) {
  if(!freeIDs.has(r.id)) throw Error('Premium recipes must not be published by SEO');
  const url=routes.recipe(r),title=r.title+' : recette pour la grossesse';
  const description=`${r.title} : une recette pour ${r.servings} personnes, en ${r.time} minutes, avec ingrédients, étapes, allergènes et précautions pendant la grossesse.`;
  const ingredients=r.ingredients.map(i=>`${new Intl.NumberFormat('fr-FR').format(i.quantity)} ${i.unit} ${i.name}`.replace(/\s+/g,' ').trim());
  const schema={'@type':'Recipe','@id':absolute(url)+'#recipe',name:r.title,description:r.subtitle,image:[absolute('/assets/'+r.image+'.jpg')],author:{'@id':ORIGIN+'/#organization'},totalTime:'PT'+r.time+'M',recipeYield:r.servings+' personnes',recipeIngredient:ingredients,recipeInstructions:r.steps.map((text,i)=>({'@type':'HowToStep',text,url:absolute(url)+'#etape-'+(i+1)})),isAccessibleForFree:true};
  const body=`<article><p class="seo-kicker">Recette gratuite · ${r.time} minutes</p><h1>${esc(r.title)}</h1><p class="seo-intro">${esc(r.subtitle)} Pour ${r.servings} personnes${r.vegetarian?', végétarien':''}.</p><img class="seo-recipe-photo" src="/assets/${esc(r.image)}.jpg" width="960" height="630" alt="Photo d’inspiration : ${esc(r.title)}" fetchpriority="high"><p class="seo-note">Photo d’inspiration ; les ingrédients écrits font référence.</p><section><h2>Les ingrédients</h2><ul class="seo-ingredients">${ingredients.map(i=>`<li>${esc(i)}</li>`).join('')}</ul><p><strong>Allergènes :</strong> ${esc(r.allergens)}</p></section><section><h2>La préparation</h2><ol class="seo-steps">${r.steps.map((t,i)=>`<li id="etape-${i+1}">${esc(t)}</li>`).join('')}</ol></section><section class="seo-answer"><h2>Les précautions pendant la grossesse</h2><p>${esc(r.safety)}</p></section>${sources(r.sources||['spf','toxo'])}<p class="seo-note">Les temps de cuisson sont indicatifs. Vérifiez la cuisson complète et suivez vos consignes médicales.</p><p>${link('/#recettes?q='+encodeURIComponent(r.title),'Adapter les portions et préparer mes courses','seo-button')}</p></article><section><h2>Les aliments de cette recette</h2>${foodList(r.foods.map(id=>D.foods.find(f=>f.id===id)).filter(Boolean))}</section>${cta()}`;
  return {url,html:page({url,title,description,body,image:'/assets/'+r.image+'.jpg',crumbs:[['Accueil','/'],['Recettes grossesse','/recettes-grossesse/'],[r.title,url]],schema:[schema]})};
}
function homeContent() {
  const popular=['mozzarella','pineapple','sweet-potato','brie','salmon','tuna','eggs','avocado'].map(id=>D.foods.find(f=>f.id===id)).filter(Boolean);
  return `${header()}<main id="main" class="seo-main"><p class="seo-kicker">À table pendant la grossesse</p><h1>Enceinte, je peux en manger ?</h1><p class="seo-intro">Les aliments, les précautions et les recettes pour manger enceinte. Trouvez une réponse expliquée et sourcée, avec la préparation qui change la réponse.</p><p>${link('/aliments/','Chercher parmi les 360 aliments','seo-button')}</p><section><h2>Les aliments à connaître</h2>${foodList(popular)}</section><section><h2>Que peut-on manger pendant la grossesse ?</h2><p>Les réponses dépendent de l’aliment, de sa forme et de sa préparation. Le guide distingue les aliments compatibles dans les conditions indiquées, ceux qui demandent des précautions, ceux à limiter et ceux à éviter sous la forme décrite.</p><div class="seo-hub-links">${categories.map(c=>link(catPath(c),D.categories.find(x=>x.id===c.id).label)).join('')}</div><p>${link('/alimentation-grossesse/','Comprendre les précautions alimentaires')}${' · '}${link('/aliments-a-eviter-enceinte/','Les aliments à éviter enceinte')}</p></section><section><h2>Des recettes à cuisiner enceinte</h2>${recipeList(D.recipes.filter(r=>freeIDs.has(r.id)).slice(0,3))}<p>${link('/recettes-grossesse/','Toutes les recettes gratuites')}</p></section>${caution()}${cta()}</main>${footer()}`;
}
function collectPages() {
  const pages=[];
  const add=(url,title,description,body,extra={})=>pages.push({url,html:page({url,title,description,body,crumbs:[['Accueil','/'],[title,url]],...extra})});
  const intro=(title,description)=>`<h1>${esc(title)}</h1><p class="seo-intro">${esc(description)}</p>`;
  const categoryLinks=`<div class="seo-hub-links">${categories.map(c=>link(catPath(c),D.categories.find(x=>x.id===c.id).label)).join('')}</div>`;
  add('/aliments/','Quels aliments peut-on manger enceinte ? La liste de A à Z','360 aliments à retrouver par famille : précautions, cuisson, conservation et sources pour chaque fiche.',intro('Quels aliments peut-on manger enceinte ?','Choisissez un aliment pour lire les conditions de préparation et les sources. Une indication « compatible » n’est pas une garantie sans ces conditions.')+`<form class="seo-search" hidden><label for="food-search">Rechercher un aliment</label><input id="food-search" type="search" placeholder="Mozzarella, ananas, patate douce…" autocomplete="off"><p role="status" aria-live="polite"></p></form><script src="/assets/guide-search.js" defer></script>`+categoryLinks+`<p>${link('/aliments-a-eviter-enceinte/','À éviter')}${' · '}${link('/aliments-a-limiter-enceinte/','À limiter')}${' · '}${link('/#aliments','Rechercher dans l’application')}</p>`+categories.map(c=>`<section id="${c.slug}" data-food-section><h2>${link(catPath(c),D.categories.find(x=>x.id===c.id).label)}</h2>${foodList(D.foods.filter(f=>f.category===c.id).sort((a,b)=>a.name.localeCompare(b.name,'fr')))}</section>`).join('')+caution(),{type:'CollectionPage'});
  for(const c of categories) {
    const url=catPath(c),foods=D.foods.filter(f=>f.category===c.id).sort((a,b)=>a.name.localeCompare(b.name,'fr'));
    add(url,c.title,c.intro,intro(c.title,c.intro)+`<nav class="seo-toc" aria-label="Dans cette page">${link('#liste','Les aliments de cette famille')}${link('#reperes','Comprendre les précautions')}</nav><section id="liste"><h2>Les fiches aliment par aliment</h2>${foodList(foods)}</section><div id="reperes">${profileSections(c.profiles)}</div>`+attribution()+caution()+cta(),{type:'CollectionPage',crumbs:[['Accueil','/'],['Alimentation grossesse','/alimentation-grossesse/'],[D.categories.find(x=>x.id===c.id).label,url]]});
  }
  for(const [statusKey,url,title,description] of [
    ['avoid','/aliments-a-eviter-enceinte/','Quels aliments éviter enceinte ?','La liste des aliments à éviter pendant la grossesse, sous la forme décrite : raisons, alternatives et précautions de cuisson.'],
    ['limit','/aliments-a-limiter-enceinte/','Quels aliments limiter enceinte ?','Caféine, poissons et autres aliments à limiter pendant la grossesse : retrouvez les raisons et les repères propres à chaque fiche.']
  ])add(url,title,description,intro(title,description)+'<p>Le conseil porte sur la forme décrite dans la fiche. Une autre préparation peut modifier certains risques, tandis que la cuisson ne supprime pas tous les contaminants. Ouvrez la fiche avant de choisir une alternative.</p>'+foodList(D.foods.filter(f=>f.status===statusKey),{reasons:true})+caution()+`<p>${link('/aliments/','Revenir à tous les aliments')}</p>`,{type:'CollectionPage'});
  add('/alimentation-grossesse/','Alimentation pendant la grossesse : comment se repérer ?', 'Que manger enceinte, quels aliments éviter et comment les préparer ? Un guide pour comprendre lavage, cuisson, conservation et choix des produits.',intro('Que manger enceinte, au quotidien ?','Devant un menu ou dans un rayon, on a surtout besoin de savoir quoi choisir et comment le préparer. Voici comment retrouver les repères utiles, aliment par aliment.')+`<section><h2>Commencer par l’aliment et sa préparation</h2><p>Une mozzarella au lait pasteurisé, un brie froid et un fromage dans un plat entièrement cuit n’appellent pas la même réponse. Le guide garde ces distinctions plutôt que d’interdire toute une famille.</p><p>${link('/aliments/','Consulter la liste complète des aliments')}</p>${categoryLinks}</section><section><h2>Comprendre les indications du guide</h2><dl class="seo-definitions">${Object.values(D.statuses).map(s=>`<dt>${esc(s.label)}</dt><dd>${esc(s.description)}</dd>`).join('')}</dl><p>${link('/aliments-a-eviter-enceinte/','Aliments à éviter')}${' · '}${link('/aliments-a-limiter-enceinte/','Aliments à limiter')}</p></section><section><h2>Trois questions pour préparer un repas</h2><h3>Quelle est la forme du produit ?</h3><p>Lisez le type d’aliment, sa composition et le traitement indiqué : cru, pasteurisé, fumé, mariné ou cuit. Le nom commercial seul ne suffit pas.</p><h3>Comment sera-t-il préparé ?</h3><p>Retrouvez dans chaque fiche le lavage, la cuisson ou les alternatives proposés. Le fait d’être immunisée contre la toxoplasmose ne protège pas des autres infections alimentaires.</p><h3>Comment est-il conservé ?</h3><p>Vérifiez les dates, les consignes après ouverture et la conservation indiquée sur l’emballage. La préparation et la conservation font partie de la réponse, même pour un aliment compatible.</p>${sources(['spf','toxo'])}</section><section><h2>Passer des précautions aux recettes</h2><p>Les recettes gratuites donnent les ingrédients, les étapes et les précautions grossesse. Vous pouvez ensuite adapter les portions et préparer vos courses dans l’application.</p>${link('/recettes-grossesse/','Voir les recettes pour la grossesse','seo-button')}</section>`+attribution()+caution()+cta());
  const free=D.recipes.filter(r=>freeIDs.has(r.id));
  add('/recettes-grossesse/','Recettes pour la grossesse : 20 idées gratuites','20 recettes gratuites à cuisiner enceinte : ingrédients, étapes, allergènes et précautions sourcées. Des idées pour varier vos repas.',intro('Des recettes pour manger enceinte','20 recettes complètes en accès libre, avec les précautions grossesse à retrouver dans chaque préparation.')+recipeList(free)+caution()+cta(),{type:'CollectionPage',schema:[{'@type':'ItemList',itemListElement:free.map((r,i)=>({'@type':'ListItem',position:i+1,url:absolute(routes.recipe(r))}))}]});
  add('/sources-et-methode/','Sources et méthode du guide alimentaire Poum','Comment Poum prépare ses fiches grossesse : sources sanitaires, distinction entre conseils spécifiques et généraux, limites et corrections.',intro('D’où viennent les réponses de Poum ?','Les fiches rassemblent des repères d’autorités sanitaires et expliquent comment ils s’appliquent à l’aliment ou à sa préparation.')+'<section><h2>Qui publie ces fiches ?</h2><p>Poum est une application éditée par Poilon Software. Les fiches sont des synthèses éditoriales préparées avec l’aide d’outils d’IA à partir des références citées. Elles n’ont pas fait l’objet d’une validation clinique indépendante et ne remplacent pas les conseils de votre sage-femme ou médecin. La citation d’une autorité ne signifie pas qu’elle approuve Poum.</p><h2>Comment lire les références ?</h2><p>Une fiche distingue les recommandations qui citent l’aliment ou la préparation et l’application de conseils généraux à une famille. Les sources sont placées près des explications. Des sources étrangères complètent les repères français ; leur organisme et leur pays sont indiqués.</p><h2>Une indication, avec ses conditions</h2><p>La forme, la cuisson, le lavage et la conservation peuvent changer le conseil. Quand les informations ne suffisent pas, le guide utilise « À vérifier ». Il ne déduit jamais une absence de risque d’une information manquante.</p><h2>Produits Open Food Facts</h2><p>Les fiches de produits sont collaboratives et peuvent être incomplètes. La détection d’ingrédients ne certifie pas la compatibilité d’un produit avec la grossesse. Cette base reste distincte des fiches éditoriales du guide. Les données sont sous <a href="https://opendatacommons.org/licenses/odbl/1-0/">licence ODbL</a> ; les images de produits relèvent de CC BY-SA.</p><h2>Recettes et illustrations</h2><p>Les recettes sont des propositions culinaires, pas un programme nutritionnel individualisé. Les photographies d’inspiration proviennent d’<a href="https://unsplash.com/license">Unsplash</a> et peuvent différer du plat décrit. Les illustrations de grossesse sont générées par IA et décoratives.</p><h2>Signaler une erreur</h2><p>Vous pouvez signaler une erreur dans le <a href="https://github.com/Poilon/mat/issues">suivi public du projet</a>, en précisant l’URL de la fiche et la source concernée. Évitez d’y publier des informations personnelles ou médicales.</p></section>'+attribution()+'<section><h2>Les références utilisées</h2>'+sources(Object.keys(D.sources))+'</section>'+caution());
  pages.push(...D.foods.map(foodPage),...free.map(recipePage));
  const unique=new Set(pages.map(p=>p.url));if(unique.size!==pages.length)throw Error('Duplicate SEO URL');
  return pages;
}
function writeSEO(destination,{mirror=false}={}) {
  const index=path.join(destination,'index.html');let html=fs.readFileSync(index,'utf8');
  html=html.replace(/<title>[\s\S]*?<\/title>/,`<title>${HOME_TITLE}</title>`).replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${HOME_DESCRIPTION}">`).replace(/<meta property="og:title" content="[^"]*">/,`<meta property="og:title" content="${HOME_TITLE}">`).replace(/<meta property="og:description" content="[^"]*">/,`<meta property="og:description" content="${HOME_DESCRIPTION}">`);
  const graph={'@context':'https://schema.org','@graph':[organization,{'@type':'WebSite','@id':ORIGIN+'/#website',name:'Poum',url:ORIGIN+'/',inLanguage:'fr-FR',publisher:{'@id':ORIGIN+'/#organization'}}]};
  html=html.replace('</head>',`<meta name="robots" content="${mirror?'noindex,follow':'index,follow,max-image-preview:large'}"><meta property="og:site_name" content="Poum"><meta property="og:locale" content="fr_FR"><link rel="stylesheet" href="${mirror?'https://poum.app':''}/assets/seo.css?v=1"><script type="application/ld+json">${ld(graph)}</script></head>`);
  let fallback=homeContent();if(mirror)fallback=fallback.replace(/(href|src)="\//g,`$1="${ORIGIN}/`);
  html=html.replace(/<div id="app">[\s\S]*?<\/div>\s*<dialog/,`<div id="app"><div class="seo-fallback">${fallback}</div></div>\n  <dialog`);
  fs.writeFileSync(index,html);
  if(mirror)return {pages:0};
  const pages=collectPages();
  for(const p of pages){const dir=path.join(destination,p.url);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),p.html);}
  const urls=['/',...pages.map(p=>p.url)];
  fs.writeFileSync(path.join(destination,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(url=>`<url><loc>${absolute(url)}</loc></url>`).join('\n')}\n</urlset>\n`);
  fs.writeFileSync(path.join(destination,'robots.txt'),'User-agent: *\nAllow: /\nDisallow: /api/\nDisallow: /*?checkout=\nDisallow: /*?password-reset=\n\nSitemap: https://poum.app/sitemap.xml\n');
  fs.writeFileSync(path.join(destination,'404.html'),page({url:'/404',title:'Cette page est introuvable',description:'Retrouvez les aliments et recettes du guide Poum.',body:'<h1>Cette page est introuvable.</h1><p>'+link('/aliments/','Retrouver un aliment')+'</p>',crumbs:[['Accueil','/'],['Page introuvable','/404']]}).replace('index,follow,max-image-preview:large','noindex,follow'));
  return {pages:urls.length};
}
module.exports={writeSEO,collectPages,homeContent,routes,categories,HOME_TITLE,ORIGIN};
